### ISSUE TITLE
not working with persian and arabic numbers

### ISSUE THREAD

**Issue by Meti27** [dm4t2/vue-currency-input#100]
thanks for awesome package.
i'm trying to use with persian and arabic numbers , but its not accept the numbers:
`۰ , ۱ , ۲ , ۳ , ۴ , ۵ , ۶ , ۷ , ۸ , ۹`
i try to convert it to english numebrs in watch section : 
```
...
    watch: {
        amount(){
            return fx.toEnglishNumber(this.amount);
        }
    }
...
```

but its not working either .
this is all my codes : 
html:
```html
<input class="form-control" name="amount" v-currency="{ currency: currency , precision:0  }" v-model="amount">
```
javascript:
```

const app = new Vue({
    el: '#app',
    data: {
        amount: 20000,
        currencySymbol: ' تومان',
        position: 'suffix'
    },
    computed: {
        currency() {
            return { [this.position]: this.currencySymbol }
        }
    },
    watch: {
        amount(){
            return fx.toEnglishNumber(this.amount);
        }
    }
});
```
the `toEnglishNumber` Properly convert to english number .

what do you suggest?

**Comment by Dissociable** [comment]
@Meti27 
Watch and return?
`<input class="form-control" name="amount" v-currency="{ currency: currency , precision:0  }" v-model="amountCurrency">`

```
data: {
        amount: 20000,
        currencySymbol: ' تومان',
        position: 'suffix'
    },
    computed: {
        currency() {
            return { [this.position]: this.currencySymbol }
        },
        amountCurrency: {
            get: function () {
                return this.amount;
            },
            set: function (newValue) {
                this.amount = fx.toEnglishNumber(this.amount);
            }
        },
    },
```

Give it a try

**Comment by Meti27** [comment]
thank you.
i tried it , no errors but not working.
it accept nothing. no persian number no english and no charachters. nothing.

**Comment by Dissociable** [comment]
@Meti27 
https://glitch.com/~v-currency-persian-numbers

**Comment by Meti27** [comment]
and its not working either just try to type  one persian number like `۵` and see .
anyway i don't want to use another package because i use this in many pages and its not good idea.
i want to fix this.
if any one can help i will be glad.

**Comment by dm4t2** [comment]
Hi, thanks for reporting. As you already noticed, Vue Currency Input currently only supports european/english numbers. But I agree it would be a nice enhancement. I will have a look on this 🚀

**Comment by Dissociable** [comment]
> 
> 
> and its not working either just try to type one persian number like `۵` and see .
> anyway i don't want to use another package because i use this in many pages and its not good idea.
> i want to fix this.
> if any one can help i will be glad.

That works

**Comment by Meti27** [comment]
@dm4t2 Great,   thanks a lot.

**Comment by Meti27** [comment]
@Dissociable  thanks , works with english number no persian.

![Untitled Project](https://user-images.githubusercontent.com/11253027/77619870-c0c18500-6f56-11ea-8833-cd258bab6510.gif)

the phone language is persian.
or on the web if copry `۵` past into the text box its not work too.

**Comment by dm4t2** [comment]
Support for arabic numbers has been added in [Release 1.18.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.18.0) 🎉 

You can test it on the [playground](https://dm4t2.github.io/vue-currency-input/playground/) with locale `ar-SA` and currency `SAR`.

**Comment by Meti27** [comment]
@dm4t2  Thanks , but seems not working with 
```
۰ , ۱ , ۲ , ۳ , ۴ , ۵ , ۶ , ۷ , ۸ , ۹
```
I copied it , but not pasting.

**Comment by dm4t2** [comment]
You might want to use locale `fa-IR` and currency `IRR` for persian numbers (for example Iran). I added this showcase to the playground.

**Comment by Meti27** [comment]
@dm4t2  Oh right , thanks Alot.
