### ISSUE TITLE
Acessing setValue() globally like this.$parseCurrency

### ISSUE THREAD

**Issue by khizarshaikh** [dm4t2/vue-currency-input#101]
Hi @dm4t2  i would like to access setValue like this.$parseCurrency but i am not able to access it. Any help would be highly appreciated.

**Comment by dm4t2** [comment]
Hi, if you use the `v-currency` directive the `setValue` method is your friend: https://dm4t2.github.io/vue-currency-input/api/#setvalue

The `<currency-input>` component exposes also a `setValue` method: https://dm4t2.github.io/vue-currency-input/config/#methods

**Comment by Kraysh** [comment]
We need a Vue instance method like the $parseCurrency when installed as Vue Plugin.
Something like this.$setValue

**Comment by khizarshaikh** [comment]
> We need a Vue instance method like the $parseCurrency when installed as Vue Plugin.
> Something like this.$setValue

Exactly
