### ISSUE TITLE
When thousand separator is point parseCurrency returns incorrect value

### ISSUE THREAD

**Issue by guilherme-santos** [dm4t2/vue-currency-input#102]
Hello, it seems I found a misbehavior.

In the case of Germany, where thousand separator is `.` and decimal is `,` and if I set `hideNegligibleDecimalDigits` to true, the result returned from `parseCurrency` is incorrect.

If you type "1.234", which is 1234 I'll return 1.234...

Here is how to reproduce:
https://codepen.io/xguiga/pen/dyYPopB
Just play around with focus and blur that you can see the number changing...

Let me know if you need any other information, in the meanwhile I'll try to take a look at the code.

**Comment by dm4t2** [comment]
It is a little tricky. `1.234` can not be parsed unambiguously in this case, since it is valid string representation of a number and the grouping symbol will be interpreted as decimal symbol.

**Comment by guilherme-santos** [comment]
Thanks for you answer, maybe it’s not clear the implementation for me, but based in the locale you should know it’s the grouping symbol, no?

**Comment by dm4t2** [comment]
Right, but on the hand string values matching a number needs a special treatment: 
https://github.com/dm4t2/vue-currency-input/blob/99bb05857321011c2c80220e471f9b539917300f/src/utils/parse.js#L7

Otherwise float values will not be handled correctly.

**Comment by guilherme-santos** [comment]
Got it... 
This function is generic to handle numbers and strings, right?
Do you have any idea where I could intercept the input (which will be always string and try in some way convert to number before to pass for this function?
I'm using v-currency directive.

**Comment by dm4t2** [comment]
Good news: I finally found a solution for this issue. It will be fixed in next the release.

**Comment by dm4t2** [comment]
Fixed in [Release 1.18.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.18.1) 🎉
