### ISSUE TITLE
why value-range not work on v-currency or main.js?

### ISSUE THREAD

**Issue by SwanIsDead** [dm4t2/vue-currency-input#103]
`
<el-input v-else-if="isNumber" v-currency="{ 'value-range': { min: 0, max: 999 } }" v-model="form.field"></el-input>
`
`
Vue.use(VueCurrencyInput, {
  globalOptions: {
    currency: null,
    "value-range": { min: 0, max: 999 }
  }
});
`

**Comment by SwanIsDead** [comment]
I tried it again and found that it should be used valueRange,thanks. But now I have a new problem: when I use v-current, the default value is not formatted.

**Comment by dm4t2** [comment]
I can not reproduce your issue:
https://codesandbox.io/s/using-vue-currency-input-with-element-fvp3t?file=/src/App.vue
