### ISSUE TITLE
Comma causing  [object Array Iterator] error

### ISSUE THREAD

**Issue by pashtet86** [dm4t2/vue-currency-input#104]
Hi,
If the first symbol is comma it's causing this error.

<img width="300" src="https://user-images.githubusercontent.com/11823971/79510159-8161f200-8045-11ea-87db-e8c361225160.png">

https://codesandbox.io/s/cranky-hopper-n04vw?file=/src/App.vue

**Comment by ICATT** [comment]
Same here. As a workaround, we trigger this method @keydown:
```
onKeyDown (e) {
      const startWithComma = e.srcElement.selectionStart === 0 && e.keyCode === 188
      if (startWithComma) {
        e.preventDefault()
      }
    }
```

**Comment by pashtet86** [comment]
I'm wondering how it's actually works on [official playground](https://dm4t2.github.io/vue-currency-input/playground/) without any issue

**Comment by dm4t2** [comment]
Hi, thanks for reporting! There's a problem in the compiled ES5 code of the bundle caused by [Bublé](https://github.com/bublejs/buble).

This does not affect the docs/playground because [Babel](https://github.com/babel/babel) is used here.

**Comment by dm4t2** [comment]
I added a workaround for the Bublé issue in [Release 1.18.2](https://github.com/dm4t2/vue-currency-input/releases/tag/1.18.2) 🎉
