### ISSUE TITLE
Some alphabetical keys are interpreted as zero

### ISSUE THREAD

**Issue by ICATT** [dm4t2/vue-currency-input#105]
When either of the following keys `acbejorty` are pressed, the component interprets it as zero. Is this expected behaviour?

**Comment by dm4t2** [comment]
No, this bug is related to #104. 
On the [playground](https://dm4t2.github.io/vue-currency-input/playground/) it works as expected.

**Comment by dm4t2** [comment]
Fixed in [Release 1.18.2](https://github.com/dm4t2/vue-currency-input/releases/tag/1.18.2) 🎉
