### ISSUE TITLE
The valueAsInteger key does not seem to work in globalOptions

### ISSUE THREAD

**Issue by dominx99** [dm4t2/vue-currency-input#106]
I am using nuxt, so I added that to modules section within globalOptions

`
    ['vue-currency-input/nuxt', {
      globalOptions: {
        currency: null,
        distractionFree: true,
        allowNegative: false,
        valueAsInteger: true,
        autoDecimalMode: true,
      },
    }],
`

and when I want to parse currency without second parameter (options):

`
      realPrice () {
        return parseCurrency(this.form.price)
      },
`

I am getting "TypeError: Cannot read property 'valueAsInteger' of undefined" error

But when I add options parameter with valueAsInteger key it works well, other options from globalOptions also work

`
      realPrice () {
        return parseCurrency(this.form.price, { valueAsInteger: true })
      },
`

**Comment by dm4t2** [comment]
Hi, the `options` argument is only optional if you use the instance method `$parseCurrency`.
See also: https://dm4t2.github.io/vue-currency-input/api/#parsecurrency
