### ISSUE TITLE
da-DK locale changes initial value

### ISSUE THREAD

**Issue by bonqus** [dm4t2/vue-currency-input#108]
When the locale is set to da-DK the initial value is changed from 20 to 2000
https://jsfiddle.net/bonqus/n2u0hkfc/

**Comment by gobonja** [comment]
@dm4t2 I can confirm this.
Same thing happens with all locales that use dots for thousands and commas for decimals.

**Comment by dm4t2** [comment]
@bonqus You should not use the `v-currency` directive on the `<currency-input>` component. Replace it with `v-bind` and it will work as expected: https://codesandbox.io/s/vue-currency-input-108-hdkmd?file=/index.html
