### ISSUE TITLE
currency-input fails to load properly in Safari 12.1 

### ISSUE THREAD

**Issue by rthreei** [dm4t2/vue-currency-input#109]
vue-currency-input uses a browser api [Intl.NumberFormat.prototype.formatToParts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts) not supported by Safari 12.1 (Mojave macOS)

As as a result, the input fails to load properly and throws the following error:
```
console error: TypeError: t.formatToParts is not a function
```

https://github.com/dm4t2/vue-currency-input/blob/1e4814d55218198807b0d2ef563f96751099b7cb/src/utils/createCurrencyFormat.js#L2

**Comment by dm4t2** [comment]
See https://github.com/dm4t2/vue-currency-input/issues/15#issuecomment-618053196
