### ISSUE TITLE
locale uk fails to parse

### ISSUE THREAD

**Issue by messiahUA** [dm4t2/vue-currency-input#110]
When I'm setting locale to 'uk' function "parse" fails check on fractions and returns null if value is > 999.

For example input value is "25000", it gets formatted as "25,000.00", numberParts [0: "25" 1: "000.00"] and fraction doesn't match(/^\d+$/g)

version 1.18.2

**Comment by dm4t2** [comment]
Works fine for me:
https://codesandbox.io/s/vue-currency-input-110-ljdzw?file=/index.html

**Comment by messiahUA** [comment]
I've tried to set locale as a prop for the input and it is ok, but the issue occurs when I set it as a global option. Sorry, I'm new to Vue, not sure how to set it as global in codesandbox (i'm using webpack).

**Comment by dm4t2** [comment]
Check this out: https://codesandbox.io/s/vue-currency-input-110-ylq5u

If you use the `$parseCurrency` instance method, the `options` argument is optional and falls back to the plugin global options. See also https://dm4t2.github.io/vue-currency-input/api/#parsecurrency

**Comment by messiahUA** [comment]
ok, I give up... I don't understand why it works on codesandbox

I've stripped down almost everything in my code and I have only:
<currency-input :value="9999"></currency-input>

I see where the problem is, but I don't understand why it is a case only on my local environment. currency-input component created has this.formattedValue which uses this.locale which is undefined when I set it as a global option and obviously it works if it is a prop to the component. Basically, on the first load of the component value is formatted incorrectly and input is empty. All the following interaction works fine, so the problem is only in created and I don't see where this.locale should receive value from global options.

**Comment by messiahUA** [comment]
@dm4t2 if I'm not mistaken your second sandbox uses an old version of the component and https://github.com/dm4t2/vue-currency-input/commit/2793dc51bc9d16c18a94388c51bb227c966a1cd3 introduces the mentioned string.

**Comment by dm4t2** [comment]
> Basically, on the first load of the component value is formatted incorrectly and input is empty. 

You're right. The initial value formatting does not respect the `locale` of the global options. I will fix this.

**Comment by dm4t2** [comment]
Fixed in [Release 1.18.3](https://github.com/dm4t2/vue-currency-input/releases/tag/1.18.3) 🎉
