### ISSUE TITLE
Error on Enter key press

### ISSUE THREAD

**Issue by webgio** [dm4t2/vue-currency-input#115]
I have an error on pressing the Enter key when in focus on currency-input fields:

```
onloadwff.js:71 Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
```

I should point out that the fields initially are disabled. After turning disabled off, everything seems working but I keep seeing errors in the console when hitting the Enter key.

**Comment by dm4t2** [comment]
Please provide a code example (for example [CodeSandbox](https://codesandbox.io/s/vue)) for reproducing your issue. The error log actually says nothing and seems not be related to vue-currency-input.

**Comment by alexsonnay** [comment]
Hello, 

I have a possibly related issue : 

when clicking outside of input => value is formatted perfectly (3 000 $)👍
when pressing Enter => value isn't formatted at all in the input (3000) ❌

Any idea why the number isn't formatting when pressing Enter ?
