### ISSUE TITLE
locale de-DE inital wrong parse

### ISSUE THREAD

**Issue by oneMatti** [dm4t2/vue-currency-input#116]
the inital value (only) will be parsed to a wrong formatted string

number 12.34 to string 1.234,00 € (expected: 12,34 €)

https://codesandbox.io/s/de-de-eur-v-currency-init-parsed-wrong-6zm4g?file=/src/App.vue

**Comment by dm4t2** [comment]
Hi, you can not use number values as model when using the `v-currency` directive since it works directly on the formatted string. The initial value needs to be also a currency formatted string matching the configured `locale` and `currency`, `"12,34"` in your example.
