### ISSUE TITLE
Mask applying wrong in pt-BR

### ISSUE THREAD

**Issue by kevinmelo** [dm4t2/vue-currency-input#117]
Using this [codesandbox](https://codesandbox.io/s/vue-currency-input-110-ylq5u)

Change `locale` to 'pt-BR', don't need the currency option

Change string value in the `App.vue` from "1234" to "1234.25"
The expected behavior is `1.234,25` but got the `123.425,00`

**Comment by dm4t2** [comment]
I forked it for you: https://codesandbox.io/s/vue-currency-input-114-9omq 
It's the same issue as with #116.

**Comment by kevinmelo** [comment]
Hey @dm4t2 thanks for the anwser.

It's not be a good update to accept float/double values?  As string i undertand can be a litttle complicate but as number...

**Comment by dm4t2** [comment]
If you want to use number values as model you can use the `<currency-input>` component or my `<v-currency-field>` adaption for Vuetify: https://codesandbox.io/s/using-vue-currency-input-with-vuetify-kd7d1?file=/src/components/VCurrencyField.vue
