### ISSUE TITLE
not aloud user add cents

### ISSUE THREAD

**Issue by murilolivorato** [dm4t2/vue-currency-input#119]
Hello , I am producing a property real estate website , and I need a  vue input that not aloud the user to change the cents .

so if the user type like this -

50.000

it will be like this -

50.000,00 

and not aloud the user to change the cents .
it is that possible ? thanks

**Comment by murilolivorato** [comment]
I need to aloud decimals , but with decimals locked

**Comment by dm4t2** [comment]
Hi, you can modify the value to an integer in the `change` event listener. 
See this example: https://codesandbox.io/s/vue-currency-input-119-2xbkk?file=/src/App.vue
