### ISSUE TITLE
Currency Symbol Disappears

### ISSUE THREAD

**Issue by jzstern** [dm4t2/vue-currency-input#120]
Thanks for the awesome plugin!

Maybe this is intentional, but I think it would be a better UX if the currency symbol persisted when the user focused on the input and typed in the amount (:

**Comment by dm4t2** [comment]
Hi, you can customize the default behavior by setting the `distraction-free` prop to either `false` or `{hideCurrencySymbol: false}`.

See https://dm4t2.github.io/vue-currency-input/config/#component 
Or check out the playground: https://dm4t2.github.io/vue-currency-input/playground/

**Comment by jzstern** [comment]
Missed that in the docs, my apologies. Thanks for the info!
