### ISSUE TITLE
No formatting when pressing Enter

### ISSUE THREAD

**Issue by alexsonnay** [dm4t2/vue-currency-input#125]
Hello,

Thanks for this awesome plugin ! My issue :

when clicking outside of input => value is formatted perfectly (3 000 $)👍
when pressing Enter => value isn't formatted at all in the input (3000) ❌

Any idea why the number isn't formatting when pressing Enter ?

ℹ️
when clicking outside => 3 identical vuex mutations (setter) are executed
when pressing Enter => only one vuex mutation (setter) is executed

**Comment by JoseManueIbnzLora** [comment]
add
v-on:keyup.enter="$event.target.blur()" 
work for my

**Comment by dm4t2** [comment]
Hi, currently a `change` event is only triggered on blur (in case the value has been changed). This differs indeed to the native change event behavior, which is also triggered when pressing "Enter". I will look at it.

**Comment by dm4t2** [comment]
Fixed in [Release 1.19.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.19.1). Now a `change` event will also be triggered when pressing enter.
