### ISSUE TITLE
Formatting does not work for Swiss Franc(locale used is fr-CH)

### ISSUE THREAD

**Issue by shivam1646** [dm4t2/vue-currency-input#127]
`<currency-input currency="CHF" locale="fr-CH" />`

When using the above configuration:

1. It does not allow input of decimal digits.
2. By default adds two zeroes at the end of input. (Eg: 2453(input) --> 245 300 CHF(output))
3. Works correctly when precision is 0.

By digging online, I found that the decimal separator for `fr-CH` currency is `.` while the one used here is `,`. Can you help me with this?

**Comment by dm4t2** [comment]
Interesting... first time the decimal symbol is different for a locale regarding its decimal/currency formatting:

`Number(1).toLocaleString('fr-CH', {minimumFractionDigits: 2})` outputs `1,00`
`Number(1).toLocaleString('fr-CH', {style: 'currency', currency: 'EUR'})` outputs `1.00 €`

Unfortunately the current implementation relies on the fact, the decimal symbol is equal for both formats causing your issue.

**Comment by shivam1646** [comment]
Hey! Thanks for the reply. Will you be looking into this or is there maybe a workaround?

**Comment by dm4t2** [comment]
I will look into this. In the meantime, you can use `locale="fr"` as a workaround.

**Comment by shivam1646** [comment]
Okay. Thanks.

**Comment by dm4t2** [comment]
Fixed in [Release 1.19.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.19.1) 🎉

**Comment by shivam1646** [comment]
> Fixed in [Release 1.19.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.19.1) 🎉

Thank you.
