### ISSUE TITLE
Value isn't formatting from Vuex store since 1.19.0

### ISSUE THREAD

**Issue by alexsonnay** [dm4t2/vue-currency-input#128]
Solution #107 isn't working with 1.19.0

https://codesandbox.io/s/using-vue-currency-input-with-buefy-7ejdo

**Comment by dm4t2** [comment]
I updated my reference Buefy example:
https://codesandbox.io/s/using-vue-currency-input-with-buefy-pnl3q?file=/src/components/BCurrencyInput.vue

**Comment by alexsonnay** [comment]
How would it work with lazy option ?

**Comment by dm4t2** [comment]
Same issue as for Vuetify in #122: You have to use to `native` modifier for the `change` event:
https://codesandbox.io/s/vue-currency-input-128-vupgv?file=/src/components/BCurrencyInput.vue:34-63
