### ISSUE TITLE
input 12345678901234567 see 12345678901234568

### ISSUE THREAD

**Issue by sergeyBreslavets** [dm4t2/vue-currency-input#129]
input 12345678901234567 see 12345678901234568   ((

**Comment by dm4t2** [comment]
You are trying to enter a number > [MAX_SAFE_INTEGER](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

This should be validated on input.

**Comment by dm4t2** [comment]
Fixed in [Release 1.19.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.19.1) 🎉
