### ISSUE TITLE
Formatting when pressing Enter not working with suffix

### ISSUE THREAD

**Issue by alexsonnay** [dm4t2/vue-currency-input#131]
When pressing Enter, input isn't always formatting :

currency: 'EUR' ✅
currency: { suffix: ' x3b²' } ❌

You didn't allow to reopen the previous issue so I created a new one I hope that's okay.

**Comment by dm4t2** [comment]
When you press enter there's only a `change` event triggered and no formatting applied at all, independent of the configured `currency`. The formatting changes **only** when the input loses the focus (assuming `distraction-free` is set to `true`).

> You didn't allow to reopen the previous issue so I created a new one I hope that's okay.

You can always add comments to closed issues. I will reopen the issue if required.

**Comment by alexsonnay** [comment]
Distraction-free is set to false in my case. But when going out of the input when pressing Enter, the number loses the format, only currency is an object. Not when it's a string.

**Comment by dm4t2** [comment]
Please provide a [CodeSandbox](https://codesandbox.io/s/vue) for reproducing your issue.
