### ISSUE TITLE
Format value immediately after value changed by javascript

### ISSUE THREAD

**Issue by tonexv** [dm4t2/vue-currency-input#132]
Say I have two input elements: input1 and input2

When I change the value of input1, input2's value would be changed by some js function. Currently, input2 formats the currency only when I put the cursor on input2, then putting the cursor to another input, say input3.

How do I set it up so that when the value of input2 is changed programatically by a js function, the formatting immediately happens without having to focus (then focus out) on the input?

Thanks.

**Comment by dm4t2** [comment]
Hi, you can use the `setValue` API method:
https://dm4t2.github.io/vue-currency-input/api/#setvalue
https://codesandbox.io/s/vue-currency-input-set-value-programmatically-rv95r?file=/src/App.vue
