### ISSUE TITLE
v-currency directive and rules validations.

### ISSUE THREAD

**Issue by Engel94Ramirez** [dm4t2/vue-currency-input#134]
- When v-text-field component has a v-currency directive and rules, by clicking de input fire a validation(on focus) without writing anything yet, and the rule is activated with the error, Is there any way to fix this?

![image](https://user-images.githubusercontent.com/43154094/85926810-94741800-b867-11ea-802d-a1fbdc159bdd.png)

And the code: 
<v-text-field dense @change="someFunction" prefix="$" v-currency="config"
                  :value="someValue" label="Example" outlined
                  :rules="rules">
                </v-text-field>

**Comment by dm4t2** [comment]
Hi, thanks for reporting. An `input` event is incorrectly triggered on focus for empty input fields. I will fix this.

**Comment by dm4t2** [comment]
Fixed in [Release 1.20.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.20.0) 🎉
