### ISSUE TITLE
<input v-currency value quirkyness

### ISSUE THREAD

**Issue by codemonkey76** [dm4t2/vue-currency-input#137]
I am using <input with the v-currency attribute, i am also using v-model to set the value, if I change the value in the control, everything is fine, and the amount is formatted as currency, if i set the value outside of the control (in my parent vue component, the value updates in the currency input, but is not formatted as currency, also if i click in the currency input it reverts the value to the original value.

**Comment by dm4t2** [comment]
Hi, you have to use `setValue` API method for external changes:

https://dm4t2.github.io/vue-currency-input/api/#setvalue
https://codesandbox.io/s/vue-currency-input-set-value-programmatically-rv95r?file=/src/App.vue

Please note, that the value will be always the formatted string when using `v-model` together with the `v-currency` directive:
https://dm4t2.github.io/vue-currency-input/guide/#directive
