### ISSUE TITLE
prevent overriding input value with threshold when using value-range option

### ISSUE THREAD

**Issue by Chup4Chups** [dm4t2/vue-currency-input#138]
Hi,

For value-range, the documentation say "The validation is triggered on blur and automatically sets the respective threshold if out of range."
As it can be confusing in term of UX, I would like to disable this feature but I cannot find how.
However, I still want to use range validation to trigger invalid-feedback on the input.

Any advice about how to proceed ?

**Comment by dm4t2** [comment]
Hi, feel free to add your custom value range validation if the built-in does not meet your requirements.

You can use [VeeValidate](https://logaretm.github.io/vee-validate/) for example:
https://codesandbox.io/s/vue-currency-input-value-range-validation-with-vee-validate-xkk0v

**Comment by Chup4Chups** [comment]
Hi,
Actually, the validation part does meet my requirements.
My only issue is about "automatically sets the respective threshold if out of range"
I just don't want to set the min / max threshold automatically if out of range.
Can you please advise how to achieve this ?
