### ISSUE TITLE
Money Length issue

### ISSUE THREAD

**Issue by venkateshparihar** [dm4t2/vue-currency-input#139]
the currency input act weird after enter 16 digits .can i set currency with no length limit

**Comment by mattelen** [comment]
I have just come across this bug too (or something similar at least). This can be replicated on the playground page (https://dm4t2.github.io/vue-currency-input/playground/) by setting the locale to default & ISO code to USD. If I type '444434.12', the value is converted to 'US$444.43', which is not ideal. See attached screenshots of the playground setup with before and after shots of defocusing the input
![Before](https://user-images.githubusercontent.com/9289772/87770168-90a83580-c816-11ea-8ee1-7f72a6419889.png)
![After](https://user-images.githubusercontent.com/9289772/87770172-9140cc00-c816-11ea-89d3-e41840f746cf.png)

.

**Comment by GordonBlahut** [comment]
@mattelen Wow, that should probably be its own issue. Seems major.

I see the same behaviour in 1.20.0 and 1.20.1 but 1.19.1 seems to work as expected so I'm guessing it was introduced in the changes to allow input of decimal separators different from the current locale.

**Comment by mattelen** [comment]
@GordonBlahut Having another look at this, yeah you are right, these are two separate issues - I'll create a new issue and will put in your extra research. Thanks

**Comment by dm4t2** [comment]
> the currency input act weird after enter 16 digits .can i set currency with no length limit

No, you can not enter a number larger than [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). See also #129.
