### ISSUE TITLE
Vue is not defined

### ISSUE THREAD

**Issue by shikharani16** [dm4t2/vue-currency-input#14]
I tried using it via CDN link provided
<script src="https://unpkg.com/vue-currency-input"></script>
I am getting following error

Uncaught ReferenceError: Vue is not defined
    at eval (eval at <anonymous> (eval at <anonymous> (dojo.js?v=1:341)), <anonymous>:7:15209)
    at runFactory (dojo.js?v=1:1120)
    at execModule (dojo.js?v=1:1249)
    at execModule (dojo.js?v=1:1240)
    at dojo.js?v=1:1284
    at guardCheckComplete (dojo.js?v=1:1264)
    at checkComplete (dojo.js?v=1:1279)
    at onLoadCallback (dojo.js?v=1:1439)
    at HTMLScriptElement.onLoad (dojo.js?v=1:1675)

It is pointing to this line
**(r=i.currency),u(e,l(t,r))}}};"undefined"!=typeof window&&**window.Vue&&window.Vue.use(x)**}(Vue);**

**Comment by dm4t2** [comment]
Have you included Vue before?

```
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-currency-input"></script>
```

Here is a working CodeSandbox example:
https://codesandbox.io/embed/vue-currency-input-direct-browser-usage-yjtci

**Comment by shikharani16** [comment]
Hi  I am  doing integration of  Vue componenet within  Dojo application.
require([
		     	"vue/vue",
		     	"vue/vuex",
		     	"vue/vee-validate"
				], function(Vue,Vuex,VeeValidate) {
		    Vue.use(Vuex);
   		    Vue.use(VeeValidate);
   
![Code](https://user-images.githubusercontent.com/29137636/59283049-8ddc2800-8c87-11e9-8ad4-804fa17b73be.jpg)
All these  are working fine. But when I add  vue-currency-input at the end
require([
		     	"vue/vue",
		     	"vue/vuex",
		     	"vue/vee-validate",
                        "vue/vue-currency-input"
				], function(Vue,Vuex,VeeValidate,VueCurrencyInput) {
	It gives the error.
Attached the screenshot of vue include in application

**Comment by dm4t2** [comment]
In the current release (1.5.1), the CDN link refers to an IIFE bundle that is only intended to be used directly in the browser as described in my previous comment.

I guess that your application requires a UMD bundle (that is not included in the current release). You can try an older version: https://unpkg.com/vue-currency-input@1.3.2/dist/vue-currency-input.umd.js

**Comment by shikharani16** [comment]
Hi
Thanks for the reply.With this version the load error is gone.My application is loading fine.I can see the input .js in my html.
require([
		     	"vue/vue",
		     	"vue/vuex",
		     	"vue/vue-currency-input"
				], function(Vue,Vuex,CurrencyInput) {      
   		    Vue.use(Vuex);
   		    Vue.use(CurrencyInput);
In  my code i have used it like
  <currency-input v-model="adder" style="width:50px;" :id="'seclineitemsteprateadder' + parentIndex +'_' + index"></currency-input>
but nothing  shows up in  Screen. In html I can see it like 
<currency-input id="seclineitemsteprateadder0_0" style="width: 50px;"></currency-input>
   		
I tried using it as Directive as well
 Vue.directive('currency', CurrencyInput);
but it hasnt done anything

**Comment by shikharani16** [comment]
attachmnet
<img width="577" alt="CurrencyLink" src="https://user-images.githubusercontent.com/29137636/59499709-944fe700-8eb5-11e9-83ba-97a7447c95cc.png">

**Comment by dm4t2** [comment]
After installing the plugin with `Vue.use()` you should be able to use the `<currency-input>` component or `v-currency` directive in your app's template. 

Are there any console errors? 
How do you include the component?

**Comment by shikharani16** [comment]
There  are no errors. I tried using it in as directive. Looks like it is not working as diective. I saw the  directive demo code in github also there value is mentioned as      **value: '$1,234.50',** so it is showing the same value. This is my fiddle
https://jsfiddle.net/xg8cyn3k/1/

**Comment by dm4t2** [comment]
The problem is that you use the the same data property for both inputs in your fiddle. The `<currency-input>` emits a number that will always overwrite the value in the input element using `v-currency`.
I edited your fiddle: https://jsfiddle.net/65rkotfq/1/
