### ISSUE TITLE
When using a different currency & locale, numbers are getting changed from what was entered

### ISSUE THREAD

**Issue by mattelen** [dm4t2/vue-currency-input#140]
I have found this bug which can be replicated on the playground page (https://dm4t2.github.io/vue-currency-input/playground/) by setting the locale to default & ISO code to USD. If I type '444434.12', the value is converted to 'US$444.43', which is not ideal. See attached screenshots of the playground setup with before and after shots of defocusing the input
Before
![Before](https://user-images.githubusercontent.com/9289772/87812818-b0604d80-c858-11ea-93fb-eb10bc4d817f.png)

After
![After](https://user-images.githubusercontent.com/9289772/87812833-b48c6b00-c858-11ea-81db-fdeb7f7802b3.png)

After a little discussion in #139 (where I originally thought we were talking about the same issue), @GordonBlahut said that he can see the same behaviour in 1.20.0 and 1.20.1, "but 1.19.1 seems to work as expected so I'm guessing it was introduced in the changes to allow input of decimal separators different from the current locale."
 
Hope that helps. Let me know if anyone has any further questions

**Comment by dm4t2** [comment]
Thanks for reporting. I will this fix shortly.

**Comment by dm4t2** [comment]
Fixed in [Release 1.20.2](https://github.com/dm4t2/vue-currency-input/releases/tag/1.20.2) 🎉

**Comment by mattelen** [comment]
Awesome, thanks so much @dm4t2!
