### ISSUE TITLE
valueAsInteger not working as expected

### ISSUE THREAD

**Issue by louis-l** [dm4t2/vue-currency-input#142]
Hi there,

Thanks for the awesome library.

I tried to play around with this but it does not look like its working as I expected. The example in [playround](https://dm4t2.github.io/vue-currency-input/playground/) is what I am after: enter `123` and the value is `12300`.

I forked the sanbox from https://dm4t2.github.io/vue-currency-input/api/#example and trying to set the `valueAsInteger: true` but the printed value is not integer, its string with currency symbol.

Please see [this codesandbox example](https://codesandbox.io/s/vue-currency-input-set-value-programmatically-pxuwo): enter `123` and blur the input, the value printed as `$123.00` as string, I want `12300` as integer.

Is there anything that Im missing here?

Thanks,

**Comment by louis-l** [comment]
Nevermind, found similar report in https://github.com/dm4t2/vue-currency-input/issues/137

For anyone having this issue, using `v-currency` directive will return the value as formatted string. To get the integer, you have to use `parseCurrency` (see [dov here)](https://dm4t2.github.io/vue-currency-input/api/#parsecurrency).

---

Im using ElementUI, so guessing that I have to create a custom component to wrap the `<el-input>`, `v-currency` directive and use `parseCurrency` at the same time.

Is there any better way to achieve this?

**Comment by dm4t2** [comment]
Right, you need a custom component when using Element:
https://codesandbox.io/s/using-vue-currency-input-with-element-ui-z8gik?file=/src/components/ElCurrencyInput.vue
