### ISSUE TITLE
Format currency data using this library

### ISSUE THREAD

**Issue by louis-l** [dm4t2/vue-currency-input#144]
Hi there,

Is there a way to use this library to format the data (pulled from database)?

Im currently using different libraries to parse and format monetary data because Im storing monetary using smallest unit (e.g. `10099` will be `$100.99`). So it would be great if I can use this awesome library to print `10099` as `$100.99` using the global configs.

Thanks

**Comment by dm4t2** [comment]
You can use the `value-as-integer` prop for that.
See: https://dm4t2.github.io/vue-currency-input/config/#props

**Comment by louis-l** [comment]
Sorry maybe I was not clear, what I meant was the ability to print `$99.00` as a static text, not using any `<input>` element.

Use case: in the shopping cart, I want to print the total amount as `$99.00` text/string, which stored in database as `9900` as integer.

**Comment by dm4t2** [comment]
This will not be addressed by my library. Just use [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) for printing currency formatted numbers.
