### ISSUE TITLE
Does not format "0"

### ISSUE THREAD

**Issue by sirzerator** [dm4t2/vue-currency-input#145]
Hi!

First of all, great component!

I've noticed a problem though when entering just "0" . I would expect the value to be formatted to whatever is configured, for example : "0,00$", but it just stays at "0" .

Thanks!

**Comment by dm4t2** [comment]
Thanks for reporting. This is of course not intended and will be fixed shortly.

**Comment by dm4t2** [comment]
Fixed in [Release 1.20.3](https://github.com/dm4t2/vue-currency-input/releases/tag/1.20.3) 🎉
