### ISSUE TITLE
new version seems to be unusable

### ISSUE THREAD

**Issue by Daniel4Digital** [dm4t2/vue-currency-input#149]
Can't make it work with the new version. Seems unusable now. :/

I understand that now we can't pass values directly, and only pass the element. So I am passing the $refs.input (and I've one with value)

But I get a TypeError: Cannot read property 'valueAsInteger' of undefined

EDIT: With the 1.20.3 version I was able to grab from the my backend API the value as a number 1000.53 and then using the setValue to insert on the input as already parsed as "1.000,53" (with pt-br). And when I submit, I want to submit as 1000.53, the same as I receive, and I was able to do with the parseCurrency, since I could send a new options object. (I'm using as directive, since Im using a custom input component)

So for now, I'll stay at 1.20.3, since I got it working.

**Comment by alex-w0** [comment]
I've upgraded also to the new version and didn't notice any different. I'm using v-model.number to save the value as an integer within the Vue instance.

**Comment by ThomasVanBroekhoven** [comment]
In my specific use case I cannot use the new version either. I have to pass it as a value together with the defined currency options. 
Also, I am surprised that this is not a new version e.g. 2.0. The breaking changes caused my application to 'break'. Nevertheless, glad to see that you're maintaining the plugin.

**Comment by dm4t2** [comment]
> Also, I am surprised that this is not a new version e.g. 2.0. The breaking changes caused my application to 'break'.

You're right, according to semantic versioning it should be a major version. In the past, I used to document the breaking changes  only in the [release notes](https://github.com/dm4t2/vue-currency-input/releases/tag/1.21.0). I will consider this for future releases.

Anyway, a code example for reproducing your issue would still be helpful. Thanks!

**Comment by Tovli** [comment]
I'm also heavily relying on parseCurrency and not only for component transformations. Is it possible to allow us to also use it without any element?

**Comment by Daniel4Digital** [comment]
This is what I am using now with 1.20.3:
https://codesandbox.io/s/vue-currency-input-set-value-programmatically-forked-e6r0h

After change to 1.21.0, in that fork above, try to hit submit again. You'll see an error "TypeError: this.$parseCurrency is not a function" (it doesnt exist, so, it was to be expected)

I changed:
return this.$parseCurrency(this.testValue, this.money); 
With:
return this.$ci.getValue(this.$refs.input); 

And when submit the error is now: "TypeError: Cannot read property 'valueAsInteger' of undefined".

Hope this can help you understand the use case. Basically I received always as number and submit always as number as I received. But on the input field I want to show the number parsed correctly according the user lang settings.

best regards

**Comment by dm4t2** [comment]
@Daniel4Digital The problem seems to be that the `el` argument of `getValue` does not point the native input element as described in the [docs](https://dm4t2.github.io/vue-currency-input/api/#getvalue) (note the warning).

Since your using a component wrapper for a `<mdb-input`> in your example it should be `this.$ci.getValue(this.$refs.input.$refs.mdbInput.$refs.input)`:
https://codesandbox.io/s/vue-currency-input-set-value-programmatically-forked-qhem5?file=/src/App.vue:1669-1731

I strongly recommend to encapsulate this a custom component so that you can use `v-model` directly with a number, for example:
https://codesandbox.io/s/using-vue-currency-input-with-mdbvue-qo10f?file=/src/components/MdbCurrencyInput.vue

@Tovli Please provide a CodeSandbox for demonstrating why `getValue` can not be used. Otherwise it's hard to understand.

**Comment by Daniel4Digital** [comment]
Thanks! It makes sense!

For those who may have the same problem: I tried to follow the same logic for the setValues and it worked too. BUT I needed to set the value on the mounted cycle, since the $refs doesn't exist on the beforeMount cycle.

All working good after all. Thanks a lot for the help dm4t2!

**Comment by Tovli** [comment]
@dm4t2 - I want to use the same library for my UI components as well as the javascript that support them.
So I have this function in a .js file:
`transformValueToNumber(value) {
      var parsedValue=parseCurrency(value.trim(), { locale: 'en' });
      return parsedValue;
    }`

AFAIK I cannot use getValue without a DOM element

**Comment by dm4t2** [comment]
@Tovli I finally came to the conclusion that the most flexible solution would be to provide both methods:

* `getValue` for getting a number value directly from the respective input element and
* `parse` for getting a number value from the formatted value and options

**Comment by dm4t2** [comment]
In [Release 1.22.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.22.0) the `parse` API method is back: https://dm4t2.github.io/vue-currency-input/api/#parse

@Daniel4Digital The usage of `getValue` has also been simplified: Now it accepts a `ref` argument that points directly to the HTML element or Vue component the `v-currency` directive is bound to.

**Comment by Kraysh** [comment]
> @Daniel4Digital The problem seems to be that the `el` argument of `getValue` does not point the native input element as described in the [docs](https://dm4t2.github.io/vue-currency-input/api/#getvalue) (note the warning).
> 
> Since your using a component wrapper for a `<mdb-input`> in your example it should be `this.$ci.getValue(this.$refs.input.$refs.mdbInput.$refs.input)`:
> https://codesandbox.io/s/vue-currency-input-set-value-programmatically-forked-qhem5?file=/src/App.vue:1669-1731
> 
> I strongly recommend to encapsulate this a custom component so that you can use `v-model` directly with a number, for example:
> https://codesandbox.io/s/using-vue-currency-input-with-mdbvue-qo10f?file=/src/components/MdbCurrencyInput.vue
> 
> @Tovli Please provide a CodeSandbox for demonstrating why `getValue` can not be used. Otherwise it's hard to understand.

Why this sandbox crashes if version of lib is changed to 1.22.3? Wasn't setValue supposed to work the same way of 1.21.0?
I having the same problem.
