### ISSUE TITLE
Incorrect value

### ISSUE THREAD

**Issue by sunshine--0817** [dm4t2/vue-currency-input#152]
输入中文之后取不到值

The value cannot be obtained after entering Chinese

**Comment by dm4t2** [comment]
Locale `en` only support latin digits (123...). Have you tried `zh-Hans-CN-u-nu-hanidec`?

See also the locales example on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
