### ISSUE TITLE
'locale' option not being respected in unit tests with Jest

### ISSUE THREAD

**Issue by fergardi** [dm4t2/vue-currency-input#153]
Hello!

First of all, thank you for your plugin. It has solved me many issues regarding currency apps for our clients so far.

I've created my own Typescript currency component following your suggestions in https://github.com/dm4t2/vue-currency-input/issues/1#issuecomment-471308652, which you can see in https://github.com/dm4t2/vue-currency-input/issues/1#issuecomment-682392140.

My component works fine in my app, as I can see while inspecting it with the Vue Dev Tools:

![image](https://user-images.githubusercontent.com/3602272/91538170-b34e6380-e917-11ea-98ae-b700845da229.png)

Comparing it with your playground looks like this is the expected results using my configuration options:

![image](https://user-images.githubusercontent.com/3602272/91538313-f4467800-e917-11ea-93d2-57c3352a50a3.png)

And this is my unit test:

```ts
import { expect } from 'chai';
import { Wrapper, createLocalVue, mount } from '@vue/test-utils';
import ElementUI from 'element-ui';
import ElCurrencyInput from './currency.vue';
import VueCurrencyInput from 'vue-currency-input';
import { expect as exp } from '@jest/globals';

const localVue = createLocalVue();
localVue.use(ElementUI);
localVue.use(VueCurrencyInput);

describe('ElCurrencyInput', () => {

  let component: Wrapper<ElCurrencyInput>;
  const currency: any = 77000000;

  beforeEach(() => {
    component = mount(ElCurrencyInput, {
      localVue,
      propsData: {
        value: currency,
      },
    });
  });

  test('Creates the component', () => {
    expect(component.exists()).to.equal(true);
    exp((component.vm as any).options).toStrictEqual({
      currency: null,
      locale: 'de-DE',
    });
  });

  test('Checks the value and formattedValue', () => {
    expect((component.vm as any).value).to.equal(currency);
    expect((component.vm as any).formattedValue).to.equal('77.000.000,00');
  });

});
```

But there must be some kind of problem because the expected formatted result is never achieved:

```
Expected value   "77.000.000,00"
    Received:
      "77,000,000.00"

    Message:
      expected '77,000,000.00' to equal '77.000.000,00'

    Difference:

    - Expected
    + Received

    - 77.000.000,00
    + 77,000,000.00
```

I think this is happening because the `locale` option is not being respected and is using the Jest runtime browser locale instead. Can this be the problem?

After looking into the coverage plugin, we can see that the `@Watch()` decorator (line 20) is never triggered:

![image](https://user-images.githubusercontent.com/3602272/91539129-25737800-e919-11ea-97dd-0fc7e8411444.png)

However, the `handleInput` is being fired correctly by the `@input` event, so I'm guessing that the watcher is not firing because I'm not changing the original `value` property, which is fine to me in this specific context.

I've also researched into your own unit tests (https://github.com/dm4t2/vue-currency-input/blob/master/tests/unit/directive.spec.js) to see if there was something I missed, but I cannot really tell. Could you (or anybody) give me some insight into the matter, please?

Thanks in advance.

**Comment by dm4t2** [comment]
Hi, you have use Node.js >= 13, which has full-icu mode enabled by default: https://nodejs.org/api/intl.html#intl_internationalization_support.

`await component.setProps({ value: 1 })` should trigger the watcher in your unit tests.

**Comment by fergardi** [comment]
Thank you for your response.

You were right in both cases:
- Running my tests with NodeJS14 solved the `intl` problem.
- Using `await component.setProps` solved the coverage trigger problem.

One last thing is happening to me. While running my tests in local mode, everything runs fine:

```
Test Suites: 36 passed, 36 total
Tests:       53 passed, 53 total
Snapshots:   0 total
Time:        16.911 s
```

But when I run the tests in Jenkins (with NodeJS14 as well), I got the following error:

```
+ npm run coverage
> siid@0.1.0 coverage /opt/jenkinsnode/workspace/SSCDAW_SIID_CI
> jest --silent --coverage

PASS src/router/index.spec.ts
PASS src/views/operation/table.spec.ts
PASS src/views/operation/form.spec.ts
PASS src/views/security/login.spec.ts
PASS src/main.spec.ts
PASS src/views/market/upload.spec.ts
FAIL src/components/currency.spec.ts
  ● ElCurrencyInput › Creates the component

    TypeError: Cannot read property 'setValue' of undefined

      28 | 
      29 |   private setValue(value: number) {
    > 30 |     setValue((this.$refs.elInput as ElInput).$refs.input as HTMLInputElement, value);
         | ^
      31 |   }
      32 | 
      33 |   private mounted() {

      at Object.setValue (node_modules/vue-currency-input/dist/vue-currency-input.umd.js:144:26)
      at VueComponent.setValue (src/components/currency.vue:30:1)
      at VueComponent.mounted (src/components/currency.vue:34:1)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
      at callHook (node_modules/vue/dist/vue.runtime.common.dev.js:4207:7)
      at Object.insert (node_modules/vue/dist/vue.runtime.common.dev.js:3133:7)
      at invokeInsertHook (node_modules/vue/dist/vue.runtime.common.dev.js:6326:28)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6543:5)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at Object.mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:13856:21)
      at Object.<anonymous> (src/components/currency.spec.ts:16:17)
```

It seems like Jenkins' NodeJS installation cannot find `import { setValue, getValue } from 'vue-currency-input';`. My component is in https://github.com/dm4t2/vue-currency-input/issues/1#issuecomment-682392140.

Thanks in advance.

**Comment by dm4t2** [comment]
Which version do use? Since [1.22.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.22.0) the `setValue` and `getValue` API methods have changed. 

You can now simply use: `setValue(this.$refs.elInput)`

See also my Element UI reference example: 
https://codesandbox.io/s/using-vue-currency-input-with-element-ui-z8gik?file=/src/components/ElCurrencyInput.vue
