### ISSUE TITLE
thousand separator is treated like a decimal point

### ISSUE THREAD

**Issue by Tovli** [dm4t2/vue-currency-input#154]
Hi,
When manually inserting thousand separator, the component treat it as a decimal point.
I'm using version 1.20.3 but you can see this behavior on 1.21 as well
https://codesandbox.io/s/using-vue-currency-input-with-mdbvue-qo10f?file=/src/components/MdbCurrencyInput.vue

**Comment by dm4t2** [comment]
This is actually a feature introduced in [Release 1.20.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.20.0).
See also: #71 and #126.

**Comment by Tovli** [comment]
Thanks for the references. In that case, I need to find a solution to avoid using multiple symbols as the decimal point instead of relying on the client locale (or my choice of locale)
