### ISSUE TITLE
Feature request: Allow spacing in front of the prefix

### ISSUE THREAD

**Issue by orenlande** [dm4t2/vue-currency-input#155]
Hello, Great plugin.
I'm working on an application that acts inside Shopify eco-system, and as part of the design requirements, I need to comply with Shopify's guidelines - your plugin almost there, except a very small thing, I need to add a space between the prefix and the actual number.

If possible, I would add it in options as some kind of "prefixSpace" which gets values such as px, em or even percentages.

![image](https://user-images.githubusercontent.com/20873769/91659931-91054300-eadb-11ea-8e69-b1ae6ff31ec9.png)

Although I'd be happy to create it as PR, I find it a bit difficult to navigate around the source code.
Would much appreciate it if the feature can make it into the next release!

**Comment by dm4t2** [comment]
Hi, this feature is already there. 
You can use a custom currency prefix for your requirement: `<currency-input :currency="{prefix: '$ '}"`.
See also: https://dm4t2.github.io/vue-currency-input/config
