### ISSUE TITLE
Error when using provider vee-validate with Vue currency input

### ISSUE THREAD

**Issue by joaovitorp** [dm4t2/vue-currency-input#156]
Error:
`Uncaught TypeError: listeners[event].fns is not a function
    at emit (vue-currency-input.esm.js?d413:437)
    at Object.onInput (vue-currency-input.esm.js?d413:442)
    at NumberInput.format (vue-currency-input.esm.js?d413:369)
    at NumberInput.applyFixedFractionFormat (vue-currency-input.esm.js?d413:300)
    at HTMLInputElement.eval (vue-currency-input.esm.js?d413:413)`
Code:
`<ValidationProvider rules="required" v-slot="{ errors }">
                  <input
                  id="price"
                  v-currency
                  name="price"
                  type="text"
                  v-model="price"
                  label="Price:"
                  />
                <span v-if="errors.length" class="bg-red-100 block text-red-600 mb-5 ">{{ errors[0] }}</span>
                </ValidationProvider>`

the error happens only within <ValidationProvider></ValidationProvider>

**Comment by kevinmelo** [comment]
This bug it's happen with quasar q-input too, using the directive

`vue.runtime.esm.js?5593:1888 TypeError: listeners[event].fns is not a function`

**Comment by PabloRN** [comment]
Same here any update for this issue? Thx

**Comment by joaovitorp** [comment]
> Same here any update for this issue? Thx

vue-currency-input@1.20 working

**Comment by PabloRN** [comment]
> > Same here any update for this issue? Thx
> 
> vue-currency-input@1.20 working

I'm using 1.22.1 should I go back to 1.20?

**Comment by dm4t2** [comment]
Thanks for reporting. I will look at it.

**Comment by jahhernandez** [comment]
I can attest that after testing all versions the 1.21.0 is working correctly. I will use it until a fix for 1.22 can be released. Thanks for the good work.

**Comment by dm4t2** [comment]
VeeValidate should work again with [Release 1.22.2](https://github.com/dm4t2/vue-currency-input/releases/tag/1.22.2) 🎉

**Comment by PabloRN** [comment]
> VeeValidate should work again with [Release 1.22.2](https://github.com/dm4t2/vue-currency-input/releases/tag/1.22.2) 🎉

Thx!!! Nice work!
