### ISSUE TITLE
precision is not honored right

### ISSUE THREAD

**Issue by Tovli** [dm4t2/vue-currency-input#157]
Hi,
I have a bulma `<b-input>` component with this directive:
v-currency="{currency: null, locale: locale, precision:2, distractionFree: false, allowNegative: false}"

When the user enters more than 2 decimal points the display show 2 decimal points but the value have 3 decimal points

tested on version 1.22.2

the b-input:
 <b-input
            v-model="container.someModel"
            @keydown.up.prevent.native
            @keydown.down.prevent.native
            v-currency="{currency: null, locale: locale, precision:2, distractionFree: false, allowNegative: false}"
          />

When other component update the container object then the display is also show the 3 numbers after the decimal point

It seems that the keydown events are causing this issue but it wasn't like that in version 1.20.3

see codesandbox example https://codesandbox.io/s/vue-currency-input-with-buefy-negative-and-decimal-point-issue-m334s

**Comment by dm4t2** [comment]
Hi, thanks for reporting. I will look at it.

**Comment by dm4t2** [comment]
Should be fixed in [1.22.3](https://github.com/dm4t2/vue-currency-input/releases/tag/1.22.3).

https://codesandbox.io/s/vue-currency-input-with-buefy-negative-and-decimal-point-issue-forked-mtps3?file=/src/components/BCurrencyInput.vue

**Comment by Tovli** [comment]
Thanks
When I'm manually enter the page all works well, but the cypress integration test is failing with succeeding in writing negative values and allowing more precision the I declared.
I'll stick with 1.20.3 until I can better understand what is wrong there
