### ISSUE TITLE
allowNegative allowing '-' when using key events

### ISSUE THREAD

**Issue by Tovli** [dm4t2/vue-currency-input#158]
Hi,
I have a bulma `<b-input>` component with this directive:
v-currency="{currency: null, locale: locale, precision:2, distractionFree: false, allowNegative: false}"

When the user enters '-' the display shows nothing but the value have '-'

tested on version 1.22.2

the b-input:
 <b-input
            v-model="container.someModel"
            @keydown.up.prevent.native
            @keydown.down.prevent.native
            v-currency="{currency: null, locale: locale, precision:2, distractionFree: false, allowNegative: false}"
          />

see codesandbox example https://codesandbox.io/s/vue-currency-input-with-buefy-negative-and-decimal-point-issue-m334s

**Comment by dm4t2** [comment]
Error cause is the same as for #157.
