### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by dinodevmtl** [dm4t2/vue-currency-input#159]
"Failed to mount component: template or render function not defined."

always getting this error.
here is my code from main.js

`import VueCurrencyInput from 'vue-currency-input'

const pluginOptions = {
    /* see config reference */
    globalOptions: { currency: 'USD' }
}
Vue.use(VueCurrencyInput, pluginOptions)`

tried it in vue component
`<currency-input
    v-model="value"
    currency="EUR"
    locale="de"
  />`

same error again n again.

**Comment by dm4t2** [comment]
There seems to be a problem with your setup. I can not reproduce your issue:
https://codesandbox.io/s/vue-currency-input-159-t9xlo?file=/src/App.vue
