### ISSUE TITLE
Decimal length

### ISSUE THREAD

**Issue by ekuzu** [dm4t2/vue-currency-input#16]
Hi
How can i set decimal place length default is 2 , i need to set it 4
Thanks.

**Comment by dm4t2** [comment]
Hi, the number of decimal digits is defined by the used currency and currently not customizable. But I plan to make the configuration more flexible, because sometimes there are situations where you want to deviate from it.

**Comment by jonagoldman** [comment]
I am also interested in this, specially when working with exchange rates and currency conversions.

There are two cases,

1) You want to show the full decimal digits. For example 1 USD = 0.891735 EUR, so in theory the EURO currency has only 2 decimal digits (or sub-units) but in reality for precise calculations all decimals digits need to be stored.

2)You want to store the value with full decimal digits but show the rounded number (defined by currency)
For example in a shopping app. A customer in an airport buys a coffee for 10 USD but wants to pay in EURO, so he needs to pay 8.91933 EURO, but the number shown in the input is rounded to 8.92 EUR. But internally it's important to store all the decimal digits as it is a currency conversion.

**Comment by jujogi** [comment]
For example with my COP currency not need display decimals. It would enough show just 1,000 COP and not 1,000.00 COP.

Thanks it's an amazing tool. 

Regards,

**Comment by dm4t2** [comment]
@jonagoldman 
The use cases you described don't work since the stored number is parsed based on the current input value and therefore always has the number of visible decimal digits.

**Comment by dm4t2** [comment]
Support for custom decimal length is now available in release 1.8.0:
https://dm4t2.github.io/vue-currency-input/examples/#decimal-length

**Comment by zefexdeveloper** [comment]
I don't know if this apply in my case but I'm using a payment gateway that requires the currency to be formatted as `90000` meaning `900.00` but when I put `90000` as the value for the input it shows me `90.000,00`

**Comment by dm4t2** [comment]
You probably want to use `valueAsInteger`?
https://dm4t2.github.io/vue-currency-input/examples/#value-as-integer

**Comment by zefexdeveloper** [comment]
@dm4t2 Oh gosh, I didn't notice that it would return exactly the way I need. You rock, thank you.
