### ISSUE TITLE
API for number to currency string formatter?

### ISSUE THREAD

**Issue by bcronje** [dm4t2/vue-currency-input#163]
Is there an API exported to format a number to a currency string? I know about parse and get/setValue, but I'm looking for something that I can use in a filter to display a number as a currency using the same format as this component.

Is the main formatting handled in `NumberFormat.format()` ? Is there a way that you can export this functionality as part of the API? something like `format(number, options)` ?

**Comment by dm4t2** [comment]
Vue Currency Input is about inputting currency formatted numbers, not printing. See also #144.
