### ISSUE TITLE
Lazy value binding with Vuetify does not show the initial value is passed through v-model

### ISSUE THREAD

**Issue by bcronje** [dm4t2/vue-currency-input#167]
The lazy model binding with the latest versions of vue/vuetify/vue-currency-input does not set the initial v-model value on the input on initial load. You first have to blur the input before the value is shown in the input.

Here is an [example](https://codesandbox.io/s/using-vue-currency-input-with-vuetify-forked-ybh7d?file=/src/components/VCurrencyField.vue). Once loaded you'll see the text field is empty, even though the number value is present. Once you click inside the text field and click outside it, the value is shown.

Is my code correct, or should I be doing something different to get lazy model binding to work?

```
<template>
  <VTextField ref="input" v-currency="options" @change="onChange"/>
</template>

<script>
export default {
  name: "VCurrencyField",
  props: {
    value: {
      type: Number,
      default: null
    },
    options: {
      type: Object,
      default: () => {}
    }
  },
  watch: {
    value(value) {
      this.setValue(value);
    }
  },
  mounted() {
    this.setValue(this.value);
  },
  methods: {
    setValue(value) {
      this.$ci.setValue(this.$refs.input, value);
    },
    onChange(value) {
      this.$emit("input", this.$ci.getValue(this.$refs.input));
    }
  }
};
</script>
```

Looking at your old [example](https://codesandbox.io/s/vue-currency-input-122-rcjd9?file=/src/components/VCurrencyField.vue) this issue does not seem to be present using older versions.

**Comment by dm4t2** [comment]
This works:
https://codesandbox.io/s/using-vue-currency-input-with-vuetify-forked-h4fty?file=/src/components/VCurrencyField.vue

**Comment by bcronje** [comment]
Perfect, thank you.
