### ISSUE TITLE
Glitch when using DistractionFree...

### ISSUE THREAD

**Issue by roes129** [dm4t2/vue-currency-input#169]
This control is awesome and just what I was looking for.  However, I found a glitch when using the directive with the option  distractionFree: {hideCurrencySymbol: false}.  Using your codesandbox to illustrate the issue, change to the following:

```
<input ref="input" v-currency="{currency: 'USD', locale: 'en', distractionFree: {
        hideNegligibleDecimalDigits: false,
        hideCurrencySymbol: false,
        hideGroupingSymbol: false
      }
    }"

    v-model="value2"></currency-input>
    <p><button @click="value2 = 55">Button</button></p>
```

Using the modified "codesandbox' example, click the button, tab into the directive control, do not edit, then tab off.  You will notice the value resets to the "previously edited value" on lost focus.  It would appear that there is an internal value that is being retained and not reset when the v-model value is reset outside the control.

Note that this only happens when "hideCurrencySymbol: false".  

Other things to note:  
It doesn't matter if the 55 is a number or a string;
It can be any combination of the distractionFree options, so long as hideCurrencySymbol is set to false, it occurs.

**Comment by dm4t2** [comment]
Hi, you have to use [setValue](https://dm4t2.github.io/vue-currency-input/api/#setvalue) if you want to set the value programmatically:

https://codesandbox.io/s/vue-currency-input-169-do3c8?file=/src/App.vue
