### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by shadowam** [dm4t2/vue-currency-input#17]
Hello!

Love your plugin, but I feel like a RTL option would make it perfect. Let me give you an example:

- Input is empty
- User types 1: Input now shows 0.01
- User types 2: Input now shows 0.12
- and so on...

Do you think it's possible to make this enhancement?

**Comment by dm4t2** [comment]
Hi, thanks for your suggestion. I also think that would be a nice feature. I will have a look on it.

**Comment by StereoSoda** [comment]
Hi, in Google Chrome doesn't work anymore :C

**Comment by dm4t2** [comment]
@StereoSoda: What does not work? This feature is not implemented yet...

**Comment by StereoSoda** [comment]
> @StereoSoda: What does not work? This feature is not implemented yet...

For google chrome is not implemented yet?

**Comment by amstrad** [comment]
> @StereoSoda: What does not work? This feature is not implemented yet...

Maybe he means #24  ?

**Comment by dm4t2** [comment]
It took some time, but I'm happy to announce that [Auto decimal mode](https://dm4t2.github.io/vue-currency-input/examples/#auto-decimal-mode) is now available in release 1.9.0 🎉

**Comment by shadowam** [comment]
Thank you very much @dm4t2! I'm sad I'm not good enough to help you in the project, but I'm really happy you implemented the idea!
