### ISSUE TITLE
Feature Request: Optional groupingSymbol

### ISSUE THREAD

**Issue by Imad-Abdulkarim-offmade** [dm4t2/vue-currency-input#170]
Thanks for the great component. Would it be possible to support not showing the grouping symbol at all regardless of the locale?
```
DE:
current: 1.299,95
request: 1299,95

EN
current: 1,299.95
request: 1299.95
```

i'm currently using this component as both a currency input and a normal number input that supports formatted floats

**Comment by dm4t2** [comment]
Hi, thanks for your suggestion. I think it's worth to make this configurable.

**Comment by dm4t2** [comment]
A new boolean option `useGrouping` was added in [Release 2.0.0-beta.1](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-beta.1) 🎉

You can check it out in the playground: https://vue-currency-input-next.netlify.app/playground/

**Comment by Sovai** [comment]
can i change the grouping symbol? I want to replace , with space like 1,000 => 1 000
