### ISSUE TITLE
Add option to force vue-currenc-input to accept integer only

### ISSUE THREAD

**Issue by asdf913** [dm4t2/vue-currency-input#174]
It is suggested that the vue-currency-input may be using [Number.isInteger()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger) to check if the input is a valid integer

`Number.isInteger(parseFloat(1234))` returns **true**
`Number.isInteger(parseFloat(1234.00))` returns **true**
`Number.isInteger(parseFloat(1234.01))` returns **false**

**Comment by dm4t2** [comment]
Hi, you can set `precision` to 0 to force integer values.
