### ISSUE TITLE
@change="NameOfYourEvent = $event" is not working on Microsoft Edge Legacy 44.17763.1.0

### ISSUE THREAD

**Issue by TrietPham96** [dm4t2/vue-currency-input#176]
Hello Matthias Stiller @dm4t2 , it seems event **@change** such as `<currency-input>@change="NameOfYourEvent = $event"</currency-input>` is not working on Microsoft Edge Legacy 44.17763.1.0
I tried set debug and checked result is: method `NameOfYourEvent` has not been hit anytime.

**Comment by dm4t2** [comment]
Hi, please refer to the docs for proper usage:
 
https://dm4t2.github.io/vue-currency-input/guide/#lazy-value-binding
https://vuejs.org/v2/guide/events.html#Methods-in-Inline-Handlers
