### ISSUE TITLE
Add prefix/suffix for vue 3 support

### ISSUE THREAD

**Issue by JakuninOleg** [dm4t2/vue-currency-input#177]
Would be really cool. Waiting for this feature. Also documentaion is not very clear how we should pass currency props

**Comment by dm4t2** [comment]
With the upcoming major release, Vue Currency Input will no longer support custom prefixes or suffixes. Only currency ISO codes will be supported.

Why? It will be aligned back to its original purpose: the input of currency formatted numbers based on the [ECMAScript Internationalization API](https://ecma-international.org/ecma-402/#numberformat-objects). Currently, it just feels wrong to allow the component to behave like a pure number input by either omitting the display of the currency symbol (`currency="null"`) or inserting custom ones (`currency="{suffix: ' %'}"`).

But nevertheless, I just started to work on a more generic number input component regarding these issues: [vue-intl-number-input](https://github.com/dm4t2/vue-intl-number-input).

**Comment by Luigidefra** [comment]
in my opinion this is a great lack of flexibility
