### ISSUE TITLE
Not working on ipad3 IOS 9.3.5

### ISSUE THREAD

**Issue by elitetester** [dm4t2/vue-currency-input#178]
Unfortunately this does not work on latest IOS version for the ipad3 with either Safari or Chrome.
In my own implementation I was using it as follows:

```
<input
@focus="getfocus('example')"
tabindex="3"
ref="entry"
v-model="example"
autocomplete="off"
v-on:keyup.enter="$refs.target.focus()"
@keyup="entrykeypress()"
v-currency="{ currency: null, locale: 'en' }"/>
```

For newer IOS/Android/WIN it works perfectly.

When using the ipad3 on your linked playground: https://dm4t2.github.io/vue-currency-input/playground/
the input box that should show a default value of '1234' is blank/empty.

**Comment by dm4t2** [comment]
I'm afraid, there's nothing I can really do without console error logs. I guess it's very likely caused by an unsupported browser feature that needs to be pollyfilled.
