### ISSUE TITLE
Undo does not work after entering a comma or dot

### ISSUE THREAD

**Issue by leosdad** [dm4t2/vue-currency-input#179]
The problem is very much described at the title. The undo stack inside the field is reset whenever a non-numeric character is input, and that includes '.' and ','. This can be confirmed in the [playground](https://dm4t2.github.io/vue-currency-input/playground/).

**Comment by dm4t2** [comment]
Hi, it should work unless you use a decimal separator that is different from the configured locale. Unfortunately, the undo stack will always reset on the first invalid character. This can not be changed.
