### ISSUE TITLE
parse with some locales (e.g. JPY) in node does not work

### ISSUE THREAD

**Issue by jmayergit** [dm4t2/vue-currency-input#180]
`¥12` locale -> `en-US` ✅
`￥12` locale -> `ja-JP` ❌

You can see how changing the locale affects the string considerably. In a node environment `parse` will return `null`

**Comment by dm4t2** [comment]
If you are trying to parse `en-US` formatted numbers with locale `ja-JP`, it will not work. The locale for both formatting and parsing must match.
