### ISSUE TITLE
Get NULL from input with large numbers when using the INR currency & en-IN locale (v2.0.0-beta.0)

### ISSUE THREAD

**Issue by mattelen** [dm4t2/vue-currency-input#181]
This error can be replicated on https://vue-currency-input-next.netlify.app/playground/

Value typed/pasted in: 200000
Locale: en-IN
Currency: INR
Browser: Chromium 87.0.4280.66 on Ubuntu 20.04.1 LTS 

When you deselect the input, the value received is just null, rather than the value. I would have thought I'd get the value, rather than null?

Let me know if I am missing something with this locale or currency. Thanks in advance for checking this out, and the work that you do on this component.

**Comment by dm4t2** [comment]
Thanks for reporting. I will dig into it.

**Comment by dm4t2** [comment]
I fixed this in [Release 1.22.4](https://github.com/dm4t2/vue-currency-input/releases/tag/1.22.4) 🎉 

The `next` version (2.0.x) will be updated soon.

**Comment by dm4t2** [comment]
Now also fixed in [Release 2.0.0-beta.1](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-beta.1) 🎉
