### ISSUE TITLE
Feature Request: support letters as scaling values

### ISSUE THREAD

**Issue by simonmarshall** [dm4t2/vue-currency-input#185]
Hi, thanks for providing this component! Note: locale=en for this request...

It would be nice if the user could type, eg, "1.23m", and the component treat the "m" as "millions" and set the value to "1230000".

Maybe the difficulty in agreeing the meaning of letters, even locale-specific meanings in the context of finance, means that the component shouldn't supply default scaling values.  However, at least component support to use supplied mappings would be enough.  A coder might specify:

scaling-values: {
  'k': 1e3, 
  'm': 1e6,
  'b': 1e9,
}

So that "k", "m", and "b" would have the corresponding scaling applied on input.

**Comment by dm4t2** [comment]
Hi, thanks for your suggestion, but it makes only little sense for me since it's too locale-specific.

**Comment by simonmarshall** [comment]
hi @dm4t2, i'm sure other locales have a convention of a letter being used to represent 1000s and 1000000s in finance, much the same way as in computing capacity.  that's why i suggested adding support for it, but leaving it up to component users to specify what numerical values to assign specific letters.
