### ISSUE TITLE
If no decimal symbol is typed, do not show the decimal point

### ISSUE THREAD

**Issue by Sun3** [dm4t2/vue-currency-input#187]
I would like to request a feature if the user does not type the decimal point, then allow the control not to show the decimal point.

User enters ```250,000``` show it as ```250,000``` not ```250,000.00```

Thank you.

**Comment by dm4t2** [comment]
See #186.

**Comment by Sun3** [comment]
Thank you. By the way how close are we to getting vue-currency-input to work with Vue 3? I tried the beta version but I was getting errors and the control was not recognized.

**Comment by dm4t2** [comment]
I just noticed that release 2.0.0-beta.1 does not work with Vue 3. Thanks for reporting 👍

Should be fixed in release [2.0.0-beta.2](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-beta.2). Please use issue #166 for any feedback regarding Vue 3.
