### ISSUE TITLE
setValue(input, null)

### ISSUE THREAD

**Issue by ilushinvanya** [dm4t2/vue-currency-input#191]
Hi.
Your documentation says that you can pass a null value to setValue. But the types do not contain null.
I really want to see null in the types for value.
Documentation:
https://dm4t2.github.io/vue-currency-input/api/#setvalue
Where to write null)
https://github.com/dm4t2/vue-currency-input/blob/master/src/index.d.ts#L52
https://github.com/dm4t2/vue-currency-input/blob/master/src/index.d.ts#L63

**Comment by dm4t2** [comment]
Thanks for reporting 👍

**Comment by dm4t2** [comment]
Fixed in [1.22.5](https://github.com/dm4t2/vue-currency-input/releases/tag/1.22.5) 🎉
