### ISSUE TITLE
Value always null after lose focus with locale de-AT

### ISSUE THREAD

**Issue by cluidold** [dm4t2/vue-currency-input#192]
Hi

If i use locale 'de-AT' with default settings all values greater than 1000 do not work as expected. If you enter the value, everything is ok, but after click outside the textbox/lose focus the value changes to null.

The problem seems to be new since 1.22.4. When i change back to 1.22.3 the input work as expected.

You can test/reproduce it at: [https://codesandbox.io/s/dsj4u](https://codesandbox.io/s/dsj4u)

Steps to reproduce:

1. Enter number >1000
2. Change dependency to 1.22.3
3. Enter number >1000

**Comment by dm4t2** [comment]
Thanks for reporting 👍

**Comment by dm4t2** [comment]
Fixed in [1.22.6](https://github.com/dm4t2/vue-currency-input/releases/tag/1.22.6) 🎉

**Comment by dm4t2** [comment]
Now also fixed in [2.0.0-rc.1](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-rc.1).
