### ISSUE TITLE
Automatically sign input value based on valueRange

### ISSUE THREAD

**Issue by glenncoppens** [dm4t2/vue-currency-input#193]
Hi,

I'm currently in a situation where multiple v-currency-fields should only allow negative values.
I can use the valueRange option for that, which is a nice technical solution for "implicit validation".

But from an end-user point of view, it would be nice if the value has its sign automatically "added", based on the valueRange option (eg: multiply `Math.abs(value)` by `-1` when `max < 0` and `min >= Number.MIN_SAFE_INTEGER`). 

Of course, to allow for switching this feature on and off, there may be a need for an extra `autoSign` option?

Or would there be another approach to this?

Thanks, Glenn

**Comment by dm4t2** [comment]
Hi, thanks for your suggestion. I think it's a nice idea which is also capable to replace the existing `allowNegative` option for forcing positive values. I will have a look at it 👍

**Comment by glenncoppens** [comment]
Thanks for looking into this!

I'm just thinking that, when eg the valueRange is `min: -100, max: 100`, at a certain point you will have to decide which sign to use as the preferred sign, right? Maybe that could be an extra config option, `preferredSign`? It may allow for more flexibility to specific use cases devs are confronted with sometimes?

**Comment by dm4t2** [comment]
My proposal for the new boolean `autoSign` option looks like this:

* It's active (`true`) by default
* When `valueRange` does not allow negative values (`{min: 0}`) and `autoSign` is active, it will prevent the user to input a minus sign (current behavior of the `allowNegative` option)
* When `valueRange` does not allow positive values (`{max: 0}`) and `autoSign` is active, it will automatically insert the minus sign on input

Does this also meet your requirements?

**Comment by dm4t2** [comment]
The new `auotSign` option is now available in [2.0.0-rc.1](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-rc.1) 🎉 

You can test it on the [playground](https://vue-currency-input-next.netlify.app/playground/).

**Comment by glenncoppens** [comment]
@dm4t2 

Nice one!
