### ISSUE TITLE
Could you please kindly provide a elementui demo

### ISSUE THREAD

**Issue by ysinsane** [dm4t2/vue-currency-input#195]
Here is mime: 
```
<template>
  <el-input ref="inputRef" v-model="formattedValue" @input="(val) => $emit('update:modelValue', val)" />
</template>

<script>
import useCurrencyInput from 'vue-currency-input'

export default {
  name: 'CurrencyInput',
  props: {
    modelValue: {
      type: Number,
      default: 0
    },
    options: {
      type: Object,
      default: () => ({ currency: 'CNY' })
    }
  },
  emits: ['update:modelValue'],
  setup(props) {
    const { formattedValue, inputRef } = useCurrencyInput(props.options)
    return { inputRef, formattedValue }
  }
}
</script>
```
I use it like this: 
<el-form-item label="Price" prop="price">
          <currency-input v-model="temp.price" />
        </el-form-item>
I found temp.price became a string as the input lost focus, something like "$123,456". What I need is a pure number.

**Comment by ysinsane** [comment]
Got a solution:

```
<template>
  <el-input ref="inputRef" v-model="formattedValue" @input="updateValue" />
</template>

<script>
import useCurrencyInput from 'vue-currency-input'

export default {
  name: 'CurrencyInput',
  props: {
    modelValue: {
      type: Number,
      default: 0
    },
    options: {
      type: Object,
      default: () => ({ currency: 'CNY' })
    }
  },
  emits: ['update:modelValue'],
  setup(props, context) {
    const { formattedValue, inputRef } = useCurrencyInput(props.options)
    const updateValue = (val) => {
      context.emit('update:modelValue', val.replace(/[^0-9]/ig, ''))
    }
    return { inputRef, formattedValue, updateValue }
  }
}
</script>

```

**Comment by dm4t2** [comment]
Check out my simplified solution: 
https://codesandbox.io/s/using-vue-currency-input-with-element-plus-8b6rc?file=/src/components/ElCurrencyInput.vue

I will also add this example to the docs.

**Comment by ysinsane** [comment]
> Check out my simplified solution:
> https://codesandbox.io/s/using-vue-currency-input-with-element-plus-8b6rc?file=/src/components/ElCurrencyInput.vue
> 
> I will also add this example to the docs.

Thanks man! This works for me.
Just got a little warning:
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.

So I add this: emits: ["update:modelValue"], then it stopped working. 
Here is my codesanbox
https://codesandbox.io/s/using-vue-currency-input-with-element-plus-forked-wcu9k?file=/src/components/ElCurrencyInput.vue

**Comment by ysinsane** [comment]
Thanks for your reply, it works perfect for me!

**Comment by ysinsane** [comment]
Dear dm4t2, 

Problems about using this with elementui, I found annother one. The input lost it's reactivity when use v-model=obj.someAttr

Here is the sandbox:
https://codesandbox.io/s/using-vue-currency-input-with-element-plus-forked-ipqd7
