### ISSUE TITLE
v-model doesn't change when you input just 1 number and delete it right away

### ISSUE THREAD

**Issue by estevE11** [dm4t2/vue-currency-input#197]
I have inside a modal and then save. This only happens when the modal just opened and the input is empty. If I input just a number, lets say 4, if I delete that number when check v-model it has number 4.

This only happens in this specific order. If it has value before or you input 2 numbers it works fine.

**Comment by dm4t2** [comment]
It seems the issue is related to your app. Please provide a [CodeSandbox](https://codesandbox.io/s/vue-currency-input-template-zorpj) for reproducing.
