### ISSUE TITLE
Add options output in playground

### ISSUE THREAD

**Issue by lcherone** [dm4t2/vue-currency-input#204]
Great lib/component, can I make a suggestion

In the playground in the docs page: https://dm4t2.github.io/vue-currency-input/playground/, 

To help onboard, it kind of needs a section below that outputs the selected/toggled options, I spent 10 mins looking through docs and referencing all the options against the human-readable form labels when could have simply copy/pasted the options onto the instance

I know its lazy ;p but fundamentally a line in [Playground.vue](https://github.com/dm4t2/vue-currency-input/blob/master/demo/Playground.vue) like the following would have saved even looking at the docs

`<span style="white-space:pre">v-currency="{{ JSON.stringify(options, null, 2).replace(/"(.*)":/g, '$1:') }}"</span>`

Output:

```
v-currency="{
  locale: "en",
  currency: "GBP",
  valueAsInteger: false,
  distractionFree: true,
  precision: 2,
  autoDecimalMode: true,
  valueRange: {
    min: 0,
    max: 10000000
  },
  allowNegative: false
}"
```

alt make a diff computed value that looks at libs defaults, if it's not changed remove it from the output.

again, nice work on the lib :)

**Comment by dm4t2** [comment]
Thanks for your feedback. Sounds like a good idea.

**Comment by dm4t2** [comment]
There's now a button for exporting the options in the playground: https://vue-currency-input-next.netlify.app/playground/
