### ISSUE TITLE
type="text" attribute missing in Guide or in component implementation

### ISSUE THREAD

**Issue by JPustkuchen** [dm4t2/vue-currency-input#205]
# Problem:
When using a currency-input component, the resulting HTML misses the `type="text` "attribute. In the demo the input field correctly contains it.

Example:
`<currency-input currency="EUR" size="10" allow-negative="false" v-model="xyz" size="5" />`
results in
`<input inputmode="decimal" size="10" [...] data-cip-id="cIPJQ342845640">`
That may lead to styling and validator issues. 

The documentation also doesn't point out that the developer should add the type="text" attribute manually , which is the current workaround:
`<currency-input type="text" currency="EUR" size="10" allow-negative="false" v-model="xyz" size="5" />`
results in
`<input inputmode="decimal" type="text" size="10" [...] data-cip-id="cIPJQ342845640">`
which is correct.

I guess type="text" should always be added in the component.

I guess for the [directive](https://dm4t2.github.io/vue-currency-input/guide/#directive), one might discuss it's the developer task to add the type attribute, but perhaps it would even make sense there? The question is what happens if a developer sets an unexpected type like `type="number"`?

**Comment by dm4t2** [comment]
You're right! Currently, an input with `type="text` is implicitly assumed, but this also should be clarified in the docs.

**Comment by JPustkuchen** [comment]
Thank you very much @dm4t2  :) A quick fix might be to align it in the directive example here: https://dm4t2.github.io/vue-currency-input/guide/#directive That was at least what I looked at first.

**Comment by dm4t2** [comment]
I updated the v2 docs: https://vue-currency-input-next.netlify.app/guide/#usage
