### ISSUE TITLE
How to get formatted value?

### ISSUE THREAD

**Issue by phlegx** [dm4t2/vue-currency-input#206]
Hi!

I want to get the formatted value from v-model. How can I do that? I miss an API function like `getFormattedValue()`. Or is there another way to get the formatted value?

**Comment by Ambratolm** [comment]
> In comparison to the <currency-input> component the v-currency directive always emits the formatted string instead of the number value when used with v-model. 

I guess you have just to use the directive.

**Comment by phlegx** [comment]
I use `<currency-input v-model="value" />`. Can you please show me how?

**Comment by Ambratolm** [comment]
```
<input v-model="value" v-currency />
```

**Comment by phlegx** [comment]
What I need is both. `v-model` should contain the number value to submit to the server and a formatted value to show elsewhere in the UI.

**Comment by Ambratolm** [comment]
You can convert the formatted value you get from `v-model` to a raw number value using the API functions like `parse` function:
> Parse Function Parses a currency formatted string emitted by the v-currency directive to a number. This method is also exposed as Vue instance method $ci.parse when installed as Vue plugin.

Example:
`const rawValue = VueCurrencyInput.parse(formattedValue, options);`

> Options are The configured options of the respective v-currency directive. When using $ci.parse this argument is optional and defaults to the globalOptions of the plugin options.

So, in options parameter make sure to put the same options object you defined on the input that the formattedValue is coming from.

For example you have in template:
`<input v-model="myVal" v-currency="myValOpts" />`

And in your script data section:
```
data() {
    myVal: 0,
    myValOpts: {
              currency: { prefix: "$ " },
              precision: 2,
              allowNegative: false
              // ....etc
    }
}
```
Then, you get the raw value this way:
`const myRawVal= VueCurrencyInput.parse(myVal, myValOpts);`

I hope it helps :)

**Comment by phlegx** [comment]
Thank you so much!
