### ISSUE TITLE
Allow inserting thousand separators

### ISSUE THREAD

**Issue by p7ac** [dm4t2/vue-currency-input#207]
If I set locale to be en-US and attempt to type in `123,000` i.e. 123 thousand units, I see this

![image](https://user-images.githubusercontent.com/65259641/115165835-bd3ff500-a0a7-11eb-88c3-9205373ce9f8.png)

Even though a comma is not the decimal separator in en-US locale, it is treated as a decimal point insertion.

It would be great to handle (ignore) the insertion of 1 or more thousand separators as this is a little bit confusing.

With Locale == de-DE the same confusing behaviour happens, an inserted `.` (period symbol) triggers the decimal separator displaying as a comma.

Confirmed using the live playground.

**Comment by dm4t2** [comment]
This behavior is intended (see also #126). Grouping (thousands) separators are not meant to be entered manually.

**Comment by p7ac** [comment]
Sorry I somehow missed the 4 other issues about this.

I find this behaviour a bit odd given the original problems should be solved if the user's locale and the components locale are the same ? Maybe I'm not understanding their issues properly.

I would make use of an option where grouping separators are ignored just as a regular numeric input field.

Would you be interested in a PR allowing that?
