### ISSUE TITLE
[Feature Request] Custom currency display

### ISSUE THREAD

**Issue by MrSuttonmann** [dm4t2/vue-currency-input#209]
Hi,

We are using this field in our application to display currencies but also non-currency numerics, for consistency.

We were using `1.22.6` but were unable to turn off groupings when the field is not focused, but noticed #170 was raised a few months ago to enable that, however I've updated to `2.0.0-rc.4` and now I'm finding it impossible to turn off the currency symbol when not focused as the currency option is now a required property.

It would be really really helpful if the `distractionFree` settings could also (optionally) be applied at all times, not just when the field is in focus. I need to be able to turn off the groupings in some fields, and the currency symbol in others independently of the field's focus state.

**Comment by dm4t2** [comment]
Hi, thanks for your feedback. I have thought a little about it (especially regarding https://github.com/dm4t2/vue-currency-input/issues/177#issuecomment-736115070).

I think it makes sense to introduce a new option `hideCurrencySymbol` for this, but please note that the `currency` option will still be required for proper formatting.

**Comment by MrSuttonmann** [comment]
That would be excellent, thank you :)

**Comment by dexcell** [comment]
@dm4t2 Thank you for the option to hide currency symbol.

But please do not force currency option to be in proper symbol string like USD. 
at least please just set configureable fallback to use USD formatting, if we choose to put our own currency like GOLD. (in-game currency or other purposes).

**Comment by dm4t2** [comment]
@dexcell Your suggestion sounds interesting. I will look into it 👍

**Comment by dm4t2** [comment]
The new option `currencyDisplay` is now available in [2.0.0-rc.5](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-rc.5) 🎉

See also in the docs:
https://vue-currency-input-next.netlify.app/config.html#currencydisplay
https://vue-currency-input-next.netlify.app/playground.html

**Comment by sinau123** [comment]
so how can I use custom currency or symbol?

for example when I use `currency: "IDR"` and `currencyDisplay: "narrowSymbol"` option, the input will show `Rp`, 
then how to display symbol with extra dot here `Rp.` ?

**Comment by dm4t2** [comment]
The formatting is controlled by [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat) and depends on your configured `locale` and `currencyDisplay`. There's no other customization.

![image](https://user-images.githubusercontent.com/11592259/134802157-5ef53b87-4535-491a-b667-307751c1b028.png)

**Comment by nekooee** [comment]
I also need to display custom currency. For example, the unit of IRR is Rial. But I want to eat "Toman". like this:
22,000 tomans
or
22,000 تومان

**Comment by nekooee** [comment]
Still no solution?

**Comment by dm4t2** [comment]
This will not be supported (see my previous reply).

**Comment by mreduar** [comment]
I have been looking for hours for an alternative to Intl.NumberFormat to see if this could be possible, but it is very difficult to find information on this.
Stripe uses a very particular currency format and I would love to imitate it depending on the locale makes it different, they include the symbol of all countries and surely use something custom.
![image](https://github.com/dm4t2/vue-currency-input/assets/22550119/95921b7a-c9ef-43ab-9d6d-fc6da350a95c)
