### ISSUE TITLE
Precision prop doesn't work in <currency-input>

### ISSUE THREAD

**Issue by 684efs3** [dm4t2/vue-currency-input#210]
I have put the precision in as:

```
<currency-input
precision="0"
/>
```

but this does not work. I get the error:

`Invalid prop: type check failed for prop "precision". Expected Number, Object, got String with value "0".`

However, if I do:

```
<currency-input
precision=0
/>
```

this does not work either. Also, Prettier/Vetur will convert precision=0 to precision="0"

Is it possible for you to change the prop so that it can take in a string?

**Comment by dm4t2** [comment]
https://vuejs.org/v2/guide/components-props.html#Passing-a-Number
