### ISSUE TITLE
bug on samsung mobile keyboard

### ISSUE THREAD

**Issue by nPaul** [dm4t2/vue-currency-input#211]
Bug on mobile samsung keyboard

can't input ',' '.' symbols

on keyboard
symbol ',' blocked
and symbol '.' can't input
allow input only integer value on field

component settings:
currency: 'RUB',
locale: 'ru-RU',
allowNegative: false

**Comment by dm4t2** [comment]
Seems to be related to #190 and should be fixed in the upcoming v2 release.

Please test it here: https://vue-currency-input-next.netlify.app/playground/

Which version do you use?
