### ISSUE TITLE
[Feature Request] `min` and `max` attributes, here's my current solution

### ISSUE THREAD

**Issue by mrspence** [dm4t2/vue-currency-input#212]
Hey there, brilliant component, solves so many issues thank-you! :)

# Feature request: `min` and `max` attributes

Developers would find it useful to be able to set `min` and `max` props for the currency input. This may also make the `allow-negative` prop obsolete.

## Use case

I currently have 3 inputs: `valuation`, `valuation_from`, and `valuation_to`

- `valuation_from` must be **smaller** than `valuation`
- `valuation_to` must be **bigger** than `valuation`
- `valuation` must be **between** `valuation_from` and `valuation_to`

I currently do this using `vue-currency-input` by hooking into the `$ci` variable, like so:

### Current solution

```vue
<div>
    <label for="valuation">Valuation</label>
    <currency-input
        v-model="valuation"
        :allow-negative="false"
        id="valuation"
    />
</div>

<div>
    <div 
        <label for="valuation_from">Ranging From</label>
        <currency-input
            :value="valuation_from"
            ref="valuation_from"
            @input="$event < valuation ? valuation_from = $event : $ci.setValue($refs.valuation_from, valuation - 1)"
            :allow-negative="false"
            id="valuation_from"
        />
    </div>
    <div>
        <label for="valuation_to">Ranging To</label>
        <currency-input
            :value="valuation_to"
            ref="valuation_to"
            @input="$event > valuation ? valuation_to = $event : $ci.setValue($refs.valuation_to, valuation + 1)"
            :allow-negative="false"
            id="valuation_to"
        />
    </div>
</div>
```

This doesn't include a little extra validation I've written, but shows everything relevant to showcase how `min` and `max` attributes would make this less verbose and more understandable for a developer.

### Ideal Solution

```vue
<div>
    <label for="valuation">Valuation</label>
    <currency-input
        v-model="valuation"
        :min="1"
        id="valuation"
    />
</div>

<div>
    <div 
        <label for="valuation_from">Ranging From</label>
        <currency-input
            v-model="valuation_from"
            :max="valuation"
            :min="0"
            id="valuation_from"
        />
    </div>
    <div>
        <label for="valuation_to">Ranging To</label>
        <currency-input
            v-model="valuation_to"
            :min="valuation"
            id="valuation_to"
        />
    </div>
</div>
```

## End note

Is there a better way of doing this? Perhaps I've missed something key that would make this easier without `min` / `max` attributes, feedback is welcome. That said, I know this isn't stackoverflow! 😉 In which case - please discuss the min/max attributes solution.

Thanks again :)

**Comment by dm4t2** [comment]
Hi, doesn't the current `valueRange` option fit your requirements? 

https://vue-currency-input-next.netlify.app/playground/

Note, that the `allowNegative` option will be replaced by the new `autoSign` option in the upcoming v2 release (see #193).

**Comment by mrspence** [comment]
The `valueRange` only works for up to two numbers, at least now? My example demonstrates three inputs reliant upon each other.

![image](https://user-images.githubusercontent.com/30320791/116689933-9ab7b100-a9b0-11eb-90a6-51f9e91cd2cf.png)

**Comment by dm4t2** [comment]
The `min` and `max` values of `valueRange` are both optional, so a strict value range is not enforced.

I adapted your "ideal  solution" in a CodeSandbox:
https://codesandbox.io/s/vue-currency-input-212-qqilz
