### ISSUE TITLE
 lost it's reactivity when use v-model=obj.someAttr

### ISSUE THREAD

**Issue by ysinsane** [dm4t2/vue-currency-input#213]
Dear dm4t2,

Problems about using this with elementui, I found annother one. The input lost it's reactivity when use v-model=obj.someAttr

Here is the sandbox:
https://codesandbox.io/s/using-vue-currency-input-with-element-plus-forked-ipqd7

**Comment by ysinsane** [comment]
I should've read the doc more carefully. Change props from external should use watch...
https://vue-currency-input-next.netlify.app/guide/#external-props-changes

**Comment by csechuan** [comment]
@dm4t2 Plan to reset the input by setting the value. I am using Nuxt, Vue 2. I guess the error i received is vue 2 doesnt have watch api exported?

console:
- "export 'watch' was not found in 'vue'
- [Vue warn]: Error in data(): "TypeError: Object(...) is not a function"
