### ISSUE TITLE
How to get the unmasked value in v2

### ISSUE THREAD

**Issue by chaosKP** [dm4t2/vue-currency-input#222]
I am trying to make this library work with quasar v2 and vee-validate v4.
But unlike the v1 versions documentation I cannot find a way to get the unmasked value.
There is no api section here [https://vue-currency-input-next.netlify.app/guide/](https://vue-currency-input-next.netlify.app/guide/) and the playground has no sandbox where I could look.
The getValue or parse methods are no longer available and inputRef.value.modelValue also returns the masked value.

So what do I need to do?

**Comment by dm4t2** [comment]
Hi, please check out this example: 
https://codesandbox.io/s/using-vue-currency-input-with-quasar-veevalidate-gokw6

The unmasked (number) value is automatically bound to the components `modelValue`.

**Comment by chaosKP** [comment]
We don't have an external value which we can watch or use.
We want the component to emit its new unmasked value on change.
Is there a way to do this?
