### ISSUE TITLE
vue-currency-input v2 broken with vue 3

### ISSUE THREAD

**Issue by harry-sm** [dm4t2/vue-currency-input#223]
Hello,

Thank you for the hard work you have put into this library. 
The issue seems to be that vue-demi is not getting the instance of vue and it throws an error.

Here is a reproduction of the issue.
https://codesandbox.io/s/vue-currency-input-forked-07nq7?file=/src/main.js

Packages used
vue@3.0.11
vue-currency-input@2.0.0-rc.4

**Comment by dm4t2** [comment]
Hi, the plugin installation has been dropped in v2. 
See https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-beta.0

Here is a working example with Vue 3: https://codesandbox.io/s/vue-currency-input-vue-3-example-5l51f

**Comment by harry-sm** [comment]
@dm4t2 works beautifully. Thank you.
