### ISSUE TITLE
CDN with directive

### ISSUE THREAD

**Issue by amchconsult** [dm4t2/vue-currency-input#226]
Hi question,

Does version 2.0.0-rc.4 still works with Vue 2?

I have try this but error "[Vue warn]: Failed to resolve directive: currency"

`<input type="text" v-model="mymoney"  v-currency="{ currency: 'USD', distractionFree: false, useGrouping: true, precision: { min: 0, max: 2 }, }" class="form-control form-control-sm text-end"></currency-input>`

last question: how do I get an unformated value with directive?

thank you

**Comment by dm4t2** [comment]
Hi, Vue Currency Input v2 still works with Vue 2 but it completely relies on the Vue Composition API.
There's no directive anymore: See https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-beta.0
