### ISSUE TITLE
Failed to compile - rc.4 and rc.5

### ISSUE THREAD

**Issue by Sun3** [dm4t2/vue-currency-input#228]
I just ran into an issue that was not happening last night. When I tried to compile this morning I am receiving the following error:

```
Failed to compile.

./node_modules/vue-currency-input/dist/vue-currency-input.esm.js 267:36
Module parse failed: Unexpected token (267:36)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     getMinValue() {
|         let min = this.toFloat(-Number.MAX_SAFE_INTEGER);
>         if (this.options.valueRange?.min !== undefined) {
|             min = Math.max(this.options.valueRange?.min, this.toFloat(-Number.MAX_SAFE_INTEGER));
|         }
```

Any suggestions?
Thank you.

ps: I am using Vue 3.

**Comment by dm4t2** [comment]
The bundle compiles to ES2020 since 2.0.0.rc5. Please make sure, that the dependency is transpiled with Babel.

See https://cli.vuejs.org/config/#transpiledependencies

Example vue.config.js:
```
/**
 * @type {import('@vue/cli-service').ProjectOptions}
 */
module.exports = {
  transpileDependencies: [
    'vue-currency-input'
  ]
}
```

**Comment by Sun3** [comment]
That worked great, thank you so much for the quick reply.  By the way, I am so happy that you added the currencyDisplay option.

**Comment by dm4t2** [comment]
Glad to hear this 🙂 I will also update the docs.

**Comment by usmanibrahim74** [comment]
@dm4t2 I have a webpack cli project. I am getting this error.
I have vue2 and I don't have vue.config.js file.
any solution?

**Comment by dm4t2** [comment]
@usmanibrahim74 Possible solutions are:

- Include [babel-loader](https://webpack.js.org/loaders/babel-loader/) in your Webpack config
- Migrate to Vue CLI
- Use [Vue Currency Input v1.x](https://vue-currency-input-v1.netlify.app/) (if Vue 3 support is not required)

**Comment by dm4t2** [comment]
**Update:** Since [2.0.2](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.2) it is no longer required to transpile the dependency with Babel for Webpack.
