### ISSUE TITLE
Unexpected behaviour with directive applied to multiple inputs

### ISSUE THREAD

**Issue by DamianGlowala** [dm4t2/vue-currency-input#229]
I have noticed a behaviour I cannot explain myself in any logical way. Here is the reproduction link to try it out:

[https://codesandbox.io/s/zen-elbakyan-er6go?file=/src/App.vue](https://codesandbox.io/s/zen-elbakyan-er6go?file=/src/App.vue)

1. Enter (for instance) 1099.99 into the first input field.
2. Enter any other number into the second input field.
3. Watch how the formatting for the first input field has been erased (comma separator disappeared).

**Why is it happening?** Any advice and possible solutions are highly appreciated.

**Comment by dm4t2** [comment]
You can not use multiple  `v-currency` directives in single Vue component instance. Please encapsulate the `v-currency` directive in a custom component avoid this behavior like in the `<CurrencyInput>` reference implementation: https://github.com/dm4t2/vue-currency-input/blob/2506d21ab4c17e6d45b9feaee4b9b73a9ea42133/src/component.js
