### ISSUE TITLE
Float values as Input are broken (in directive)

### ISSUE THREAD

**Issue by th3l0g4n** [dm4t2/vue-currency-input#23]
This is more or less the same issue as #6.

Passing a float value to an input field with v-currency directive formats the display value wrong:
Input: 4500.45
Display on blur: 450.045,00 €

I've seen that you are using Intl.NumberFormat for formatting, which actually seems to work quite well. 
Just using:
`new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(4500.45)`
correctly returns:
`4.500,45 €`

Might there be an issue as the value is beeing formatted twice?
https://github.com/dm4t2/vue-currency-input/blob/master/src/directive.js#L103
and
https://github.com/dm4t2/vue-currency-input/blob/master/src/directive.js#L105

**Comment by dm4t2** [comment]
Hi, thanks for reporting. This also affects the component, not only the directive.
Obviously I missed this case in my unit tests 💥 

I will fix this in release 1.8.2.
