### ISSUE TITLE
3rd party documentation?

### ISSUE THREAD

**Issue by toralux** [dm4t2/vue-currency-input#235]
Do you currently have any 3rd party integration examples like for quasar that should be supported: Vue Currency Input does not provide a ready-to-use component, instead it enables you to create your own based on your favorite input component (for example Vuetify, Quasar or Element).
https://vue-currency-input-next.netlify.app/guide.html#use-the-custom-component

**Comment by dm4t2** [comment]
Yes, here are some Vue 3 examples for Quasar and Element Plus:

https://codesandbox.io/s/using-vue-currency-input-with-quasar-veevalidate-gokw6?file=/src/QCurrencyInput.vue
https://codesandbox.io/s/using-vue-currency-input-with-element-plus-8b6rc?file=/src/components/ElCurrencyInput.vue

Might also be useful to include these in the docs.

**Comment by dm4t2** [comment]
I added an examples page in the docs: https://dm4t2.github.io/vue-currency-input/examples.html
