### ISSUE TITLE
How to programmatically focus input

### ISSUE THREAD

**Issue by TomHuijer** [dm4t2/vue-currency-input#236]
I am trying to programatically focus the input using $refs as follows:

```html
<currency-input v-model="internalValue" ref="input"></currency-input>
```

```js
this.$nextTick(() => {
    this.$refs.input.focus();
})
```

However, this returns `TypeError: _this.$refs.input.focus is not a function`
How should I go about this?

**Comment by dm4t2** [comment]
Your `ref` points to the Vue component instance, which has no `focus` method. 

Use `this.$refs.input.$el.focus()` instead: https://codesandbox.io/s/vue-currency-input-236-jcqt7?file=/src/App.vue:271-299
