### ISSUE TITLE
Bug in in Chrome 76.0 ? (number disappears)

### ISSUE THREAD

**Issue by amstrad** [dm4t2/vue-currency-input#24]
Hi, i would like to use your component, however i find the formatted number gets blank when it´s over 10k in Chrome latest 76.0>
This happends in your Example page, also in my project..
I found in firefox or safari it´s ok... Any ideas?

![bug](https://user-images.githubusercontent.com/772421/63599128-3af4ea00-c5c1-11e9-9fad-8a9d4c25e43b.gif)

**Comment by dm4t2** [comment]
Hi, I can not reproduce this issue in Chrome 76.0.3809.100 (Windows 10).
What browser locale you are using?

**Comment by amstrad** [comment]
Hi, Spanish

Or, according to https://aruljohn.com/language.php :

Language Codes | Language Names
-- | --
es-ES | Spanish
es | Spanish

**Comment by amstrad** [comment]
You can add any extra language in settings (dunno why i got two though..)

![Captura de pantalla 2019-08-23 a las 21 29 03](https://user-images.githubusercontent.com/772421/63618746-1d3d7a00-c5ed-11e9-859f-33180d783c3f.png)

**Comment by dm4t2** [comment]
Yes, the Spanish locale is completely broken. I will investigate this.

**Comment by amstrad** [comment]
Will force  locale="it" for the moment, i get the same format and seems to work oki

**Comment by dm4t2** [comment]
For some reason Chrome format currencies without a thousands separator with locale="es". I think this a bug, since it works well in other browsers. Anyway, the component must handle this. I will fix it in release 1.8.3.
