### ISSUE TITLE
Webpack Loader Issue

### ISSUE THREAD

**Issue by dammy001** [dm4t2/vue-currency-input#244]
Hello, 

I've been trying to resolve the issue below after installing this plugin in a vue 3 typescript project.

./node_modules/vue-currency-input/dist/index.esm.js 265:36
Module parse failed: Unexpected token (265:36)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     getMinValue() {
|         let min = this.toFloat(-Number.MAX_SAFE_INTEGER);
>         if (this.options.valueRange?.min !== undefined) {
|             min = Math.max(this.options.valueRange?.min, this.toFloat(-Number.MAX_SAFE_INTEGER));
|         }

What could be the issue and fix for this. Thanks.

**Comment by dm4t2** [comment]
See #228.

**Comment by dammy001** [comment]
seen thanks.
