### ISSUE TITLE
The currency does not appear in a component with conditional rendering

### ISSUE THREAD

**Issue by lmouline** [dm4t2/vue-currency-input#247]
From what I experienced, the currency is not displayed while adding a rendering condition to the input element (or one of its parent).

Here my component:

```
<template>
  <div id="app">
    <input v-if="condition" ref="inputRef" v-model="formattedValue" />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue-demi";
import useCurrencyInput from "vue-currency-input";

export default defineComponent({
  name: "App",
  components: {},
  setup() {
    const { inputRef, formattedValue } = useCurrencyInput({ currency: "EUR" });

    const condition = ref(false);
    setTimeout(() => {
      condition.value = true;
    }, 0);

    return {
      condition,
      inputRef,
      formattedValue,
    };
  },
});
</script>
```

Here the full [project](https://github.com/lmouline/vue-currency-input-error-conditinal-rendering).

**Comment by dm4t2** [comment]
Hi, you have to `useCurrencyInput` a custom SFC according to the guide: 
https://dm4t2.github.io/vue-currency-input/guide.html#usage

Then rendering conditions should work:
https://codesandbox.io/s/vue-currency-input-247-jovh3?file=/src/CurrencyInput.vue

**Comment by lmouline** [comment]
Oh Ok I missed this (important) info.
Many thanks (again :D) for your reply :)
