### ISSUE TITLE
Unable to use setValue in Nuxt 

### ISSUE THREAD

**Issue by csechuan** [dm4t2/vue-currency-input#248]
@dm4t2  For the purpose of setting default value into the input and clearing the form, i need to use setValue, but unfortunately not able to. I received these warnings:

"export 'watch' was not found in 'vue'
[Vue warn]: Error in data(): "TypeError: Object(...) is not a function"

I am using Nuxt with Vue2. I guess Vue2 doesnt have watch API exported?

**Comment by dm4t2** [comment]
For Vue 2, `watch` is exported by the Vue Composition API plugin:

`import { watch } from '@vue/composition-api'`

I updated the docs: https://dm4t2.github.io/vue-currency-input/guide.html#external-props-changes
