### ISSUE TITLE
Vue 2 example?

### ISSUE THREAD

**Issue by kevinmelo** [dm4t2/vue-currency-input#249]
I don't see any Vue 2 example, that is not using the `setup` from Vue 3.

The `vue-currency-input` v2 works with Vue 3?

**Comment by dm4t2** [comment]
> I don't see any Vue 2 example, that is not using the `setup` from Vue 3.

That's because Vue Currency Input v2 completely relies on the Vue Composition API which is can also be used in Vue 2 with the Composition API Plugin. Please read the guide: https://dm4t2.github.io/vue-currency-input/guide.html
