### ISSUE TITLE
Handling currencies that are not a part of Intl.NumberFormat

### ISSUE THREAD

**Issue by dekadentno** [dm4t2/vue-currency-input#25]
Greetings and thank you for this sweet component.

I am having problems with cryptocurrencies. Some of them are handling well (BTC, ETH...), but test bitcoin (TBTC) is (obviously) throwing an error (Invalid currency codes at new NumberFormat). 

Is there a way to manually bypass this validation?

thanks

**Comment by dm4t2** [comment]
Hi, currently not. A solution would be to allow a custom currency format to define a prefix/suffix for the crypto currency and bypass the default currency format. I have to think about it.

**Comment by dekadentno** [comment]
> Hi, currently not. A solution would be to allow a custom currency format to define a prefix/suffix for the crypto currency and bypass the default currency format. I have to think about it.

Thank you for your reply!

**Comment by dm4t2** [comment]
Support for custom currency symbols (even an empty one) is now available in release 1.10.0 🎉 

https://dm4t2.github.io/vue-currency-input/examples/#custom-currency-symbol
