### ISSUE TITLE
help compile error

### ISSUE THREAD

**Issue by karelbyte** [dm4t2/vue-currency-input#250]
i am trying to use it in a project with vue 2 and vuetify, some help 

`Failed to compile.

./node_modules/vue-currency-input/dist/index.esm.js 265:36
Module parse failed: Unexpected token (265:36)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     getMinValue() {
|         let min = this.toFloat(-Number.MAX_SAFE_INTEGER);
>         if (this.options.valueRange?.min !== undefined) {
|             min = Math.max(this.options.valueRange?.min, this.toFloat(-Number.MAX_SAFE_INTEGER));
|         }`

**Comment by dm4t2** [comment]
See https://github.com/dm4t2/vue-currency-input/discussions/243
