### ISSUE TITLE
Large numbers issue

### ISSUE THREAD

**Issue by vladninja** [dm4t2/vue-currency-input#252]
Hi. I found a bug with large numbers (more than MAX_NUMBER in JS).

How to reproduce:
https://dm4t2.github.io/vue-currency-input/playground.html
Type: "9999999999999999" after the "blur" -> returns something like MAX_NUMBER

Is it possible to add an option to operate not on floats, integers, but on strings? This solves this problem.
Thanks

**Comment by dm4t2** [comment]
Hi, this behavior is intended. You can not enter numbers greater than [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). Otherwise you would run into accuracy problems. See also #188 and #129.
