### ISSUE TITLE
Only numbers input from mobile devices

### ISSUE THREAD

**Issue by StanBoteff** [dm4t2/vue-currency-input#253]
Hello guys, the component is very good and useful! But there is the problem on mobile devices that you cannot add comma because the keyboard that is shown when you click in input field is only number and cannot swap to letters.

##Screen shot
![Screenshot from 2021-07-01 11-36-52](https://user-images.githubusercontent.com/83815440/124093577-a8e18680-da60-11eb-9e2e-89d9fe465c78.png)

**Comment by dm4t2** [comment]
Hi, do you use the `autoDecimalDigits` option? In this case, the decimal separator won't show up on the mobile numeric keyboard.

**Comment by StanBoteff** [comment]
Nope.

**Comment by dm4t2** [comment]
Can you provide a code example and your configuration?

**Comment by StanBoteff** [comment]
`<currency-input
        v-model="input"
        currency="GBP"
        :placeholder="placeholder"
        :distraction-free="false"
      />`

**Comment by dm4t2** [comment]
I can not reproduce this on the [playground](https://dm4t2.github.io/vue-currency-input/playground.html) with latest Safari on iOS.
