### ISSUE TITLE
Version 2.0.0 error with Nuxtjs

### ISSUE THREAD

**Issue by ncminh89** [dm4t2/vue-currency-input#254]
My nuxt current version is 2.15.3 and error happened as below. When I go back to version 1.22.6, everything is ok. 

![image](https://user-images.githubusercontent.com/24700470/124254959-d4916900-db53-11eb-99c1-4ad8335e0fc2.png)

**Comment by dm4t2** [comment]
v2 does not provide a Nuxt module anymore.

**Comment by JackEdwardLyons** [comment]
Is there any way to work around this? I've tried with the nuxt composition API but still no luck
