### ISSUE TITLE
initial values ​​are not displayed

### ISSUE THREAD

**Issue by Rudison** [dm4t2/vue-currency-input#256]
Good afternoon, I'm using the vue-currency-input plugin, however when I use the configuration, currency: 'BRL',
the bind stops working, however if I remove it it works again.
but this field is mandatory.

My example:
my value start with: 7
![image](https://user-images.githubusercontent.com/6667805/127378760-fa0596a5-3eea-4fbb-a6e4-665e459588c4.png)

but on the v-model he doesn't bring

![Screenshot_2](https://user-images.githubusercontent.com/6667805/127378921-78560e12-91ec-4c74-b8d2-a2dd964fae2b.png)

but if i remove the options  currency: 'BRL'

![Screenshot_1](https://user-images.githubusercontent.com/6667805/127378976-34a8689b-6a3d-4825-9d7b-d5b1bc22c3de.png)

**Comment by dm4t2** [comment]
Hi, please provide a [CodeSandbox](https://codesandbox.io/s/vue) for reproducing your issue. Thanks!

**Comment by Rudison** [comment]
https://codesandbox.io/s/admiring-rain-bpjwh?file=/package.json:79-112

it's really working, when I add the webpack it gives me these messages

![Screenshot_3](https://user-images.githubusercontent.com/6667805/127537846-ac70390c-121f-492b-9d8b-e29201cff37c.png)

**Comment by Rudison** [comment]
when I use the webpack it doesn't work, the problem is my settings, sorry for the inconvenience

**Comment by Rudison** [comment]
when I use the webpack it doesn't work, the problem is my settings that I can't adjust, sorry for the inconvenience

**Comment by dm4t2** [comment]
See discussion #243
