### ISSUE TITLE
Cannot be used with TestCafe

### ISSUE THREAD

**Issue by timrog** [dm4t2/vue-currency-input#257]
Hi there,

Is there a good reason the component [only accepts trusted input events](https://github.com/dm4t2/vue-currency-input/blob/2f81361d10b2a7fbf35b7d99567d6e22c68a3157/src/currencyInput.ts#L178)? It means UI testers like TestCafe cannot use the component as they dispatch untrusted events using script.

**Comment by dm4t2** [comment]
This check filters input events not triggered by the user. It is required to avoid recursive calls since there are programmatically triggered input events. 

But I agree that this should be solved differently.

**Comment by dm4t2** [comment]
Fixed in [2.0.1](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.1) 🎉

**Comment by timrog** [comment]
Magic! Thanks
