### ISSUE TITLE
Module parse failed: Unexpected token (33:10)

### ISSUE THREAD

**Issue by r-martins** [dm4t2/vue-currency-input#260]
Can't import module due to error below:

>  WAIT  Compiling...                                                                                                                                                          4:02:43 PM
> 
> 98% after emitting CopyPlugin
> 
>  ERROR  Failed to compile with 1 error                                                                                                                                       4:02:43 PM
> 
>  error  in ./node_modules/vue-currency-input/dist/index.esm.js
> 
> Module parse failed: Unexpected token (33:10)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | const INTEGER_PATTERN = '(0|[1-9]\\d*)';
> | class CurrencyFormat {
> \>     locale;
> |     currency;
> |     currencyDisplay;
> 
>  @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/CurrencyInput.vue?vue&type=script&lang=js 2:0-50 10:28-44
>  @ ./src/components/CurrencyInput.vue?vue&type=script&lang=js
>  @ ./src/components/CurrencyInput.vue
>  @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=js
>  @ ./src/App.vue?vue&type=script&lang=js
>  @ ./src/App.vue
>  @ ./src/main.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
> 

Something related to `locale` but can't figure out what.
I tried to replicate at sandbox but no success.

vue version: "3.1.5"
vue-currency-input: "2.0.1"
core-js: "3.16.0"

I created the project using vue-cli, selecting the components manualy (babel included), with vue 3.

**Comment by dm4t2** [comment]
Probably the same as #243.

**Comment by r-martins** [comment]
I don't think so, but ok.
I ended up by creating an alternative manually. :(
