### ISSUE TITLE
precision is not working in firefox on input

### ISSUE THREAD

**Issue by toridyar** [dm4t2/vue-currency-input#262]
precision is only working when leaving an input in firefox

These are the properties set for the input:
![image](https://user-images.githubusercontent.com/13679556/128766298-93cf4bdb-5954-40fe-90c1-f0f77c616dbc.png)

works correctly in chrome (only allows 1 decimal place)
![image](https://user-images.githubusercontent.com/13679556/128766487-58e4c6f1-937f-4564-804f-76e021e14d0a.png)

but will allow any number of decimals places in firefox (will eventually correct itself after losing focus)
![image](https://user-images.githubusercontent.com/13679556/128766432-65f7ff25-ddb9-48d5-9036-6abec3d7d3c0.png)

No errors in console

**Comment by dm4t2** [comment]
I can not reproduce your issue in the [playground](https://dm4t2.github.io/vue-currency-input/playground.html) with the latest Firefox.
