### ISSUE TITLE
When value of the input is changed externally, the input export value as String

### ISSUE THREAD

**Issue by FLopes-14** [dm4t2/vue-currency-input#267]
Hello! I'm using Vue 2 and when I create the input with an predefined value, the value is in numeric format and the input currency component returns the value as a String. It shouldn't, I was expecting to return me a Number, since it is what Im providing. However if I edit the value, the component responds correctly with a Number.
I use this guide https://dm4t2.github.io/vue-currency-input/guide.html#external-props-changes, but the problem persists.

**Comment by husayt** [comment]
thanks @dm4t2  i will try to reproduce and provide smth.
