### ISSUE TITLE
Cursor jumps to the end of the line

### ISSUE THREAD

**Issue by freakbite** [dm4t2/vue-currency-input#268]
When using the following options and removing the first digit of "1 000 000" the cursor jumps to the end of the string, instead of staying at the start of the string.

`const options = {
  currency: "SEK",
  hideGroupingSeparatorOnFocus: false,
  locale: "sv-SE",
};`

I'm using a v-text-field in vuetify.

PS: Finally a really awesome currency input component. Great work!

**Comment by dm4t2** [comment]
Hi, can you provide a minimal repo for reproducing your issue? I tried out your setup but the cursor stays correctly in front of the "0" after deleting.

**Comment by freakbite** [comment]
Ah, so sorry. I typoed the example.
It should be 1 500 000, so you end up with the cursor at the end of 500 000.
If you use 1 000 000 and go to 0 it works correctly.

I can fix and example as well if needed.

**Comment by dm4t2** [comment]
I see, thanks 👍 
This will be fixed in the next release.

**Comment by dm4t2** [comment]
Fixed in [2.1.0](https://github.com/dm4t2/vue-currency-input/releases/tag/2.1.0) 🎉
