### ISSUE TITLE
Allow usage of parseCurrency without global Vue plugin installation

### ISSUE THREAD

**Issue by johnny-dash** [dm4t2/vue-currency-input#27]
In our situation, we don't want to register the plugin globally as most of the pages are not using it. Therefore we go with directive solution which allows you to import this currency input on demand. However, this means we need to implement our own parseCurrency method and we can't config the default currency and locale (The default locale configuration is passed in as a parameter when the library is registered globally). When we creating our own `parseCurrency` function, we find that `parse` and `createCurrencyFormat` in the `parseCurrency` implementation is not exported. 

I have created a pull request to export these two functions. #26

**Comment by dm4t2** [comment]
I introduced the `parseCurrency` API method in release 1.10.0 which can be used without global Vue plugin installation.

https://dm4t2.github.io/vue-currency-input/api/#methods

**Comment by Nutcracker52** [comment]
@dm4t2 seems to be this parseCurruncy method is depreciated what you call this function in 1.17.3 and version 3? 
this is how i Used to access it in older vertions 
![image](https://user-images.githubusercontent.com/65933656/193504542-fa4085e1-ea11-4c3f-8f0b-8123f7f1e26b.png)

**Comment by kashiif** [comment]
@Nutcracker52 You can use the [`parse()`](https://github.com/dm4t2/vue-currency-input/blob/master/src/currencyFormat.ts#L62) as :

```
import { parse } from 'vue-currency-input';

...
parse(str, { locale, currency });

```
