### ISSUE TITLE
input is broken with vue 3.2.8

### ISSUE THREAD

**Issue by husayt** [dm4t2/vue-currency-input#271]
### Vue Currency Input version

2.0.2

### Vue version

3.2.8

### What browser are you using?

all browsers

### What operating system are you using?

all

### Reproduction repo/CodeSandbox

pending

### Describe your issue

I get this issue with vue 3.2.8, but it all works fine with 3.2.6
![image](https://user-images.githubusercontent.com/1169324/132019583-912dbe33-b6a0-494b-8b15-0f257f053186.png)
![image](https://user-images.githubusercontent.com/1169324/132019656-e2336b7e-de85-4aee-a6c6-9ff87b4d694b.png)
input comes empty. will try repro, but meanwhile users better need to be warned not to update to vue 3.2.8

**Comment by dm4t2** [comment]
Works for me with Vue 3.2.8. Please provide a repo or CodeSandbox.

**Comment by husayt** [comment]
I have now tried with 3.2.9 and all works fine. So whatever it was is no more issue. Thanks

**Comment by husayt** [comment]
I am reopening this as it still happens in 3.2.11. But it only happens in prod (that is why I thought it was fixed), when bundled with vite.

Will try to produce a reproduction.
in vue 3.2.7 this works fine
