### ISSUE TITLE
Distraction Free mode not working ?

### ISSUE THREAD

**Issue by redjoker011** [dm4t2/vue-currency-input#28]
Hi, Vue Currency Input is awesome, but I've just noticed that passing `distraction-free` option into global configuration and component itself is not working . The one in the example doesn't  also work or am I missing something ?

**Comment by redjoker011** [comment]
Just found out that `distraction-free` option will take effect on input `focus` , Is there a way to hide currency prefix, I think its much flexible if that's possible.
btw closing this issue

**Comment by dm4t2** [comment]
Hi, this will probably be addressed in #25 (allowing a custom currency prefix/suffix, even an empty one)
