### ISSUE TITLE
How to accomplish precision: { min: 0, max: 2 }

### ISSUE THREAD

**Issue by Sun3** [dm4t2/vue-currency-input#288]
### Vue Currency Input version

v2.1.0

### Vue version

v3.2.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Describe your issue

Since the precision range removal, you now specify the number of decimals without the option of not showing it if the user does not type in a decimal? This is a huge feature for my project. If the user types in decimal we show it but if they don't we do not show it.

Example 1 User types in 14,000 and it shows as 14,000
Example 2 User types in 14,000.44 and it shows as 14,000.44

I was trying to make it work, but it seems there is no way to have a user enter 14,000 or 14,000.44 and declare the precision. You either need to enter ```precision: 0``` or ```precision: 2```.

In my case I really need to make the ```{ min: 0, max: 2 }``` work like it used to.

Is there any way to allow the user to enter a currency and only if the user types in the . (period), then use the precision like 2?

Thank you.

**Comment by Sun3** [comment]
I tried using ```precision: undefined``` but the issue I am having is that the field will always use the decimals. My requirements for the project is for the user to type in a number with either decimals or without. By using ```{ min: 0, max: 2 }``` it allows the user to type in 14,000 or 14,000.44 but to show the decimals only if the user types the period (.) for the decimails

I hope I explained it better. Is this possible? It was before by using ```{ min: 0, max: 2 }```

Thank you.

**Comment by dm4t2** [comment]
`precision: undefined` will display decimals **only for non-integer numbers** considering the default precision of the used `currency`:

- 1 -> $1
- 1.01 -> $1.01
- 1.1 -> $1.10

`{min: 0, max: 2}` would result in:

- 1 -> $1
- 1.01 -> $1.01
- 1.1 -> $1.1 ⚠

So it meets your requirement, right?

**Comment by dm4t2** [comment]
This behavior is caused by `autoDecimalDigits`, which requires a fixed precision.

**Comment by Sun3** [comment]
I have it somewhat working. When using ```setValue(value.toFixed(3))``` I removed the ```toFixed(3)``` and used ```setValue(value)```. Then set ```precision: undefined``` it works but I noticed that it cuts the decimal points to two digits.

Is there a way around it? Like to 3 digits without setting ```precision: 3```.

Thanks.
