### ISSUE TITLE
Accessibility: When MacOS screen reader reads through page and hits vue-currency-input textbox Chrome crashes.

### ISSUE THREAD

**Issue by dueyfx** [dm4t2/vue-currency-input#293]
### Vue Currency Input version

v2.1.2

### Vue version

v3.2.0

### What browser are you using?

Chrome Version 95.0.4638.69

### What operating system are you using?

Mac OS Big Sur 11.6

### Reproduction link

https://dm4t2.github.io/vue-currency-input/playground.html

### Describe your issue

I ran into an issue on my app which uses vue-currency-input with MacOS screen reader.  I went to the playground and saw the same issue, so I'll post the repro steps for that since it will be easier. 

Repro Steps:
- Open Chrome (Version 95.0.4638.69).  
- Navigate on a single window/tab to https://dm4t2.github.io/vue-currency-input/playground.html
- Enable screen reader (CMD+F5)
- optional: use VO+A to start screen read if it hasn't started automatically.

The screen reader will start reading through each element on the page 1 by 1.  Once it reaches the vue-currency-input text box, Chrome crashes.   

For what it's worth.  The issue doesn't happen on Chrome v94.

**Comment by dm4t2** [comment]
Thanks for reporting. Some kind of funny 😀 
I also reproduced this issue with BrowserStack but I have no idea what exactly it is caused by.

With Chrome 96 (Beta) it works again.
