### ISSUE TITLE
precision: undefined defaults to two digits, it should be more

### ISSUE THREAD

**Issue by Sun3** [dm4t2/vue-currency-input#294]
### Vue Currency Input version

2.1.2

### Vue version

3.2.21

### What browser are you using?

Chrome

### What operating system are you using?

Windows 11

### Reproduction link

n/a

### Describe your issue

When using the ```precision: undefined``` it defaults the decimal number of digits to 2 (**I needed up to 3 digits**). It should allow more. I am using this because ```precision: { min: 0, max: 3 }``` is no longer available.

Any suggestions on how to accomplish this?
Thank you.

**Comment by dm4t2** [comment]
I just reopened PR #261.

**Comment by Sun3** [comment]
@dm4t2 Thanks, look forward to this feature.
