### ISSUE TITLE
Negative values not working when locale is set to nl-NL

### ISSUE THREAD

**Issue by nataliaBernarte** [dm4t2/vue-currency-input#30]
Awesome package. But I just noticed negative values don't seem to work when the locale is set to `nl-NL`. It always returns the positive value.

I've tried with some other locales (be-NL, de-DE, es-ES...) and they all seem to work. The only difference I've found so far is nl-NL adds a space between the symbol and the value. For example: `€ 23,54`.

I'm using the latest version (1.8.3). Thanks in advance!

**Comment by dm4t2** [comment]
Hi, thanks for reporting. When using locale `nl-NL` the `-` char is placed **after** the currency symbol, for example `€ -10,00`, causing some problems...

**Comment by dm4t2** [comment]
This issue will be shortly fixed in release 1.8.4.

**Comment by nataliaBernarte** [comment]
That was fast! Thanks @dm4t2 :D
