### ISSUE TITLE
setValue not working anymore inside onMounted

### ISSUE THREAD

**Issue by chaosKP** [dm4t2/vue-currency-input#310]
### Vue Currency Input version

2.3.0

### Vue version

3.2.20

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction link

https://codesandbox.io/s/using-vue-currency-input-with-quasar-veevalidate-forked-58rom?file=/src/QCurrencyInput.vue

### Describe your issue

I had everything working with version 2.1.0 and updating to 2.2.0 also works.
But if I update to 2.4.0 or 2.3.0 the inital value of the input is not set anymore.
The inital value is set via the setValue function inside the onMounted lifecycle hook.

In the code sandbox the inital value is set to 1000 and is working fine, but if the version of vue-currency-input is changed to 2.3.0 and the embedded sandbox browser page is reloaded, the inital value is not set and the input is empty.

**Comment by dm4t2** [comment]
You have to watch `inputRef` instead of using the `onMounted` hook:
https://codesandbox.io/s/using-vue-currency-input-with-quasar-veevalidate-forked-fv6xz?file=/src/QCurrencyInput.vue:881-1038

Since v2.1.0 there's a API function `parse` for parsing formatted values: see #273

**Comment by chaosKP** [comment]
Thanks, works now.
But I can't use the parse function because I get a warning inside the console about trying to call onUnmounted for a none existing element on focusing and unfocusing the input...
If I don't use the parse function no such warnings appear.
I can't reproduce it with the codesandbox so I am not opening another issue.
