### ISSUE TITLE
Doc examples are broken

### ISSUE THREAD

**Issue by Bosphoramus** [dm4t2/vue-currency-input#319]
### Vue Currency Input version

0

### Vue version

0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction link

https://dm4t2.github.io/vue-currency-input/examples.html#usage-with-quasar-veevalidate

### Describe your issue

Doc examples are not working. Codesandbox shows the following error: Cannot use import statement outside a module
Even the examples that seem to work break when you play with them.

**Comment by dm4t2** [comment]
See https://github.com/codesandbox/codesandbox-client/issues/6194.

It seems there's currently no fix or workaround. I will possibly switch to [StackBlitz](https://stackblitz.com/).

**Comment by dm4t2** [comment]
CodeSandbox fixed the Vue issue. The Examples should now work again 🎉
