### ISSUE TITLE
Bug on adding ","

### ISSUE THREAD

**Issue by SPQRInc** [dm4t2/vue-currency-input#32]
If I type the value `2,22` the input is `22,2`.

So my input is `2`, `comma`, `2`, `2`. You can see the result on this little animation:

![2019-09-16 16 25 58](https://user-images.githubusercontent.com/23051150/64966230-b2572a00-d89e-11e9-9256-6ac47c434458.gif)

## Additional information:

- vue-currency-input: 1.9.0
- Config:
```
data: () => ({
		currency: 'EUR',
	}),
```

**Comment by dm4t2** [comment]
Thanks again for reporting @SPQRInc

**Comment by dm4t2** [comment]
This bug is fixed in release 1.9.1.
