### ISSUE TITLE
Programatically set value

### ISSUE THREAD

**Issue by Bosphoramus** [dm4t2/vue-currency-input#320]
### Vue Currency Input version

latest

### Vue version

2

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction link

Would have done based on the examples on the docs but https://github.com/dm4t2/vue-currency-input/issues/319

### Describe your issue

Im trying to make a button to reset a form with a vue-currency-input component.
I want that button to set the input value to 0, but the vue-currency-input doesnt update programatically, it only does if you change it manually, typing the value.
Am i missing something? this is pretty trivial.
When the docs examples start working again, to make a reproduction would be as easy as: 
Rendering a button with a @click handler that calls a method that updates the data() value to 0. 
You will notice that the internal value changes to 0. But the formatted value that's shown on the input stays the same.

**Comment by dm4t2** [comment]
Adding a watcher on the `value` prop should solve your issue: https://dm4t2.github.io/vue-currency-input/guide.html#external-props-changes
