### ISSUE TITLE
Directive - Not formatting on first render

### ISSUE THREAD

**Issue by kevinmelo** [dm4t2/vue-currency-input#321]
### Vue Currency Input version

v1.22.1

### Vue version

V2.6.11

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction link

https://codesandbox.io/s/vue-currency-input-parse-formatted-value-forked-ttxx2u?file=/src/App.vue

### Describe your issue

When i have a model with a integer the directive render with no problem with the mask/options.

But when i have a number with decimal the direct don't render on first render.

**Comment by dm4t2** [comment]
Since `v-currency` works on formatted strings (not numbers) you have to ensure that your initial formatted value conforms to the used locale/currency. In your example, you need to change `"9.99"` ->`"9,99"` because the decimal separator is `,` and not `.`

**Comment by kevinmelo** [comment]
But in my case i have a multi language application. I need to trasnform every single register from a double/integer to a string with change comma? Is more simples to use doubles and integer?

**Comment by dm4t2** [comment]
I would suggest using the `<CurrencyInput>` component which accepts number value bindings (`v-model`) and is built on top of the `v-currency` directive.

- https://vue-currency-input-v1.netlify.app/guide/#component 
- https://github.com/dm4t2/vue-currency-input/blob/v1/src/component.js

**Comment by kevinmelo** [comment]
Thanks for commendarion but i use Quasar :/. But why the directive works with string but the component work with number?
