### ISSUE TITLE
v-model.lazy and hideGroupingSeparatorOnFocus issues in Safari

### ISSUE THREAD

**Issue by neontuna** [dm4t2/vue-currency-input#322]
### Vue Currency Input version

2.4.0

### Vue version

3.2.31

### What browser are you using?

Safari

### What operating system are you using?

macOS 12.3

### Reproduction link

https://codesandbox.io/s/cool-cookies-48jp6b

### Describe your issue

This is a little convoluted but I believe I've found a circumstance where v-currency doesn't update v-model.   This only happens in Safari (and Mobile Safari).    I think this is a combination of using `v-model.lazy` and `hideGroupingSeparatorOnFocus: false`.  When using both of these the component will not update v-model unless you clear the input.   The code sandbox should have a reproduction.

**Comment by blackjak231** [comment]
I second this issue. Its causing major issues for some end users (offer field not setting the correct price).

To add more details on the process to reproduce and the browsers : 

**What browser is the issue on ?**
-  Safari - macOS 12.6.x & macOS 13.x
-  Safari - iOS 16.2
-  Chrome - iOS 16.2

**Reproduction link**
Same as provided in original issue : https://codesandbox.io/s/cool-cookies-48jp6b

**Steps to reproduce**
1. Scenario 1 (NOK): 
  1. Click input to have focus at the end of the text
  2. Remove the last two digits and enter 77 for testing (you should then have 67 877)
  3. Click outside the input
  4. no update
  
2. Scenario 2 (OK): 
  1. Click input to have focus in the first 3 digits of the text
  2. Remove the last digit and enter 0 for testing (you should then have 60 890)
  3. Click outside the input
  4. updates
  
 Here is a gif for more visual context : 
![ezgif-2-166447a02c](https://user-images.githubusercontent.com/1529214/206733168-64db90c5-4be8-4c5c-80c3-316cc8702903.gif)

@dm4t2 The update seems to be triggered only when editing the first group of digits before the first space is encountered (ex: if the value is 123 456 789, only changing 1, 2 or 3 will update v-model).

Will check code to see if i can help with a PR, but i can't promess anything, busy schedule...

**Comment by blackjak231** [comment]
@neontuna due to the fact that onChange events are inconsistant on Webkit (not just safari), you need to check for the onBlur event.

I added a method to check the onBlur event in my "CurrencyInput.vue" component : 

```
<template>
    <input ref="inputRef" :disabled="disabled" @blur="onBlur"/>
</template>

<script>
import { watch } from 'vue'
import { useCurrencyInput } from "vue-currency-input";

export default {
    name: "CurrencyInput",
    props: {
        modelValue: [Number, String],
        options: Object,
        disabled: Boolean,
        autoEmit: {
            type: Boolean,
            default: true
        }
    },
    setup(props, { emit }) {
        const {
            inputRef,
            numberValue,
            formattedValue,
            setOptions,
            setValue
        } = useCurrencyInput(props.options, props.autoEmit)

        const onBlur = (event) => {
            if(props.modelValue !== numberValue.value) {
                // Update model value since it is not updated with "onChange"
                emit('update:modelValue', numberValue.value)
                // Check if browser is webkit to prevent duplicated "onChange" event
                if(/webkit/.test( navigator.userAgent )) {
                    emit('change', numberValue.value)
                }
            }
        }

        return { inputRef, onBlur };
    },
};
</script>
```

In my case it works fine and is doing exactly what i want it to. However, i think it would be best to implement something internally. I just do not have the time to look into the library to fix it internally.

Cheers !
