### ISSUE TITLE
v-model as object is not supported

### ISSUE THREAD

**Issue by vladninja** [dm4t2/vue-currency-input#331]
### Vue Currency Input version

v2.0.0

### Vue version

v2.6.14

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction link

https://codesandbox.io/s/distracted-matan-0oty6w?file=/src/App.vue

### Describe your issue

Hi, I am using Vue 2.6.14 + Composition API with this plugin and I have some error when I am trying to set a v-model to object key, e.g. `<CurrencyInput v-model="data.height" :options="options" />`. I have an error, which sounds like: ` Cannot assign to read only property 'height' of object '#<Object>'` when I focused on field. The input event send the correct value.

![image](https://user-images.githubusercontent.com/76119088/174453213-c8c8bff7-32a4-432c-b6f4-33c6fd60b326.png)

Additionally, when I am trying to reproduce this issue on CodeSandbox or Stackblitz I have some errors related to the vue-demi, which is using in this plugin and I can't reproduce my issue on these platforms, e.g.: https://codesandbox.io/s/distracted-matan-0oty6w?file=/src/App.vue

Could you help me with this issue?
Thanks

**Comment by dm4t2** [comment]
CodeSandbox does not work with Vue2 for some reason. Can you share a minimal reproduction repo?

**Comment by dm4t2** [comment]
I updated your CodeSandbox to Vue Currency Input v3 + Vue 2.7. 
Works for me: https://codesandbox.io/s/async-tree-vr2xxy
