### ISSUE TITLE
Cursor to jump to end of input for element-plus integration

### ISSUE THREAD

**Issue by pnowy** [dm4t2/vue-currency-input#343]
### Vue Currency Input version

v3.0.0

### Vue version

v3.2.39

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction link

https://dm4t2.github.io/vue-currency-input/examples.html#usage-with-element-plus

### Describe your issue

Hi,

it seems that there is an issue on the Chrome browser with the element-plus input usage.

The problem is that cursor to jump to end of input when try to edit the value:

![screencast 2022-09-20 19-18-17](https://user-images.githubusercontent.com/3254609/191323244-8203cd1b-4f87-4dff-add6-d69d50d92f71.gif)

I've use the default element-plus example provided in examples (including the ZIP file as there CodeSandbox had some issues with element-plus dependencies installation - just in case they do not fix it):

[currency-input.zip](https://github.com/dm4t2/vue-currency-input/files/9609957/currency-input.zip)

Hope that gif explain what is the problem (user has to click twice to edit in specific place). I've tried with pure input and worked fine so it seems like some compatibility issue.

**Comment by dm4t2** [comment]
Thanks for reporting. This is related to #338, which will be fixed shortly.
