### ISSUE TITLE
3.0.1 broken element-plus

### ISSUE THREAD

**Issue by pnowy** [dm4t2/vue-currency-input#347]
### Vue Currency Input version

v3.0.1

### Vue version

v3.2.40

### What browser are you using?

Chrome/Safari

### What operating system are you using?

MacOS

### Reproduction link

https://8b6rc.csb.app/

### Describe your issue

Hi @dm4t2 this is a follow up of https://github.com/dm4t2/vue-currency-input/issues/343

I've checked the 3.0.1 version with element-plus (on the official example and also within my own project) and it seems that the input is broken right now - I cannot enter any number (but the previous issue has been fixed so nice job 😄 ). 

Visual example below:

![screencast 2022-10-03 22-00-06](https://user-images.githubusercontent.com/3254609/193668153-e8df0402-c395-43cb-bffc-8b6202c3f6ba.gif)

During execution I was trying to put any number (or any other value) but it seems is blocked somehow right now. With the standard input there is no issues.

**Comment by dm4t2** [comment]
Using `v-model` on `<el-input>` fixes the issue:
https://codesandbox.io/s/vue-currency-input-integration-with-element-plus-devoxx?file=/src/components/ElCurrencyInput.vue

**Comment by pnowy** [comment]
Yes, indeed - that fix the issue. Thanks for the hint!
