### ISSUE TITLE
Turn formatting on/off

### ISSUE THREAD

**Issue by janeivind** [dm4t2/vue-currency-input#35]
Would love to see a config option to turn the formatting on or off (like disable: true/false).

**Comment by dm4t2** [comment]
Makes little sense to me. Can you please describe the exact use case with an example?

**Comment by janeivind** [comment]
I have a component for number/digit input that I wish to config with v-currency on or off. The best option for me is to use the plugin as a directive. I can solve my problem by using a v-if to check, but then I have to repeat a lot of code (the input-tag also set up with vee-validate):
{code}
  <div v-if="isCurrency">
    <input
    :aria-describedby="suffixKey"
    :aria-required="element.required"
    :class="classes"
    :disabled="element.disable"
    :id="element.key"
    :placeholder="element.hint"
    :size="element.maxLength"
    class="form-control"
    data-testid="input"
    type="text"
    :ref="element.key"
    v-bind="ariaInput"
    v-model="value"
    v-currency="currencyFormat"
    @change="valueUpdate"
    />
</div>
<div v-else>
    <input
    :aria-describedby="suffixKey"
    :aria-required="element.required"
    :class="classes"
    :disabled="element.disable"
    :id="element.key"
    :placeholder="element.hint"
    :size="element.maxLength"
    class="form-control"
    data-testid="input"
    type="text"
    :ref="element.key"
    v-bind="ariaInput"
    v-model="value"
    @change="valueUpdate"
    />
</div>
{code}

The data currencyFormat , set with v-currency="currencyFormat", is now set to
{code}
currencyFormat()  {
      return {
        currency: {
          prefix: null,
          suffix: null
        },
        locale: "nb-NO",
        decimalLength: this.element.precision,
        distractionFree: false
      }
    }
{code}
 So what I need here is an option to trigger if my component should use a currency formatting, like
{code}
currencyFormat()  {
      ..
        enable: this.element.currencyFormat
      }
    }
{code}

**Comment by dm4t2** [comment]
This kind of problem needs to be solved by your application and not by the `v-currency` directive. You can easily reduce the amount of duplicated code by using a computed prop for the `input` attributes or by using a wrapper component with a [render function](https://vuejs.org/v2/guide/render-function.html) that decides whether the directive should be applied or not.
