### ISSUE TITLE
changeEvent triggered multiple times

### ISSUE THREAD

**Issue by mivvm** [dm4t2/vue-currency-input#351]
### Vue Currency Input version

v3.0.1

### Vue version

v3.2.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction link

https://codesandbox.io/s/vue-currency-input-vue-3-example-forked-qx9rjp?file=/src/App.vue:66-69

### Describe your issue

changeEvent triggered multiple times

**Comment by mivvm** [comment]
changeEvent triggered multiple times

**Comment by dm4t2** [comment]
From the description, I can't see why this is actually an issue. Anyway, this should no longer happen since v3.0.1 (your CodeSandbox uses v3.0.0).
