### ISSUE TITLE
Build issue on 3.0.2

### ISSUE THREAD

**Issue by koichirose** [dm4t2/vue-currency-input#359]
### Vue Currency Input version

3.0.2

### Vue version

2.7.14

### What browser are you using?

-

### What operating system are you using?

-

### Reproduction link

-

### Describe your issue

I'm getting a few errors while building my app with Vue Currency Input 3.0.2.
I'm using Nuxt 2.15 with Vue 2.7.14.
3.0.1 is fine.

```
ERROR in ./node_modules/vue-currency-input/dist/index.mjs 729:19-27
Can't import the named export 'computed' from non EcmaScript module (only default export is available)
...
ERROR in ./node_modules/vue-currency-input/dist/index.mjs 724:11-29
Can't import the named export 'getCurrentInstance' from non EcmaScript module (only default export is available)
```
... and some more similar errors

What could be causing this?

**Comment by dm4t2** [comment]
This is fixed in Nuxt v2.16.0. See https://github.com/nuxt/nuxt.js/pull/9180
