### ISSUE TITLE
Cannot read properties of undefined (reading 'conformToMask')

### ISSUE THREAD

**Issue by VIXI0** [dm4t2/vue-currency-input#364]
### Vue Currency Input version

3.0.3

### Vue version

3

### What browser are you using?

chromium

### What operating system are you using?

win

### Reproduction link

e

### Describe your issue

3.0.3 not working with this error Cannot read properties of undefined (reading 'conformToMask') 
downgrading to 3.0.2 working.

**Comment by dm4t2** [comment]
Please provide a minimal reproduction.
