### ISSUE TITLE
autoEmit = false --> field values not updating state when valueRange option changes

### ISSUE THREAD

**Issue by Max1us** [dm4t2/vue-currency-input#365]
### Vue Currency Input version

v3.0.3

### Vue version

v3.2.45

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction link

https://codesandbox.io/s/white-sun-dv5miq

### Describe your issue

The (simplified) use case i'm trying to implement is as follows;

I have two fields. These fields have valueRanges, allowing a value within min/max.
The second field must be greater than field 1 (via computed value), but less than the configured static maximum.

I want the validation to trigger ONLY when I leave the field for obvious reasons (you'd never be able to enter your desired value if it keeps changing it by constantly validating).

The problem is that if you change the value of field 1, the MIN value then changes the value of field 2 (as it should), but no events are triggered/emitted. The displayed field value is now incorrect with what the state value of the field is.

The watches / functions I added only seem to work when I change a value manually, am I missing something?

**Comment by dm4t2** [comment]
This is a bug! Thanks for reporting 👍

**Comment by Max1us** [comment]
Hi @dm4t2 , Thanks for this - it seems to work, except in one scenario..
https://codesandbox.io/s/young-leaf-t6mkm5

The use case is that i'm displaying the same field on two different pages or tabs - depending on the ui - (in case the user wants to edit their previously input value on the results page, for example) and in that case, it is now causing a recursion error.

"Maximum recursive updates exceeded in component. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function. "

**Comment by dm4t2** [comment]
The recursion is caused by the options watcher. For some reason, it triggers even when the options have not actually changed. This is a workaround: https://codesandbox.io/s/solitary-voice-p62xjd?file=/src/components/CurrencyInput.vue

**Comment by Max1us** [comment]
@dm4t2 Thanks, that's a bit of a weird one.. and only happens when using .lazy..  
- updated my last codesandbox to use the workaround, but use a better comparison method (lodash's isEqual) if anyone else is looking at this.
