### ISSUE TITLE
Feature request: integer model

### ISSUE THREAD

**Issue by slipszenko** [dm4t2/vue-currency-input#37]
Hi, thanks for creating this component.

I was wondering if it would be possible to add in a `prop` to specify that you want to pass in and retrieve the model as an integer, as usually when working with money it is considered best practice to work with the factional part of the currency and always store an integer. Something like `:valueAsInteger="true"`.

I'd originally achieved this by wrapping the component and causing the set on a computed property to run the following code:

```js
        let valueInCents = 0;

        if (value !== null) {
          valueInCents = Number.isInteger(value)
            ? value * 100
            : parseInt((`${value}`).replace('.', ''), 10);
        }

        this.$emit('input', valueInCents);
```

But this was causing the components to enter an infinite loop growing `this.value`.

![Screenshot 2019-10-02 at 18 29 46](https://user-images.githubusercontent.com/1292645/66062932-a5933100-e542-11e9-835e-7411a3ad2e3f.png)

Alternatively, perhaps you could give me some pointers on where to start if I were to try to attempt a PR that attempted this feature.

Thank you for your time.

**Comment by slipszenko** [comment]
I've managed to achieve the effect that I was after with the following code:

```vue
<template>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text">{{ currencySymbol }}</span>
    </div>
    <currency-input
      :value="initialValue"
      :currency="{ prefix: '' }"
      :locale="$i18n.locale"
      @input="emitChangeInCents"
      class="form-control pr-1 border-radius-box-right" />
  </div>
</template>

<script>
import { CurrencyInput } from 'vue-currency-input';

export default {
  props: {
    value: Number,
    currencySymbol: String,
  },
  data() {
    return {
      // Value must be passed vue-currency-input as dollars/euros/etc.
      initialValue: this.value / 100,
    };
  },
  methods: {
    emitChangeInCents(newValue) {
      // We must return the value in cents
      let valueInCents = 0;

      if (newValue !== null) {
        valueInCents = parseInt((newValue * 100).toFixed(0), 10);
      }

      this.$emit('input', valueInCents);
    },
  },
  components: {
    CurrencyInput,
  },
};
</script>
```

Thanks!

**Comment by jonasesr** [comment]
This would be a cool feature. You have to keep in mind that not every language has 2 fraction digits. Regarding to this list: [https://www.currency-iso.org/dam/downloads/lists/list_one.xml](https://www.currency-iso.org/dam/downloads/lists/list_one.xml) there are several currencies with 3 or 4 fraction digits. A very nice feature would be to set the property `valueAsInteger` and parses it based on the `minimumFractionDigit` Option of the `Intl.NumberFormat`

```
        const formatter = new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(number)
        const options = formatter.resolvedOptions()
        let valueInCents = 0;

        if (value !== null) {
            valueInCents = Number.isInteger(value)
                ? value * Math.pow(10, options.minimumFractionDigits)
                : parseInt((`${value}`).replace('.', ''), 10);
        }

        this.$emit('input', valueInCents);
```
