### ISSUE TITLE
IOS keyboard no minus option

### ISSUE THREAD

**Issue by jobjen02** [dm4t2/vue-currency-input#372]
### Vue Currency Input version

1.22.6

### Vue version

2.6.11

### What browser are you using?

Safari - IOS

### What operating system are you using?

IOS

### Reproduction link

https://codesandbox.io/s/vue-currency-input-y8f06f

### Describe your issue

The input of an negative number is not possible on IOS. Both decimal and numeric inputmode does not support a minus on the IOS keyboard.
It doesn't have anything to do with me using a older version of the package, since it is an IOS thing.

A solution would be to allow the text keyboard or maybe another custom solution is possible.

If I'm right, this is since the release of IOS 13.

![IMG_7239](https://user-images.githubusercontent.com/25797291/216358834-5a3dfb5f-217f-4d01-ba4f-d83556974d80.PNG)

**Comment by dm4t2** [comment]
Everything is positive at Apple :laughing: 

A workaround in v3 might be to use a value range `{max: 0}`, which automatically adds a minus sign.

The best solution would be to preserve an existing `inputmode` attribute. So if you use `<input inputmode="text">`, Vue Currency Input will not override it.

**Comment by jobjen02** [comment]
If I add `inputmode="text" `, the Vue Currency Input does override it to either decimal or numeric. How can I solve that?

**Comment by dm4t2** [comment]
Until my proposal is implemented, it can be solved like this: https://codesandbox.io/s/vue-currency-input-372-5vh10h
