### ISSUE TITLE
copy paste value with dot don't insert

### ISSUE THREAD

**Issue by asnvrn** [dm4t2/vue-currency-input#374]
### Vue Currency Input version

v3.0.3

### Vue version

v3.2.37

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### Reproduction link

-

### Describe your issue

Example
copy value 12 345,67 - paste 12 345,67 - ok
copy value 12 345.67 - paste 1 234 567 - opps

please fix

**Comment by dm4t2** [comment]
This is not a bug. The decimal/grouping separator of the pasted value must conform to the configured locale.

**Locale**|**Decimal separator**|**Grouping separator**|**Value**|**Result**
:-----:|:-----:|:-----:|:-----:|:-----:
de-DE| `","`| `"."`|1.234.567| 1.234.567
de-DE| `","`| `"."`|1,234,567| 1,23
