### ISSUE TITLE
$parseCurrency is not working with Nuxt

### ISSUE THREAD

**Issue by kichigai** [dm4t2/vue-currency-input#38]
I live this plugin.
I try to using nuxt.js environment.

Everything is ok. But, `$parseCurrency` occur error.
The problem seems to be `Vue.prototype`.
How about using `mixin`.

Good decimal plugin. ^^

**Comment by dm4t2** [comment]
Thanks for reporting. To be honest, I've never tried my plugin with Nuxt before. I need to look into this.

**Comment by isaumya** [comment]
I was also thinking about asking did this plugin work with Nuxt? Keep up the good work and add Nuxt support.

**Comment by dm4t2** [comment]
I added a Nuxt module in release 1.11.0: https://dm4t2.github.io/vue-currency-input/guide/#nuxt

**Comment by kichigai** [comment]
I apply new version. and occur error.

`Cannot assign to read only property 'exports' of object '#<Object>'`

**Comment by cannap** [comment]
> I apply new version. and occur error.
> 
> `Cannot assign to read only property 'exports' of object '#<Object>'`

add it to transpile in nuxt config

**Comment by dm4t2** [comment]
The Nuxt module was erroneous. I'd better test this first, sorry 👼 

Please try release 1.11.1.

**Comment by kichigai** [comment]
Thank you your fast fix.
