### ISSUE TITLE
Quasar with vue-currency-input

### ISSUE THREAD

**Issue by kevinmelo** [dm4t2/vue-currency-input#383]
### Vue Currency Input version

V3.0.4

### Vue version

v.3.2.47

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction link

https://codesandbox.io/s/vue-currency-input-integration-with-quasar-gwn46?fontsize=14&hidenavigation=1&theme=dark

### Describe your issue

inputCurerncy is emiting `change` event, and this event trigger Quasar form validation even using '`autoEmit = false`'

Would be great, if autoEmit, disable the `change emit` ou if we could have more control about the event `onChange`

**Comment by dm4t2** [comment]
Thanks for reporting 👍
