### ISSUE TITLE
Incompatible with Nuxt 2 / Vue 2.7.14

### ISSUE THREAD

**Issue by kriansa** [dm4t2/vue-currency-input#384]
### Vue Currency Input version

3.0.4

### Vue version

2.7.14

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### Reproduction link

Instructions below

### Describe your issue

Importing `vue-currency-input` on a brand-new Nuxt 2.16.3 (Vue 2.7.14) app will result in compile errors:

```
 ERROR  Failed to compile with 5 errors
 ERROR  in ./node_modules/vue-currency-input/dist/index.mjs
Can't import the named export 'computed' from non EcmaScript module (only default export is available)

 ERROR  in ./node_modules/vue-currency-input/dist/index.mjs
Can't import the named export 'getCurrentInstance' from non EcmaScript module (only default export is available)

 ERROR  in ./node_modules/vue-currency-input/dist/index.mjs
Can't import the named export 'ref' from non EcmaScript module (only default export is available)

 ERROR  in ./node_modules/vue-currency-input/dist/index.mjs
Can't import the named export 'version' from non EcmaScript module (only default export is available)

 ERROR  in ./node_modules/vue-currency-input/dist/index.mjs
Can't import the named export 'watch' from non EcmaScript module (only default export is available)
```

## Steps to reproduce

1. Run `npx create-nuxt-app myapp` and press enter all times until it creates the project.
2. Run `yarn add vue-currency-input`
3. Add the following to the file `pages/index.vue`
    ```js
    import { useCurrencyInput } from 'vue-currency-input'
    ```
4. Run yarn dev and watch the log output

**Comment by dm4t2** [comment]
Looks like the same problem as #359. I actually thought this was fixed in Nuxt v2.16.0.  

Adding the following configuration to `nuxt.config.js` should help:
```
export default {
  build: {
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      })
    },
  },
}
```
