### ISSUE TITLE
CAD is a valid A ISO 4217 currency code but it doesnt work

### ISSUE THREAD

**Issue by marcodeluca** [dm4t2/vue-currency-input#385]
### Vue Currency Input version

3.0.4

### Vue version

3.2.40

### What browser are you using?

firefox, chrome

### What operating system are you using?

mac

### Reproduction link

na

### Describe your issue

CAD - the valid Canadian ISO 4217 currency code, doesn't work. CDN works, which is not an ISO 4217 currency. Am I missing something? Has my currency code shortform changed without us knowing?

Implemented as per the instructions, everything works and a couple dozen other currency codes all seem to be working properly. By working of course I mean it shows the code in the input when not focused:)

**Comment by dm4t2** [comment]
I can not reproduce your issue in Chrome. CAD works as expected:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/11592259/236678327-cf23f34c-7b44-497a-9408-1848043bc752.png">

**Comment by marcodeluca** [comment]
Ok so this is a browser setting issue I guess I have to figure out?

on CHROME - CAD works and USD does not.

on FIREFOX - USD works and CAD does not.

**Comment by marcodeluca** [comment]
Ok I know the issue is closed but just FYI, I didnt have the locale set so as per your documentation: 

Default is undefined (use the default locale of the Browser).

Not really sure why the ISO standard is inconsistent like that without a locale but i don't think that's an issue with this package. Thanks for the quick reply!
