### ISSUE TITLE
Different Results with Locale on Different Browsers

### ISSUE THREAD

**Issue by marcodeluca** [dm4t2/vue-currency-input#386]
### Vue Currency Input version

3.0.4

### Vue version

3.2.40

### What browser are you using?

firefox, chrome

### What operating system are you using?

OS X

### Reproduction link

na

### Describe your issue

Ok I know you just closed #385 but there's definitely something wonky with the locale. Maybe there's something Im not understanding about the relationship between the currency code and the locale.

Is the idea that you don't show the currency code if it matches the locale? Is there a way to not do that?

**This should now be changed to a question not a bug as that's probably the reason.**

Case 1: If currency code and the locale are the same country:

```
<CurrencyInput
    v-model="usdPrice"
    :options="{ currency: 'CAD', locale: 'en-US' }"
/>
```
```
<CurrencyInput
    v-model="cadPrice"
    :options="{ currency: 'CAD', locale: 'en-US' }"
/>
```

![Screenshot 2023-05-07 at 9 33 52 AM](https://user-images.githubusercontent.com/968926/236680680-2196ca02-085d-4be7-93ae-84992b991a64.png)

Case 1: If currency code and the locale are the same country:

```
<CurrencyInput
    v-model="usdPrice"
    :options="{ currency: 'CAD', locale: 'en-CA' }"
/>
```
```
<CurrencyInput
    v-model="cadPrice"
    :options="{ currency: 'CAD', locale: 'en-CA' }"
/>
```

![Screenshot 2023-05-07 at 9 35 15 AM](https://user-images.githubusercontent.com/968926/236680755-efbccc4c-317c-4ee7-80a5-c7eeae6e32c7.png)

Case 2: If Locale is not set:

```
<CurrencyInput
    v-model="usdPrice"
    :options="{ currency: 'CAD', locale: 'en-US' }"
/>
```
```
<CurrencyInput
    v-model="cadPrice"
    :options="{ currency: 'CAD', locale: 'en-US' }"
/>
```

FIREFOX:
![Screenshot 2023-05-07 at 9 36 09 AM](https://user-images.githubusercontent.com/968926/236680816-74649051-490a-46d7-b1a2-e63ab2db29e4.png)

CHROME
<img width="630" alt="Screenshot 2023-05-07 at 9 36 17 AM" src="https://user-images.githubusercontent.com/968926/236680822-0437daa1-0739-4e60-b474-cbf40efe912f.png">

**Comment by dm4t2** [comment]
Formatting relies entirely on the [ECMAScript Internationalization API (Intl.NumberFormat)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) and is outside the scope of Vue Currency Input.

Questions about this should be directed to https://github.com/tc39/ecma402
