### ISSUE TITLE
Return value as integer to simply work with e.g. Dinero.js or PHP Money

### ISSUE THREAD

**Issue by jonasesr** [dm4t2/vue-currency-input#39]
This would be a cool feature. You have to keep in mind that not every language has 2 fraction digits. Regarding to this list: [https://www.currency-iso.org/dam/downloads/lists/list_one.xml](https://www.currency-iso.org/dam/downloads/lists/list_one.xml) there are several currencies with 3 or 4 fraction digits. A very nice feature would be to set the property `valueAsInteger` and parses it based on the `minimumFractionDigit` Option of the `Intl.NumberFormat`

```
        const formatter = new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(number)
        const options = formatter.resolvedOptions()
        let valueInCents = 0;

        if (value !== null) {
            valueInCents = Number.isInteger(value)
                ? value * Math.pow(10, options.minimumFractionDigits)
                : parseInt((`${value}`).replace('.', ''), 10);
        }

        this.$emit('input', valueInCents);
```

Edit: In addition it also needs to work the other way around.

_Originally posted by @jonasesr in https://github.com/dm4t2/vue-currency-input/issues/37#issuecomment-544938017_

**Comment by karolsw3** [comment]
Agreed.

**Comment by dm4t2** [comment]
The `valueAsInteger` option has been added in [Release 1.12.0](
https://github.com/dm4t2/vue-currency-input/releases/tag/1.12.0) 🎉 

https://dm4t2.github.io/vue-currency-input/examples/#value-as-integer

**Comment by karolsw3** [comment]
Woo! That's what I call good project maintenance :) Thanks, man!
