### ISSUE TITLE
wrong result (using decimal > 10)

### ISSUE THREAD

**Issue by komgrip** [dm4t2/vue-currency-input#391]
### Vue Currency Input version

3.0.4

### Vue version

3.2.45

### What browser are you using?

Chrome

### What operating system are you using?

mac

### Reproduction link

https://codesandbox.io/s/vue-currency-input-integration-with-quasar-forked-hjorim

### Describe your issue

![Screenshot 2566-05-22 at 12 34 25](https://github.com/dm4t2/vue-currency-input/assets/84488643/cb61653a-7720-45e2-ba42-65e0cb3b5353)

**Comment by dm4t2** [comment]
This is currently a known limitation: https://github.com/dm4t2/vue-currency-input/issues?q=MAX_SAFE_INTEGER

You can vote for #346.
