### ISSUE TITLE
Component emitted event "change" but it is neither declared in the emits option nor as an "onChange" prop.

### ISSUE THREAD

**Issue by leochen-g** [dm4t2/vue-currency-input#396]
### Vue Currency Input version

v3.0.5

### Vue version

v3.2.43

### What browser are you using?

Chrome

### What operating system are you using?

Mac

### Reproduction link

no

### Describe your issue

In vue3 project, I do not want use lazy. but when I set value to input，It is warning `Component emitted event "change" but it is neither declared in the emits option nor as an "onChange" prop.`.

In Vue 3, there is an issue with this condition. If it's not lazy, the changeEvent should be "change", but it should be "update:modelValue".

**Comment by dm4t2** [comment]
Can you provide a minimal reproduction? Thanks!

**Comment by alhavizd** [comment]
same issue
```javascript
<template>
  <v-text-field ref="inputRef" v-model="getValue" density="compact" variant="outlined" autocomplete="off" :error-messages="errorMessages" class="with-mini-message" @input="changePrice" />
</template>
<script setup>
import {useCurrencyInput} from 'vue-currency-input'
import {ref, computed} from 'vue'

const {inputRef} = useCurrencyInput({
  currency: 'IDR',
  locale: 'id-ID',
  currencyDisplay: 'narrowSymbol',
  hideCurrencySymbolOnFocus: false,
  hideGroupingSeparatorOnFocus: false,
  precision: 0,
  valueRange: {min: 0}
})

const props = defineProps({
  modelValue: {
    type: [Number, String],
    default: null
  },
  errorMessages: {
    type: [String, Array],
    default: () => []
  }
})

const emit = defineEmits(['update:modelValue'])

const getValue = computed({
  get: () => props.modelValue,
  set: (val) => {
    emit('update:modelValue', val)
  }
})
</script>
```

**Comment by dm4t2** [comment]
There is actually no need to handle the emits manually in your case. 
The `useCurrencyInput` composable does this [automatically]( https://dm4t2.github.io/vue-currency-input/guide.html#auto-emit).

See also the Vuetify 3 example: https://stackblitz.com/edit/vue-currency-input-vuetify-3-dh7gm2?file=src%2Fcomponents%2FVCurrencyField.vue

**Comment by alhavizd** [comment]
thanks, it work
