### ISSUE TITLE
When setting currency input options, getting an error saying argument type is not assignable to CurrencyInputOptions

### ISSUE THREAD

**Issue by NTass02** [dm4t2/vue-currency-input#407]
### Vue Currency Input version

3.0.5

### Vue version

3.3.4

### What browser are you using?

Chrome

### What operating system are you using?

Mac

### Reproduction link

None

### Describe your issue

This is my object: <{
    currency: 'USD',
    locale: 'en',
    currencyDisplay: 'narrowSymbol',
    hideCurrencySymbolOnFocus: false,
    hideNegligibleDecimalDigitsOnFocus: false,
    valueRange: props.valueRange ? props.valueRange : undefined,
  }>

It has the correct properties and property types according to the CurrencyInputOptions type but TS is showing as if the properties and/or property types are incorrect.

**Comment by NTass02** [comment]
I had to use CurrencyDisplay.narrowSymbol versus the string 'narrowSymbol'.

**Comment by lucassimines** [comment]
Having the same issue, needed to add in my code:

```
declare enum CurrencyDisplay {
    hidden = "hidden"
}
```
