### ISSUE TITLE
Option request: Hide negligible decimal digits when NOT focused

### ISSUE THREAD

**Issue by CodeSpartan** [dm4t2/vue-currency-input#41]
For example the number 200.00 could be displayed as 200, but the number 200.20 would still be displayed as 200.20. Basically what "Hide negligible decimal digits" currently does, but without focus. It would be useful for example for online stores where most prices (but not all) are whole numbers such as $7.

**Comment by dm4t2** [comment]
I also thought about this. My plan is to extend/reuse the `decimalLength` prop to accept a `{min, max}` object. 

For example with `{min=0, max=2}`:

1.00 = $1
1.20 = $1.2
1.23 = $1.23
1.234 = $1.23

**Comment by dm4t2** [comment]
The feature is now available in [Release 1.13.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.13.0) :tada:

see https://dm4t2.github.io/vue-currency-input/examples/#precision

**Comment by KEYHAN-A** [comment]
Hi @dm4t2 ,
first, thank you for the plugin,

I used {min, max} to get rid of extra zeros that it adds after the number if you have just integer,
but now it doesn't allow me to add multiple 0 after each other,
I'm using the input for Crypto Currencies which can accept values like `0.005`

is there any way to disable 'not allowing zeros back to back or after ` . ` ' ?

thank you

**Comment by dm4t2** [comment]
Hi @KEYHAN-A, thanks for reporting. I opened a new issue: #87
