### ISSUE TITLE
Problem with attribute currencyDisplay when use Typescript

### ISSUE THREAD

**Issue by adirizky54** [dm4t2/vue-currency-input#410]
### Vue Currency Input version

v3.0.5

### Vue version

v3.3.8

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction link

https://stackblitz.com/edit/nuxt-starter-8ryhek?file=components%2FInputCurrency.vue

### Describe your issue

Got error `Type '"symbol"' is not assignable to type 'CurrencyDisplay | undefined'` when use props currencyDisplay with value `symbol`
<img width="770" alt="Screenshot 2024-01-06 at 17 00 11" src="https://github.com/dm4t2/vue-currency-input/assets/24888851/16a6e5a9-f6e7-4fdd-b0e2-3e1306a8bc3f">

**Comment by adirizky54** [comment]
I think this error because in vue-currency-input on prop currencyDisplay use enum instead union like this

<img width="770" alt="Screenshot 2024-01-06 at 17 05 57" src="https://github.com/dm4t2/vue-currency-input/assets/24888851/a654b814-24db-4989-9f2a-1b2742644c78">

**Comment by dm4t2** [comment]
You can import the CurrencyDisplay enum: https://stackblitz.com/edit/nuxt-starter-cqw9zx?file=app.vue

**Comment by adirizky54** [comment]
Personally I avoid enums

Instead of import `CurrencyDisplay` on every time when use currency input i prefer to extract value inside enum from `CurrencyDisplay` and when use that component i got correct autocompletion from vscode too

<img width="970" alt="Screenshot 2024-01-09 at 13 40 47" src="https://github.com/dm4t2/vue-currency-input/assets/24888851/ecde95de-eed3-4e95-a4ca-59a232317613">

<img width="728" alt="Screenshot 2024-01-09 at 13 38 50" src="https://github.com/dm4t2/vue-currency-input/assets/24888851/cd9228d8-c648-4389-89c4-bc04b70e4252">
