### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.numberMask.conformToMask') in IOS 12

### ISSUE THREAD

**Issue by waveo-wangxiao** [dm4t2/vue-currency-input#415]
### Vue Currency Input version

3.1.0

### Vue version

3.4.21

### What browser are you using?

Safari

### What operating system are you using?

IOS

### Reproduction link

https://dm4t2.github.io/vue-currency-input/playground.html

### Describe your issue

I'm encountering an issue using this component on iOS 12.
I opened the playground page on my old iPhone with iOS 12.5.5, and I encountered this error: TypeError: undefined is not an object (evaluating 'this.currencyFormat.format').
![Screenshot 2024-03-15 at 12 47 54 PM](https://github.com/dm4t2/vue-currency-input/assets/84308681/a4726d7b-2c78-4b71-b1b3-2d4cd4911b18)

I also attempted to add the code below as I suspected it might be due to compatibility issues. However, still encountered the same error.
Is there anyone who can assist with this issue?
```
onBeforeMount(async () => {
  if (!Intl.NumberFormat.prototype.formatToParts) {
    const intl = await import('intl');
    Intl.NumberFormat = intl.NumberFormat;
    await import('intl/locale-data/jsonp/en.js');
  }
})
```

It runs fine in IOS 15 & above

**Comment by dm4t2** [comment]
Safari@iOS 12 does not support [Intl.NumberFormat.prototype.formatToParts()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts).

See https://caniuse.com/mdn-javascript_builtins_intl_numberformat_formattoparts

You can probably polyfill formatToParts with an older version of FormatJS: https://github.com/formatjs/formatjs/blob/main/packages/intl-numberformat/CHANGELOG.md
