### ISSUE TITLE
Prevent onChange event when mounted?

### ISSUE THREAD

**Issue by JohnH-ESD** [dm4t2/vue-currency-input#421]
### Vue Currency Input version

3.0.5

### Vue version

3.3.8

### What browser are you using?

Edge, Chrome

### What operating system are you using?

Windows 10

### Reproduction link

https://stackblitz.com/edit/vue-currency-input-vuetify-3-dh7gm2-hxc3nr?file=src%2Fcomponents%2FVCurrencyField.vue,src%2FApp.vue,package.json

### Describe your issue

With the latest version of Vue (3.3.8)/Vite (4.5.0) it seems that vue-currency-input triggers a "change" event when mounted. I need it to not do this. I checked a bunch of examples in stackblitz.com that was shown in the documentation and forked them to provide my setup and it worked fine, it wasn't until I updated the packages to the version I'm using that it was triggering the change event. Something in the new version is causing that issue.

As seen in my repo link, I have a basic setup wheere I console log a message on the change event, and when mounted it gets triggered. In the older versions of Vue (3.2.45) and Vite (4.0.4) it worked fine.

Thank you!

**Comment by dm4t2** [comment]
The change event is also triggered with Vue v3.2.45 and Vite v4.0.4: 

https://stackblitz.com/edit/vue-currency-input-vuetify-3-dh7gm2-hlyyqg?file=src%2Fcomponents%2FVCurrencyField.vue,package.json

If you rely on change events you should use `v-model.lazy` with Vue 3:
https://dm4t2.github.io/vue-currency-input/guide.html#lazy-value-binding

Alternatively,  you can completely control the emit behavior on your own by disabling "auto emit":
https://dm4t2.github.io/vue-currency-input/guide.html#auto-emit

**Comment by JohnH-ESD** [comment]
Thank you for the reply but I have tried those options and it still emits a change event on mount. 

Here is a version with disabling auto-emit:
https://stackblitz.com/edit/vue-currency-input-vuetify-3-dh7gm2-xkxkwu

And here it is with the v-model.lazy:
https://stackblitz.com/edit/vue-currency-input-vuetify-3-dh7gm2-jrfhwq
