### ISSUE TITLE
Missing typescript types

### ISSUE THREAD

**Issue by ChristPetitjean** [dm4t2/vue-currency-input#44]
When importing in typescript project, we are missing Types:
![image](https://user-images.githubusercontent.com/13761085/68384900-f35e1300-0158-11ea-9b24-20c8c5218883.png)

**Comment by dm4t2** [comment]
Typescript support will be added shortly.

**Comment by ChristPetitjean** [comment]
here is a workaround to get your component work with Typescript for impatient people like me 😛 . (waiting for your implementation of course 🤣 )

> vue-currency-input.d.ts

```ts
import Vue, { Component, PluginFunction, VueConstructor, DirectiveOptions, PluginObject, DirectiveFunction } from 'vue'

interface CurrencyDirective extends PluginObject<undefined> {
    currency: DirectiveFunction;
    CurrencyDirective: Component;
}

declare const CurrencyDirective: CurrencyDirective;
export = CurrencyDirective;

declare module 'vue/types/vue' {
    interface Vue {
      $parseCurrency(formattedValue: string | number, locale: string, currency: string): number
    }
  }
```

**Comment by dm4t2** [comment]
TypeScript support has been added in [Release 1.12.0](
https://github.com/dm4t2/vue-currency-input/releases/tag/1.12.0) 🎉

**Comment by kevinmelo** [comment]
Still with the same error when using `<script lang="ts">`

**Comment by dm4t2** [comment]
> Still with the same error when using `<script lang="ts">`

Which version?
