### ISSUE TITLE
set currency position without set complete currency

### ISSUE THREAD

**Issue by ricardo17coelho** [dm4t2/vue-currency-input#46]
Is there a way to set the currency label position with a property without set the currency property ? 

something like:

   <CurrencyInput
      v-model="value"
      currencyPosition="prefiy or sufix"
      "/>

**Comment by dm4t2** [comment]
No, why you don't want to set with the `currency` prop?

**Comment by ricardo17coelho** [comment]
because if i set the `position` with the  `currency` prop, than can't use the `locale` prop for other currencies.
I will need to change the `currency` symbol every time.
or am I wrong?

**Comment by dm4t2** [comment]
The `locale` prop does not depend the on `currency` prop and will still be used for number formatting even if you set `currency` to something like `{prefix: '$ '}`. Not sure if I got you right. If not a [CodeSandbox](https://codesandbox.io/) would be helpful.
