### ISSUE TITLE
Manually settings of digit separator and removing trailing zeros from decimal

### ISSUE THREAD

**Issue by a-vasyukov** [dm4t2/vue-currency-input#48]
Hello 👋🏻

It would be great if you can add some more flexibility to number formatting.

In my case I no need any digit separators at all:
`1 234 567.1235678` -> `1 234 567.1235678`.
But if the decimal part is empty, then no need to show trailing zeros:
`12345.00000000` -> `12345`.

Thank you!

**Comment by dm4t2** [comment]
Hi, you can disable the decimal digits by setting`decimalLength` to 0.

**Comment by a-vasyukov** [comment]
> Hi, you can disable the decimal digits by setting`decimalLength` to 0.

Thanks for you reply.
But I need to set `decimalLength` option to 8, not to 0.

**Comment by dm4t2** [comment]
This will be addressed with #41.
