### ISSUE TITLE
Input field value does not default to 0 when value is deleted and input field loses focus.

### ISSUE THREAD

**Issue by HeyWrecker** [dm4t2/vue-currency-input#49]
This is by far the easiest plugin I've tried so far for currency formatting so thank you for the time and effort you've put into it. With that said, I'm running into an issue where when I highlight a value and delete it or delete the value one character at a time until there's nothing left, then click out of the input, the input field is blank.

I'm using Vuex and I've tried multiple methods of trying to force the input field to maintain a 0 value when it has lost focus, but so far have had no luck. Is there a way to maintain a default value of 0 when the field is cleared?

Thanks!

Rick

**Comment by dm4t2** [comment]
Hi, thanks for your feedback!

It's currently not possible to preserve a 0 value (instead of `null`) if the input gets cleared. But I think it's worth to introduce an option to make this configurable.

**Comment by HeyWrecker** [comment]
Great, thanks Matthias!

**Comment by dm4t2** [comment]
I think the best approach for this would be using `min=0` when input is `required`:
`<currency-input :min="0" required />`

Currently the value range is only validated for non-empty inputs.
Does this also match your use case?

**Comment by HeyWrecker** [comment]
I agree and think that sounds reasonable. The `max` attribute currently limits it to the ceiling value that is supplied when the element loses focus so it makes sense that the `min` attribute would do the same when it is supplied with a `0` value.

**Comment by dm4t2** [comment]
The feature is now available in [Release 1.13.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.13.0) :tada:

PS: I finally decided to validate the `min` value not only on required inputs.

**Comment by dm4t2** [comment]
@HeyWrecker: I revert this with [release 1.14.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.14.0). You can force a custom value via watcher if the input gets cleared: https://codesandbox.io/s/vue-currency-input-set-value-programmatically-di241

**Comment by HeyWrecker** [comment]
@dm4t2 , is there a way to use this from the directive or do I need to use it as the component? The example given uses the component.

**Comment by HeyWrecker** [comment]
@dm4t2 I "think" I was able to accomplish what I needed to do via manually emitting the "format" event like so:

`input_refund_target_element.dispatchEvent(new CustomEvent("format", { detail: { new_value } }));`

I looked at your `setValue` code and it appeared to essentially be doing the same thing internally. I do think it would be nice if the `setValue` method could be exposed via the API, but for now I think I have what I need. I'll let you know if I run into any problems. Thank you very much for your time and help!

**Comment by dm4t2** [comment]
That's a good idea. I will open an new issue for that 👍

**Comment by HeyWrecker** [comment]
@dm4t2 Matthias, do you have any experience or recommendations with  using the directive in conjunction with Vuex and computed getter/setters?

**Comment by dm4t2** [comment]
Check this out: https://codesandbox.io/s/vue-currency-input-set-value-programmatically-rv95r
