### ISSUE TITLE
Backspace won’t delete value if "currency: { suffix: ' $' }"

### ISSUE THREAD

**Issue by kms-rscholz** [dm4t2/vue-currency-input#51]
If a currency symbol is suffixed the field’s content cannot be deleted via the backspace key if the cursor is positioned to the right of the symbol and `distraction-free` is set to `false`. Ideally the backspace key would just ignore the suffixed symbol and delete the last digit of the input.

**Comment by dm4t2** [comment]
I can't reproduce the described behavior (with Chrome latest):

https://codesandbox.io/s/vue-template-zelsx

**Comment by kms-rscholz** [comment]
Thanks for checking this! While creating a minimal reproduction I managed to find the bug: https://codesandbox.io/s/codesandbox-nuxt-n5zmw

A custom watcher and the directive did not like each other …
