### ISSUE TITLE
no default export

### ISSUE THREAD

**Issue by Heartz66** [dm4t2/vue-currency-input#54]
Simply getting this error message, might be a TS issue:

` Module '"/node_modules/vue-currency-input/src/index"' has no default export.`

**Comment by Heartz66** [comment]
https://github.com/dm4t2/vue-currency-input/pull/55

**Comment by dm4t2** [comment]
Hi, how can I reproduce this? I didn't get any errors in my IDE (WebStorm)...

**Comment by dm4t2** [comment]
With [Release 1.15.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.15.0) the correct default export has been added in the types.
