### ISSUE TITLE
computed value

### ISSUE THREAD

**Issue by Heartz66** [dm4t2/vue-currency-input#56]
I'm using a computed value with get & set, whenever a set is done, the directive doesn't see the change (when the set is done outside the directive) and simply puts the value to the number without a format. Would it be possible to add a watch on the v-model of the directive that formats the value (if it isn't focused etc)?

**Comment by Heartz66** [comment]
I will be using the component instead of the directive since the component is watching the v-model value. Will this also be possible for directive?

**Comment by dm4t2** [comment]
Hi, this is not possible with the `v-currency` directive, since it works directly on the formatted string. If you need to watch for external changes you have to use the `<currency-input>` component.
