### ISSUE TITLE
Can't be null when there is min

### ISSUE THREAD

**Issue by milostimotic** [dm4t2/vue-currency-input#58]
It is not possible to set **null** value in the v-model when min property is passed.

**Comment by dm4t2** [comment]
This is actually a feature introduced with 1.13.0 (see #49).

Why would you set a `null` value if a min value is required?

**Comment by milostimotic** [comment]
Hi, thanks for the reply. 

For example someone would like to have clear inputs, and then when user starts to type something in it, than it should validate min and max values. Now `null` value and `min` can't be mixed, because input will be populated with `min` value by default if `v-model` is null.

I think that it would be better to add this as an option, so we can decide if `null` will be allowed in combination with `min` value?

**Comment by dm4t2** [comment]
You're right 👍  I will provide a more flexible solution for this.

**Comment by dm4t2** [comment]
I have reverted the changes from #49 with [Release 1.14.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.14.0). Min value validation is now only used for non-empty inputs.
