### ISSUE TITLE
Value-handling broken

### ISSUE THREAD

**Issue by SPQRInc** [dm4t2/vue-currency-input#6]
Hello,

actually I really like this component.

But: The handling of float values is broken. You can see this in your example:

Value, that is set: 1234.5 (https://github.com/dm4t2/vue-currency-input/blob/master/docs/.vuepress/components/ComponentDemo.vue#L91)

Value that is shown: 12.345,00 $ (https://dm4t2.github.io/vue-currency-input/demo/)
Raw number value: 12345

I would love to see a patch :-)

**Comment by dm4t2** [comment]
Hi, thanks for reporting. I will have a look on it.

**Comment by dm4t2** [comment]
I fixed this problem in release 1.3.1.
