### ISSUE TITLE
v-model doesn't  change if I change the currency or reached the max value

### ISSUE THREAD

**Issue by aquafun** [dm4t2/vue-currency-input#60]
I have a option to change the currency and a max value for my currency field. 
If I change the currency or reach the max value, everything is working fine and looks good but it does not safe the updated data. Even with watch. 
That's a big issue because It saves old and unusable data for me.

My field looks like this:
`<input type="text" class="small" 
	v-currency="{
		currency: selectedCurrency, 
		locale,
		distractionFree: false,
		min: currency.min,
		max: currency.max,
	}"
	v-model="$parent.$parent.fields.investmentAmount"
/>`

my `locale` value is computed.

**Comment by dm4t2** [comment]
Hi, you're right. The value binding is broken for the `v-currency` directive. I will fix that. Thanks for reporting 👍

**Comment by dm4t2** [comment]
Fixed with [Release 1.14.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.14.0)

**Comment by Grewamor** [comment]
Hi,

i only want to modify the price in the view, not in de model. And i was happy, that it not was bind to the model.
How can i reach this behavior?

**Comment by dm4t2** [comment]
@Grewamor:
Just use `value` instead of `v-model` if you don't want to have a bidirectional value binding 😉
