### ISSUE TITLE
Input can't be cleared

### ISSUE THREAD

**Issue by milostimotic** [dm4t2/vue-currency-input#63]
From version 1.14.0 input can't be cleared to `null` once it is populated. You can reproduce the issue at this link:

https://codesandbox.io/s/vue-template-s1vyv?fontsize=14&hidenavigation=1&theme=dark

**Comment by dm4t2** [comment]
Thanks again for reporting 👍 
I'll fix this soon.

**Comment by dm4t2** [comment]
Fixed with [Release 1.14.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.14.1) 🎉
