### ISSUE TITLE
Input event fires on blur, cause the field to be set as dirty (Vuelidate)

### ISSUE THREAD

**Issue by longtomjr** [dm4t2/vue-currency-input#65]
Good day. The currency input control differs from a normal <input> by firing an `input` event on blur. This is resulting in unexpected results like the field being set as dirty after blur. 

Is there a way to only fire the input event if something is being input when distraction free mode is turned off?

**Comment by dm4t2** [comment]
The `input` event only needs to be fired on blur if the value actually changes, so this can be improved 👍

**Comment by longtomjr** [comment]
Thanks a lot :)

**Comment by dm4t2** [comment]
Fixed with [Release 1.15.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.15.0) 🎉
