### ISSUE TITLE
Negative number

### ISSUE THREAD

**Issue by zefexdeveloper** [dm4t2/vue-currency-input#66]
The negative symbol is appearing before the sign `BRL`:

![image](https://user-images.githubusercontent.com/30276092/70375879-f1b37680-18e1-11ea-84d6-437136366113.png)

---

Another option that would be good is to disable negative values so it won't allow the user to press `-`. Right now even if I put the `min` and I press `-` it flicks the `R$` and disappear again.

An example is here (`numeralPositiveOnly`): https://jsfiddle.net/ankurk91/aza302c7/

This one is using `cleave.js` but I prefer this package cause I can get the integer value easier.

It would be REALLY awesome to have a way to disable negative values.

**Comment by dm4t2** [comment]
Hi, I can confirm that there are definitely issues when using a currency prefix containing a white space and `distractionFree` is disabled:

* pressing `-` + invalid char causes the input to get cleared unintentionally
* pressing `-` + number + `backspace` does not remove the previously entered number

Not sure, if those covers the problem you described.

**Comment by zefexdeveloper** [comment]
@dm4t2 

I can confirm the latter bug you mentioned: `-55555` you can't remove the last `5` pressing backspace.

And as I mentioned, having an option to disable completely negative numbers and avoid the user pressing `-` would be great, like the `cleave.js` with the `numeralPositiveOnly`.

**Comment by dm4t2** [comment]
I opened a new issue for your feature request: #67

**Comment by dm4t2** [comment]
Fixed with [Release 1.14.2](https://github.com/dm4t2/vue-currency-input/releases/tag/1.14.2) 🎉
