### ISSUE TITLE
Option to disable negative values

### ISSUE THREAD

**Issue by dm4t2** [dm4t2/vue-currency-input#67]
There should be an option to disable negative values completely, preventing the user to press `-`.

**Comment by eagleera** [comment]
any progress on this?

**Comment by dm4t2** [comment]
Currently working on this. It will be probably released with 1.16.0.

**Comment by dm4t2** [comment]
Option `allow-negative` is now available in [Release 1.16.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.16.0) 🎉 

Demo: https://dm4t2.github.io/vue-currency-input/playground/
