### ISSUE TITLE
Format input

### ISSUE THREAD

**Issue by bajki** [dm4t2/vue-currency-input#68]
Hi, is there an option to show input as 2.500,23 € but return value as 2500.23?

Thanks,
Ivan

**Comment by dm4t2** [comment]
"return value" means what? A code example would be helpful...

**Comment by npbenjohnson** [comment]
I'm guessing this is the same issue I'm having, is there a reason the directive can't store a model value the same way the component does? I'm just starting on vue coming from angular, so I don't really know where to start looking in to that yet, but I'd like to avoid putting 
`@input="property = $parseCurrency(property, format)" `
on all v-text-field's that use the directive. Also if that's what you were asking @bajki, that code should function as a workaround.

**Comment by dm4t2** [comment]
@bajki: The simplest solution is to use the `<currency-input>` component: https://dm4t2.github.io/vue-currency-input/guide/#component.

@npbenjohnson: This will not format initial or externally set values. You need adapt the implementation of the `<currency-input>` component to create something like a `<v-currency-field>`: https://codesandbox.io/s/using-vue-currency-input-with-vuetify-kd7d1
