### ISSUE TITLE
Directive over-eagerly deleting 0's

### ISSUE THREAD

**Issue by npbenjohnson** [dm4t2/vue-currency-input#69]
With
`{
    currency: 'USD',
    autoDecimalMode: false,
    precision: 2,
    distractionFree: true
  }`
using the directive on a vuetify v-text-field, typing "1.01" into a field will result in the text being 11 because typing ".0" causes ".0" to be immediately deleted

**Comment by dm4t2** [comment]
Hi, thanks for reporting 👍 
I can also reproduce this in the [examples](https://dm4t2.github.io/vue-currency-input/examples/).

**Comment by dm4t2** [comment]
Fixed with [Release 1.14.3](https://github.com/dm4t2/vue-currency-input/releases/tag/1.14.3) 🎉
