### ISSUE TITLE
hide currency

### ISSUE THREAD

**Issue by patie** [dm4t2/vue-currency-input#7]
can you add option for hide currency from input please?

**Comment by dm4t2** [comment]
Hi, what exactly do mean with "hide currency"? Please give me an example of the behavior you expect.

**Comment by patie** [comment]
Thank you for fast answer, in input is for example "1 234,50 USD" i want "1 234,50", so without currenct, "USD" in this case. Its possible add boolean option for this?

**Comment by dm4t2** [comment]
No, the component is intended to display and edit currency formatted numbers, so the currency symbol (USD) should be always a part of it.

**Comment by patie** [comment]
it would be formatted for selected currency, but with hidden currency symbol.. but ok, your library, your rules.

**Comment by linxux** [comment]
In my case, I wanna this feature for crypto-currency.

**Comment by dm4t2** [comment]
> In my case, I wanna this feature for crypto-currency.

will be addressed in #25

**Comment by dm4t2** [comment]
@patie: in release 1.10.0 there's now an option to hide the currency symbol

**Comment by MarcoLefrancois** [comment]
How to use it ?

**Comment by dm4t2** [comment]
@MarcoLefrancois 
Set the `currency` prop to `null` to hide the currency symbol permanently.
See also: https://dm4t2.github.io/vue-currency-input/config/

**Comment by laics1984** [comment]
Hi, I am using rc version that supporting vue3. currency: null isn't working

**Comment by dm4t2** [comment]
@laics1984 This is no longer supported in v2: 
https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-beta.0

see also https://github.com/dm4t2/vue-currency-input/issues/166#issuecomment-759819019
