### ISSUE TITLE
Unexpected behavior for 'value-as-integer'

### ISSUE THREAD

**Issue by aarongerig** [dm4t2/vue-currency-input#72]
Whenever you use `valueAsInteger: true` together with either a specific `locale` (e.g. `de-CH`) or a `currency` (e.g. `CHF` or even `{ prefix: '...', suffix: '...' }`) the value output is not an integer. Instead you get the whole string back.

**Steps to reproduce**

1. Define either locale or currency
``` html
<input
  v-model.number="form.price"
  v-currency="{
    currency: { prefix: 'Fr. ', suffix: '.–' },
    locale: 'de-CH',
    precision: 0,
    valueAsInteger: true,
  }"
/>
```

2. Type something in the field and check Vue Devtools.

Input: `100`
Displays: `Fr. 100.–`
Expected Output: `100`
Current Output: `Fr. 100.–`

**Comment by dm4t2** [comment]
Hi, this behavior has nothing to do with `valueAsInteger`. You can **not** bind a number with `v-model` when using the `v-currency` directive. It works directly on the displayed (formatted) value.

See also: https://dm4t2.github.io/vue-currency-input/guide/#directive (perhaps this needs to be more clarified in the docs)

You have to use the `<currency-input>` component. Is there a reason why not to use it?

PS: `valueAsInteger: true` is senseless when using `precision: 0` 😉

**Comment by aarongerig** [comment]
Oh, I haven't seen that – sorry! I refactored to use the `CurrencyInput` component and now I get an integer as value. Thank you for explaining. 👍 

Unfortunately, there's another issue when changing the `v-model`'s value, but I'm going to create another issue for that...
