### ISSUE TITLE
Can't change data when v-model and min is used in combination

### ISSUE THREAD

**Issue by aarongerig** [dm4t2/vue-currency-input#73]
The value bound to the currency input field via `v-model` doesn't change, if a `min` value is set and you'd like to change both to a lower value.

**Example**
Current `v-model` and `min` value: 1000
Try changing both to something lower: e.g. 300

**Steps to reproduce**
1. Type into the first field something higher than 1000 (default value) --> value should change to the higher value without any problems.
2. Then type in something lower than 1000 (e.g. 300) --> value changes back to the original value of 1000.

Reproduction link: https://codesandbox.io/s/vue-currency-input-bug-i0mcw

In Vue-Devtools I can see the `min` value changing correctly, but the v-model's value doesn't change. I have tried to use `this.$set()` and `this.$refs.currencyInput.setValue()`, both make no difference.

**Comment by dm4t2** [comment]
This is intended. If a value range is configured, the initial value or a externally set value is validated and automatically falls back to the respective `min` or `max` value.

**Comment by aarongerig** [comment]
@dm4t2 Exactly, what you describe is correct behavior. But what if you change the value range as well (min and/or max), the new input value should be accepted right?

**Before**
min: 3000
value: 3000

**Applying changes**
set min to 100
set value to also 100

**After**
min: 100
value: 3000

This is not correct behavior, right?

**Comment by dm4t2** [comment]
This is the correct behavior, since the value will only be updated if it falls below `min` (in your case is `value` > `min`) . I forked your [CodeSandbox](https://codesandbox.io/s/vue-currency-input-bug-u7cmh) for demonstrating.

See also https://dm4t2.github.io/vue-currency-input/examples/#value-range

**Comment by aarongerig** [comment]
Nonetheless, that behavior confuses me. I expected to be able to change the `min` value to whatever I want and also change the value to whatever I want, but apparently that doesn't work.

Anyways, I found a workaround for me use case. Thank you for explaining!
