### ISSUE TITLE
Vuetify input and new API method setValue

### ISSUE THREAD

**Issue by wyllyan** [dm4t2/vue-currency-input#74]
Hi!
It seems that the method setValue only works with html inputs. Tested here and it works...
But with Vuetify text field the console shows "el.dispatchEvent is not a function".

**Comment by dm4t2** [comment]
Hi, that's right. 
You can't use `setValue` on Vue components directly. You have to use it on the input element of the `<v-text-field>` component which is accessible by `$refs.type`. 

Check out my `<v-currency-field>` for an example: 
https://codesandbox.io/s/using-vue-currency-input-with-vuetify-kd7d1

**Comment by alesvaupotic** [comment]
Matthias,

sorry for bringing this back up but your example is producing errors if not parsing with `valueAsInteger: false` like here:
```
      this.$emit("input", parseCurrency(value, {valueAsInteger:false}));
```

![image](https://user-images.githubusercontent.com/1660347/82725549-02b04280-9cde-11ea-9c63-627f18b727f9.png)

Kudos for the component!

**Comment by dm4t2** [comment]
@alesvaupotic This was caused by the missing `options` argument of the `parseCurrency` method. I fixed this in the example.

**Comment by gabrielpeixoto** [comment]
I'm getting this error:
`TypeError: Cannot read properties of undefined (reading 'getValue')`
