### ISSUE TITLE
Option to pass tag attributes

### ISSUE THREAD

**Issue by spotman** [dm4t2/vue-currency-input#76]
Hi there!

First of all, thank you for this component. There is no option to pass `<input>` tag attributes like `id`, `name` `readonly`, `disabled`, `placeholder`, etc. May I ask you to add them to CurrencyInput component? Implementing `attributes` prop (Object) may be a good idea too.

Cheers,
Denis.

**Comment by dm4t2** [comment]
This is already supported. You can pass any HTML attribute to component, for example:
`<currency-input required class="my-input" placeholder="Enter amount"/>`
