### ISSUE TITLE
Allow v-currency directive on contenteditable elements

### ISSUE THREAD

**Issue by dm4t2** [dm4t2/vue-currency-input#77]
The `<v-currency>` should be applicable also on `contenteditable` elements, for example `<div contenteditable v-currency/>`.

**Comment by dm4t2** [comment]
After some prototyping I finally came to conclusion to abandon this feature. The behavior comparing to `input` elements is too different across multiple browsers.

**Comment by VanishMax** [comment]
Wait a second. At least, you could allow people to create their own behaviour working with contenteditable by exporting a function that. If directive on contenteditable is not a workaround, then #85  is a solution for interested people.
