### ISSUE TITLE
Add support for "lazy" value binding

### ISSUE THREAD

**Issue by Heartz66** [dm4t2/vue-currency-input#78]
I have 2 input fields with the same v-model value (using computed values for currency conversion purposes). When input field 1 is updated, it will trigger the value-range validation because input field 2 is changed without being focused (I assume). This way it's currently impossible to type a value lower then the `min` of the value range on input field 1.

**Comment by Heartz66** [comment]
https://codesandbox.io/s/vue-currency-input-0rqeg?fontsize=14&hidenavigation=1&theme=dark

**Comment by Heartz66** [comment]
I think a way to solve this is by adding support for `v-model.lazy`. This will not trigger the update on the second field whenever there is input on the first field, it will only trigger on `change`/`blur`.

**Comment by dm4t2** [comment]
Sounds good to me. I will have a look on it.

**Comment by dm4t2** [comment]
Lazy value binding is now supported with [Release 1.16.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.16.0) 🎉 

see: https://dm4t2.github.io/vue-currency-input/guide/#lazy-value-binding
