### ISSUE TITLE
How to change a comma to a point

### ISSUE THREAD

**Issue by VisualMafia** [dm4t2/vue-currency-input#79]
Change of location does not help. Thanks

**Comment by VisualMafia** [comment]
locale: 'en'

**Comment by dm4t2** [comment]
Yes, the decimal symbol depends (among other parts of the formatting) on the configured `locale`.

**Comment by VisualMafia** [comment]
Is it possible to remove the comma in the division of numbers? This kind of look is needed: 10,000.00 => 10 000.00 or 10000.00 ?

**Comment by VisualMafia** [comment]
This format 10,000.00 breaks validation in Vee validate. 10 000.00 or 10000.00 solves the problem.

**Comment by VisualMafia** [comment]
I solved the issue by writing custom validation. Maybe someone will come in handy. But if you could easily change the format, it would be great.

extend('min_value_custom', {
	validate(value, args) {
		return parseFloat(value).toFixed(2) >= parseFloat(args.value.replace(/,/g, "")).toFixed(2);
	},
	params: ['value'],
	message: 'Message'
});

**Comment by dm4t2** [comment]
I have no plans to do so. 

PS: You might want to use https://dm4t2.github.io/vue-currency-input/api/#parsecurrency for your custom validator or use the the built-in value range validation.

**Comment by VisualMafia** [comment]
ok, thanks!
