### ISSUE TITLE
Currency symbol is missing if :distraction-free is set to false

### ISSUE THREAD

**Issue by SPQRInc** [dm4t2/vue-currency-input#8]
If  :distraction-free is set to `false`, the input is not rendered correctly if input has decimals. The currency symbol is missing and the cursor is moving to left.

Example:
![2019-04-15 18 37 01](https://user-images.githubusercontent.com/23051150/56149779-97118700-5fad-11e9-8c14-1de1228ad7fd.gif)

**Comment by dm4t2** [comment]
Hi, thanks for reporting. I can reproduce this if the `distraction-free` prop set to `true` (not `false` as you described) and 2 fraction digits are entered manually.

**Comment by SPQRInc** [comment]
My bad, it was the case, if I set it to `undef`. 

But thanks for your support, I love to see that you are fixing bugs quickly :-) Thanks for your work :-)

**Comment by dm4t2** [comment]
I fixed this bug in release 1.3.2.
