### ISSUE TITLE
value-range overwrites while typing

### ISSUE THREAD

**Issue by Heartz66** [dm4t2/vue-currency-input#80]
Some users would like to remove all the digits before they type in a number. For example, if they want to type 200 EUR, they will remove all digits and start typing 200, this is currently not possible because if you go under the value-range `min`, it will simply overwrite it with the min value-range.

Would it be possible to do validation check for value-range on `blur` event?

https://codesandbox.io/s/vue-currency-input-bf6ws?fontsize=14&hidenavigation=1&theme=dark

EDIT: Just came to the conclusion that this only happens if Value As Integer is enabled.

**Comment by dm4t2** [comment]
This is related to #78. The `<currency-input>` has a watcher on the value prop to force validation on external value changes. So if two inputs share the same value they will play ping-pong 🎾
