### ISSUE TITLE
Decimal and thousands separator through props

### ISSUE THREAD

**Issue by milostimotic** [dm4t2/vue-currency-input#81]
Is there an option to set thousand and decimal separator as props? As I see, at this time it is only possible to set it up with `locale` prop, but it would be also good to support this options.

```
<currency-input 
    v-model="value"
    thousands="."
    decimal=","
/>
```

**Comment by dm4t2** [comment]
Hi, why won't you use a suitable `locale`?

**Comment by milostimotic** [comment]
Hi,

Locale is good option but for example someone might have in the application settings to decide what will be decimal and what will be thousand separator. v-money library have this option implemented. I think that prop e.g. `separator: {thousands, decimals}` would be a good feature that can override `locale` prop if is set.

**Comment by dm4t2** [comment]
This won't be supported, since Vue Currency Input aims to offer an language-dependent, ISO-compliant currency formatting based on [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat).
