### ISSUE TITLE
method to revert parseCurrency

### ISSUE THREAD

**Issue by eagleera** [dm4t2/vue-currency-input#82]
a method to go from a number to a currency value
Example:
let currency = convertNumber(24, options);
currency value is now $24,00

**Comment by visgotti** [comment]
im on it

**Comment by visgotti** [comment]
Well- I started a [branch](https://github.com/visgotti/vue-currency-input/tree/parse-number-to-currency-api)

Got pretty frustrated with it.. trying to reverse the implementation doesn't really work in reverse for a couple reasons.. it seems his code is catered to entering input. After about an hour and a half of fiddling with it I decided it's better to just use the native [Internationalization API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) instead. I'm sure you can write a wrapper around it if you want, or you can try to finish off my code. But I don't plan on finishing out my branch anymore. 

Note: I also noticed the master branch is failing tests.

**Comment by dm4t2** [comment]
@eagleera: What is the use case for this?

**Comment by eagleera** [comment]
> @eagleera: What is the use case for this?

To set the value of an input programmatically, I tried this approach you made: https://codesandbox.io/s/vue-currency-input-set-value-programmatically-di241
but it doesn't seem to work when using it with buefy inputs  (https://buefy.org/documentation/input)

**Comment by dm4t2** [comment]
You can easily use the `setValue` API method for that:
https://dm4t2.github.io/vue-currency-input/api/#setvalue

It takes a `HTMLInputElement` as argument which is accessible by `$refs.input` in case of `b-input`.

Checkout this CodeSandbox:
https://codesandbox.io/s/vue-currency-input-set-value-on-buefy-input-component-programmatically-j3iq8

**Comment by eagleera** [comment]
> You can easily use the `setValue` API method for that:
> https://dm4t2.github.io/vue-currency-input/api/#setvalue
> 
> It takes a `HTMLInputElement` as argument which is accessible by `$refs.input` in case of `b-input`.
> 
> Checkout this CodeSandbox:
> https://codesandbox.io/s/vue-currency-input-set-value-on-buefy-input-component-programmatically-j3iq8

It worked! thanks for the codesandbox!

**Comment by bkarlson** [comment]
I just stumbled upon this: our DB keeps number values, and in our components we use `v-currency` directive (attached to a framework's input component) so upon population our price fields are empty, because `v-currency- expects formatted strings instead of numbers. 

Easy solution was to iterate over received data and create priceStr values: 

```
priceStr = new Intl.NumberFormat(this.locale, {
        style: 'currency',
        currency: this.currency
      }).format(price)
```

I'm not certain though if it properly converts all possible currency/locale combinations into format expected by vue-currency, but at least for Euro we got it working fine.

**Comment by dm4t2** [comment]
@bkarlson 
Why not use the `setValue` API method?

https://dm4t2.github.io/vue-currency-input/api/#setvalue
https://codesandbox.io/s/vue-currency-input-set-value-programmatically-rv95r?file=/src/App.vue

**Comment by bkarlson** [comment]
@dm4t2, thanks for follow up. Can `setValue` be used to _return_ a value instead of setting? Because I need to display currency value in a `span` based on a number value in a `v-for` loop, and I cannot see how `setValue` can be used in such case. Sample code:

```js
<div v-for="...">
...
                <SfPrice v-if="item.itemPrice"
                         :regular="formatPrice(item.itemPrice)"
                      />
</div>
```
