### ISSUE TITLE
Negative value for local sv-SE and for currency 'kr' is not supported .

### ISSUE THREAD

**Issue by varun761** [dm4t2/vue-currency-input#84]
A negative value like -10,000 kr is not supported. The negative sign is replaced every time.

**Comment by dm4t2** [comment]
Hi, thanks for reporting. There definitely an issue because the locale dependent minus symbol `−` (U+2212) for `sv-SE` differs from the default one `-` (Hyphen-minus, U+002D).

**Comment by dm4t2** [comment]
Fixed with [Release 1.16.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.16.1) 🎉

**Comment by varun761** [comment]
Thanks . I appreciate that . Good work .
