### ISSUE TITLE
Input can't be cleared when using value as integer

### ISSUE THREAD

**Issue by Heartz66** [dm4t2/vue-currency-input#86]
I'm not sure how these issues are caused and on which conditions but these errors are being reported to me: 

`Unable to get property 'toFixed' of undefined or null reference`

`Cannot read property 'toFixed' of null`

**Comment by dm4t2** [comment]
Thanks for reporting. This occurs when clearing the input while using both `valueAsInteger` and a lazy value binding.

**Comment by dm4t2** [comment]
Fixed with [Release 1.16.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.16.1) 🎉
