### ISSUE TITLE
Mobile pop up keyboard not numeric

### ISSUE THREAD

**Issue by kgolding** [dm4t2/vue-currency-input#88]
On mobile browsers, the pop-up keyboard displays the full version rather than the numeric format. I believe this is due to the input being of type "text" and not "number"

**Comment by dm4t2** [comment]
Hi, you can use `<currency-input inputmode="decimal"/>`, which is supported by the most mobile browsers: https://caniuse.com/#feat=input-inputmode

I will add this as default for the `<currency-input>` in next release.

**Comment by kgolding** [comment]
That works as a quick fix, and I think it should be the default too :)

**Comment by dm4t2** [comment]
With [Release 1.17.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.17.0) the `inputmode` attribute is set automatically to `decimal`. When `autoDecimalMode` is enabled, it is set to `numeric` (to hide the decimal separator on the keyboard).
