### ISSUE TITLE
Component change event is not triggered

### ISSUE THREAD

**Issue by DevelGitH** [dm4t2/vue-currency-input#91]
After the newest release 1.17.0 the component events are not triggered at all.
On my example the method test should be triggered on every input change.

https://codesandbox.io/s/boring-sun-1ejs2

**Comment by dm4t2** [comment]
Thanks for reporting. I will fix this shortly.

**Comment by dm4t2** [comment]
Fixed with [Release 1.17.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.17.1) 🎉
