### ISSUE TITLE
@Input event is emitted every time the value changes rather than on input

### ISSUE THREAD

**Issue by robjbrain** [dm4t2/vue-currency-input#92]
I'm not sure how to give a codepen example of this, but it seems like @input is emitted every time the value changes rather than just from input, which is different to the behaviour of a normal <input> element.

 which has @input when a user inputs and @change when the value changes.

I found this because I was doing something similar to.

```
<template>
    <currency-input
            :value="value"
            @input="onInput"
            :precision="{min:0,max:8}"
            :distraction-free="false"
    />
</template>
<script>
export default {
    data() {
        return {
            value: null
        }
    },
    methods: {
        onInput(value) {
            saveViaAjaxRequest(value)
                .then(response => {
                    // Here it was returning a slightly different number of decimal places and it was a string, thus triggering the change event on the currency component again.
                    this.value = response.value
                })
        }
    }
}
</script>
```

This would cause an endless loop of `onInput` triggering `@change` which triggered `onInput`

I realise you could say it's just a big in my code/api and that I should make the format identical, but really there should be a way to distinguish between the value changing and the user changing it.

The way I usually see this resolved in different plugins is to emit `@input` on user input and emit `@change` whenever the value changes.

I'm not sure if there are other instances when this loop may occur, I don't think it's limited to ajax requests, it could happen in any circumstance.

**Comment by dm4t2** [comment]
You should not randomly mutate the `value` in the `input` event handler since this will trigger the watcher on the `value` prop causing the described infinite loop.

You can rather call your API in the `change` event handler:
https://codesandbox.io/s/interesting-brook-we9yg

Hope this helps!

**Comment by robjbrain** [comment]
From your demo it seems like change is only called on blur? This means the change would not be saved if a user does not blur the field.

It's common to save while typing and use a `debounce` function to limit the number of times the api is called, but that doesn't seem possible if you're using `@change`.

Maybe i've misunderstood?

**Comment by dm4t2** [comment]
That's right. The `change` event is triggered when the input loses the focus (and the value has actually been changed).

https://dm4t2.github.io/vue-currency-input/guide/#lazy-value-binding

**Comment by dm4t2** [comment]
See #326
