### ISSUE TITLE
node-gyp

### ISSUE THREAD

**Issue by Dissociable** [dm4t2/vue-currency-input#94]
Hello,
by using v1.17.2 i keep getting errors related to node-gyp and it's build/rebuild errors.
It also wants Microsoft Visual Studio installed + Desktop development with C++
Why it need them?

**Comment by dm4t2** [comment]
Hi, you need to install Node.js 13 with the necessary tools on Windows:

![image](https://user-images.githubusercontent.com/11592259/76162010-33e69100-6139-11ea-9a53-adb080c4edae.png)

https://github.com/nodejs/node-gyp#on-windows
