### ISSUE TITLE
Support LTS versions of Node.js

### ISSUE THREAD

**Issue by viaregio** [dm4t2/vue-currency-input#96]
Please support at least the latest LTS version of Node.js (12.16.1). Since version 1.17.2 only versions >=13 are supported.

**Comment by dm4t2** [comment]
My fault, node 13 should only be required for development/ci environments. This is also related to #94.

I fixed this in [Release 1.17.3](https://github.com/dm4t2/vue-currency-input/releases/tag/1.17.3) 🎉
