### ISSUE TITLE
value-as-integer prop usage

### ISSUE THREAD

**Issue by Dantonyswamy** [dm4t2/vue-currency-input#99]
I am trying to pass the prop `value-as-integer` mentioned on the config reference to obtain the integer value of the input amount by using the `v-currency` directive and its not working. Below is the usage of the directive on a vuetify text field component.  
```
<v-text-field
          v-model.number="productPrice"
          v-currency="{ currency: 'CAD', locale: 'en', valueasinteger: true }"
          outlined
          color="#536dfe"
     />
```

**Comment by galopez1995** [comment]
Hi, I have the same problem. the valueAsInteger works when using the component currency-input but when using the Directive on v-text-field it does not work.

`<currency-input
                    :valueAsInteger="true"
                    v-model="value"
                    currency="EUR"
                    locale="de"
                  />

  <v-text-field
                    v-model="value"             
                    v-currency="{ currency: 'EUR', locale: 'de', valueAsInteger: true }"
                  > </v-text-field> 
`

**Comment by dm4t2** [comment]
Works fine for me:
https://codesandbox.io/s/using-vue-currency-input-with-vuetify-1l83s

**Comment by galopez1995** [comment]
Hi appreciate your response.

make the modification you indicated but the output in the model is still the number with the format.

In this case, I require the display to show "1,000,000 US $" but in the 1,000,000 model

attached image
![image](https://user-images.githubusercontent.com/12545405/76909383-17550200-6879-11ea-942c-d40fe6ed301f.png)


if i use <currency-input> if it works

![image](https://user-images.githubusercontent.com/12545405/76909673-e2957a80-6879-11ea-86c2-7b631321def8.png)

regards,

**Comment by dm4t2** [comment]
@galopez1995 When using the `v-currency` directive the emitted value will always be a string: https://dm4t2.github.io/vue-currency-input/guide/#directive

**Comment by dmitry** [comment]
@dm4t2 any reason for that? How to cast it to integer in this case? May be it's better to add some additional option item to emit casted value?

**Comment by dm4t2** [comment]
@dmitry This is technically conditioned. You can not use a number with `v-model` when using the `v-currency` directive since it works directly on the formatted string. You need an additional state to handle both the displayed (formatted) value and its internal representation (number). This should be encapsulated in a custom component, see this Vuetify example:

https://codesandbox.io/s/using-vue-currency-input-with-vuetify-kd7d1?file=/src/components/VCurrencyField.vue
